Repository kyma-project/serverless, pull requests merged in 2022-12, with the labels that each got.

#24 Upgrade codeowners
  CODEOWNERS
Labels: size/M, lgtm

#25 Make README useful again
  Makefile
  README.md
  hack/create-k3d-cluster.sh
  hack/get_kyma_localhost_registry_name.sh
  hack/local/serverless/Makefile
  hack/verify_kyma_status.sh
Labels: lgtm, size/L

#30 Edit codeowners
  CODEOWNERS
  OWNERS_ALIASES
Labels: size/S, lgtm

#29 README improvement
  README.md
Labels: documentation, size/M, area/serverless, lgtm, area/documentation

#34 Add makefile for pipeline
  hack/ci/Makefile
Labels: size/S, lgtm

#31 Add workaround for old git version for vm
  .gitignore
  module-chart/Chart.yaml
  module-chart/README.md
  module-chart/charts/docker-registry/.helmignore
  module-chart/charts/docker-registry/Chart.yaml
  module-chart/charts/docker-registry/README.md
  module-chart/charts/docker-registry/templates/NOTES.txt
  module-chart/charts/docker-registry/templates/_helpers.tpl
  module-chart/charts/docker-registry/templates/configmap.yaml
  module-chart/charts/docker-registry/templates/cronjob.yaml
  module-chart/charts/docker-registry/templates/deployment.yaml
  module-chart/charts/docker-registry/templates/destination-rule.yaml
  module-chart/charts/docker-registry/templates/ingress.yaml
  module-chart/charts/docker-registry/templates/poddisruptionbudget.yaml
  module-chart/charts/docker-registry/templates/pvc.yaml
  module-chart/charts/docker-registry/templates/rbac.yaml
  module-chart/charts/docker-registry/templates/secret.yaml
  module-chart/charts/docker-registry/templates/service.yaml
  module-chart/charts/docker-registry/values.yaml
  module-chart/charts/k3s-tests/Chart.yaml
  module-chart/charts/k3s-tests/README.md
  module-chart/charts/k3s-tests/templates/_helpers.tpl
  module-chart/charts/k3s-tests/templates/k3s-test.yaml
  module-chart/charts/k3s-tests/values.yaml
  module-chart/charts/webhook/Chart.yaml
  module-chart/charts/webhook/README.md
  module-chart/charts/webhook/templates/_helpers.tpl
  module-chart/charts/webhook/templates/cluster-role-binding.yaml
  module-chart/charts/webhook/templates/cluster-role.yaml
  module-chart/charts/webhook/templates/config-observability.yaml
  module-chart/charts/webhook/templates/configmap.yaml
  module-chart/charts/webhook/templates/deployment.yaml
  module-chart/charts/webhook/templates/secret.yaml
  module-chart/charts/webhook/templates/service-account.yaml
  module-chart/charts/webhook/templates/service.yaml
  module-chart/charts/webhook/templates/webhooks.yaml
  module-chart/charts/webhook/values.yaml
  module-chart/profile-evaluation.yaml
  module-chart/profile-production.yaml
  module-chart/templates/_helper_tests.txt
  module-chart/templates/_helpers.tpl
  module-chart/templates/cluster-role-binding.yaml
  module-chart/templates/cluster-role.yaml
  module-chart/templates/configmap.yaml
  module-chart/templates/daemonset-certs-configmap.yaml
  module-chart/templates/daemonset-certs.yaml
  module-chart/templates/daemonset-service-account.yaml
  module-chart/templates/deployment.yaml
  module-chart/templates/function-dashboard.yaml
  module-chart/templates/function-metrics-dashboard.yaml
  module-chart/templates/leader-election-role-binding.yaml
  module-chart/templates/leader-election-role.yaml
  module-chart/templates/runtimes.yaml
  module-chart/templates/secrets.yaml
  module-chart/templates/service-accounts.yaml
  module-chart/templates/service-monitor.yaml
  module-chart/templates/service.yaml
  module-chart/templates/virtualservice.yaml
  module-chart/values.yaml
Labels: lgtm, size/XXL

#35 Improve reconciliation loop
  Makefile
  api/v1alpha1/serverless_helpers.go
  api/v1alpha1/serverless_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_serverlesses.yaml
  controllers/serverless_controller.go
  controllers/serverless_controller_rbac.go
  controllers/serverless_controller_test.go
  controllers/suite_test.go
  controllers/testhelper_test.go
  go.mod
  go.sum
  internal/dependencies/optional.go
  internal/dependencies/prerequisites.go
  internal/dependencies/prerequisites_test.go
  internal/state/fsm.go
  internal/state/fsm_test.go
  internal/state/new.go
  internal/state/state_functions.go
  main.go
  pkg/reconciler/reconciler.go
Labels: lgtm, size/XXL
