Repository kyma-project/serverless, pull requests merged in 2022-11, with the labels that each got.

#4 Serverless manager scaffold
  .dockerignore
  .gitignore
  Dockerfile
  Makefile
  PROJECT
  README.md
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/serverless_helpers.go
  api/v1alpha1/serverless_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config.yaml
  config/crd/bases/operator.kyma-project.io_serverlesses.yaml
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/crd/patches/cainjection_in_serverlesses.yaml
  config/crd/patches/webhook_in_serverlesses.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/serverless_editor_role.yaml
  config/rbac/serverless_viewer_role.yaml
  config/rbac/service_account.yaml
  config/samples/operator_v1alpha1_serverless_k3d.yaml
  controllers/serverless_controller.go
  controllers/serverless_controller_test.go
  controllers/suite_test.go
  go.mod
  go.sum
  hack/boilerplate.go.txt
  hack/create-k3d-cluster.sh
  hack/get_kyma_file_name.sh
  main.go
Labels: lgtm, size/XXL

#8 Implement test scenarios
  .gitignore
  Makefile
  config/rbac/role.yaml
  config/samples/operator_v1alpha1_serverless_k3d.yaml
  controllers/serverless_controller.go
  controllers/serverless_controller_test.go
  controllers/suite_test.go
  controllers/testhelper_test.go
  go.mod
  go.sum
Labels: lgtm, size/L

#2 Design configurability and dependency management for modular serverless
  .gitignore
  README.md
  docs/assets/modular-serverless.drawio.svg
  docs/configurability-of-serverless.md
Labels: size/M, lgtm, area/documentation, architecture

#10 Fix makefile (cli) and empty spec
  Makefile
  config/samples/operator_v1alpha1_serverless_k3d.yaml
Labels: lgtm, size/XS

#19 Disable internal registry by default
  api/v1alpha1/serverless_helpers.go
Labels: lgtm, size/XS

#18 Fix operator image propagation
  Makefile
  config/manager/manager.yaml
Labels: lgtm, size/XS

#23 Implement hack helpers to run manager locally
  api/v1alpha1/serverless_types.go
  config/default/kustomization.yaml
  config/manager/kustomization.yaml
  config/samples/operator_v1alpha1_serverless_k3d.yaml
  controllers/serverless_controller.go
  controllers/serverless_controller_test.go
  controllers/testhelper_test.go
  go.mod
  go.sum
  hack/get_kyma_localhost_registry_name.sh
  hack/local/Makefile
  hack/local/serverless/Makefile
  hack/local/serverless/k3d-patches/patch-k3d-module-manager-clusterrole.yaml
  hack/local/serverless/k3d-patches/patch-kyma.yaml
  hack/verify_kyma_status.sh
Labels: lgtm, size/L
