Repository kyma-project/serverless, pull requests merged in 2023-11, with the labels that each got.

#379 Adjust go.mod, go.sum, Dockerfile, makefiles to new structure
  Makefile
  components/operator/.dockerignore
  components/operator/Dockerfile
  components/operator/go.mod
  components/operator/go.sum
  hack/ci/Makefile
  hack/common/Makefile
Labels: size/M, area/serverless, lgtm, kind/cleanup

#390 Remove additional make targets with `-operator` sufix
  Makefile
  hack/ci/Makefile
  hack/common/Makefile
Labels: size/M, lgtm, kind/cleanup

#391 Fix dependency code editor configuration
  config/serverless/templates/busola-serverless-extension.yaml
Labels: kind/bug, lgtm, size/XS, area/busola/ux

#392 add gcr and acr examples
  docs/user/00-20-configure-serverless.md
Labels: size/M, area/serverless, lgtm, area/documentation

#395 Fix formatting
  docs/user/00-20-configure-serverless.md
Labels: size/S, lgtm, area/documentation

#399 Copy hack folder to components/operator
  components/operator/hack/boilerplate.go.txt
  components/operator/hack/ci/Makefile
  components/operator/hack/common/Makefile
  components/operator/hack/common/k3d-patches/patch-k3d-lifecycle-manager-clusterrole.yaml
  components/operator/hack/common/verify_kyma_status.sh
  components/operator/hack/common/verify_serverless_status.sh
  components/operator/hack/get_kyma_file_name.sh
  components/operator/hack/local/Makefile
  components/operator/hack/makefile-strategy.md
  components/operator/hack/makefile-strategy.png
Labels: area/serverless, lgtm, size/L, kind/cleanup

#398 Rich Changelog generation
  .github/scripts/create_changelog.sh
  .github/workflows/create-release.yaml
Labels: size/M, lgtm, area/ci

#397 Delete secret mutation webhook
  components/serverless/cmd/webhook/main.go
  components/serverless/config/webhook/manifests.yaml
  components/serverless/internal/controllers/serverless/fsm_test.go
  components/serverless/internal/controllers/serverless/function_reconcile.go
  components/serverless/internal/webhook/remote_registry_cfg_webhook.go
  components/serverless/internal/webhook/remote_registry_cfg_webhook_test.go
  components/serverless/internal/webhook/resources/webhook_config.go
  config/serverless/charts/webhook/templates/webhooks.yaml
  config/serverless/values.yaml
Labels: area/serverless, lgtm, size/L, kind/deprecation

#402 Copy Makefile to components/operator
  components/operator/Makefile
Labels: area/serverless, lgtm, size/L, kind/cleanup

#403 Cleanup Makefiles
  Makefile
  components/operator/Makefile
  components/operator/hack/ci/Makefile
  components/operator/hack/common/Makefile
  hack/ci/Makefile
  hack/common/Makefile
  hack/common/k3d-patches/patch-k3d-lifecycle-manager-clusterrole.yaml
  hack/common/verify_kyma_status.sh
  hack/common/verify_serverless_status.sh
  hack/local/Makefile
  hack/makefile-strategy.md
  hack/makefile-strategy.png
Labels: area/serverless, lgtm, kind/cleanup, size/XL

#407 fix output path for rendered manifest
  components/operator/Makefile
Labels: area/serverless, lgtm, kind/failing-test

#406 Run runtimes builds
  components/runtimes/nodejs/nodejs16/Dockerfile
  components/runtimes/nodejs/nodejs18/Dockerfile
  components/runtimes/python39/Dockerfile
Labels: kind/feature, area/serverless, lgtm, size/XS

#405 Use latest tags in sec-scanners-config on main
  sec-scanners-config.yaml
Labels: kind/feature, area/security, size/S, lgtm

#409 fix test gardener-integration
  .github/workflows/gardener-integration.yaml
Labels: area/serverless, lgtm, size/XS, kind/failing-test, area/ci

#414 Don't use sec-scanners-config to build moduletemplate on pre/post submit
  components/operator/Makefile
  module-config-template.yaml
Labels: kind/feature, area/security, lgtm, size/XS

#415 Fix links found by Link Checker
  CODE_OF_CONDUCT.md
  README.md
  components/serverless/design/glossary_proposal.md
  config/serverless/charts/webhook/README.md
  docs/user/technical-reference/07-20-function-processing-stages.md
  docs/user/technical-reference/07-70-function-specification.md
  docs/user/tutorials/01-50-sync-function-with-gitops.md
  docs/user/tutorials/_sidebar.md
Labels: size/S, lgtm, area/documentation

#416 Use sec-scanners-config during the release
  .github/scripts/release.sh
  sec-scanners-config-local.yaml
Labels: kind/bug, area/security, lgtm, size/XS, area/ci

#413 Cleanup dashboard definitions
  config/serverless/templates/function-dashboard.yaml
  config/serverless/templates/function-metrics-dashboard.yaml
  config/serverless/values.yaml
Labels: area/serverless, lgtm, kind/cleanup, size/XXL

#421 Adjust path to Makefile in release.sh
  .github/scripts/release.sh
Labels: lgtm, size/XS, area/ci

#420 Only `serverless-registry-config-default` secret should be copied across namespaces
  components/serverless/internal/controllers/kubernetes/namespace_controller.go
  components/serverless/internal/controllers/kubernetes/namespace_controller_test.go
  components/serverless/internal/controllers/kubernetes/secret_service.go
  components/serverless/internal/controllers/kubernetes/secret_service_test.go
  components/serverless/internal/controllers/kubernetes/shared.go
  config/serverless/templates/deployment.yaml
  config/serverless/values.yaml
Labels: size/M, area/serverless, lgtm, kind/deprecation

#422 add configuration for golangci-lint
  components/operator/.golangci.yaml
  components/serverless/.golangci.yaml
Labels: size/S, lgtm, kind/cleanup, area/ci

#424 remove temporary dir module-chart-test and use tests/serverless instead
  components/operator/hack/ci/Makefile
Labels: lgtm, kind/cleanup, area/tests

#428 Bump golang to 1.21.4-alpine3.18
  components/operator/Dockerfile
  components/serverless/deploy/jobinit/Dockerfile
  components/serverless/deploy/manager/Dockerfile
  components/serverless/deploy/registry-gc/Dockerfile
  components/serverless/deploy/webhook/Dockerfile
  config/serverless/values.yaml
Labels: size/M, lgtm, kind/chore

#430 Dynamically exclude namespaces
  components/operator/internal/chart/flags.go
  components/operator/internal/chart/flags_test.go
  components/operator/internal/state/registry.go
  components/operator/internal/state/registry_test.go
  components/serverless/internal/controllers/kubernetes/shared.go
  components/serverless/internal/controllers/kubernetes/shared_test.go
Labels: kind/feature, size/M, lgtm

#431 Convert html tabs /toggles into docsify tags in the Serverless repo
  docs/user/00-50-limitations.md
  docs/user/technical-reference/07-10-sample-functions.md
  docs/user/technical-reference/07-70-function-specification.md
  docs/user/tutorials/01-10-create-inline-function.md
  docs/user/tutorials/01-100-customize-function-traces.md
  docs/user/tutorials/01-11-create-git-function.md
  docs/user/tutorials/01-110-override-runtime-image.md
  docs/user/tutorials/01-120-inject-envs.md
  docs/user/tutorials/01-130-use-external-scalers.md
  docs/user/tutorials/01-20-expose-function.md
  docs/user/tutorials/01-40-debug-function.md
  docs/user/tutorials/01-60-set-external-registry.md
  docs/user/tutorials/01-80-log-into-private-packages-registry.md
  docs/user/tutorials/01-90-set-asynchronous-connection.md
Labels: lgtm, size/L, area/documentation

#429 Add validation for build and function resoruces
  components/serverless/Makefile
  components/serverless/internal/controllers/serverless/function_reconcile.go
  components/serverless/internal/controllers/serverless/validation.go
  components/serverless/internal/controllers/serverless/validation_test.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_types.go
  config/serverless/values.yaml
Labels: lgtm, size/L

#436 Fix Eventing link in the Serverless documentation
  docs/user/README.md
Labels: lgtm, size/XS, area/documentation

#433 Controller validation
  components/serverless/Makefile
  components/serverless/internal/controllers/serverless/utils.go
  components/serverless/internal/controllers/serverless/validation.go
  components/serverless/internal/controllers/serverless/validation_test.go
  config/serverless/values.yaml
Labels: lgtm, size/L

#425 Cleanup `GitRepository` orphan resources
  components/operator/internal/gitrepository/cleanup.go
  components/operator/internal/gitrepository/cleanup_test.go
  components/operator/main.go
Labels: lgtm, size/L

#439 Prepare v1.2.0 release
  .version
  config/serverless/values.yaml
  sec-scanners-config.yaml
Labels: size/M, lgtm, kind/chore

#440 Bump Action to whitelisted Version
  .github/workflows/create-release.yaml
Labels: lgtm, size/XS, area/ci

#441 Bump Action to whitelisted Version (#440)
  .github/workflows/create-release.yaml
Labels: lgtm, size/XS, area/ci

#434 Cleanup makefile in serverless
  components/serverless/Makefile
Labels: lgtm, size/L

#445 Fix link to the APIRule CR documentation
  docs/user/README.md
Labels: lgtm, size/XS, area/documentation

#443 Format the `values.yaml` file
  config/serverless/values.yaml
Labels: size/M, area/serverless, lgtm, kind/cleanup

#444 Remove gitrepositories leftovers
  components/operator/controllers/serverless_controller_rbac.go
  components/serverless/config/crd/kustomization.yaml
  components/serverless/config/crd/patches/cainjection_in_gitrepositories.yaml
  components/serverless/config/rbac/gitrepository_editor_role.yaml
  components/serverless/config/rbac/gitrepository_viewer_role.yaml
  components/serverless/config/rbac/role.yaml
  components/serverless/internal/controllers/serverless/function_reconcile.go
  config/operator/rbac/role.yaml
Labels: size/M, area/serverless, lgtm, kind/cleanup

#450 Remove gitrepositories leftovers (#444)
  components/operator/controllers/serverless_controller_rbac.go
  components/serverless/config/crd/kustomization.yaml
  components/serverless/config/crd/patches/cainjection_in_gitrepositories.yaml
  components/serverless/config/rbac/gitrepository_editor_role.yaml
  components/serverless/config/rbac/gitrepository_viewer_role.yaml
  components/serverless/config/rbac/role.yaml
  components/serverless/internal/controllers/serverless/function_reconcile.go
  config/operator/rbac/role.yaml
Labels: size/M, lgtm, kind/cleanup

#448 add paths which should be checked for gardener integration test
  .github/workflows/gardener-integration.yaml
Labels: lgtm, size/XS, kind/failing-test, area/ci

#449 add paths which should be checked for gardener integration test
  .github/workflows/gardener-integration.yaml
Labels: lgtm, kind/failing-test, area/ci

#426 fix errors from serverless showed by linters
  components/serverless/.golangci.yaml
  components/serverless/internal/config/file_test.go
  components/serverless/internal/controllers/serverless/fsm_test.go
  components/serverless/internal/controllers/serverless/gitops_test.go
  components/serverless/internal/controllers/serverless/utils.go
  components/serverless/internal/file/notify_test.go
  components/serverless/internal/git/go2git.go
  config/serverless/values.yaml
Labels: size/M, area/serverless, lgtm, kind/failing-test

#452 Handle no GH actions to check in release flow
  .github/scripts/verify-actions-status.sh
Labels: kind/bug, size/S, lgtm, area/ci

#453 Handle no GH actions to check in release flow (#452)
  .github/scripts/verify-actions-status.sh
Labels: kind/bug, size/S, lgtm, area/ci

#454 Remove '-it' from docker run
  .github/workflows/create-release.yaml
Labels: lgtm, size/XS, area/ci

#455 Remove '-it' from docker run (#454)
  .github/workflows/create-release.yaml
Labels: lgtm, size/XS, area/ci

#456 Remove redundant unit test step from release flow
  .github/workflows/create-release.yaml
  .github/workflows/run-unit-tests.yaml
Labels: size/M, lgtm, area/ci

#457 Remove redundant unit test step from release flow
  .github/workflows/create-release.yaml
  .github/workflows/run-unit-tests.yaml
Labels: size/M, lgtm, area/ci

#459 Disable changelog generator
  .github/scripts/create_draft_release.sh
  .github/workflows/create-release.yaml
Labels: size/S, lgtm, area/ci

#462 Bump rc-tag
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore, cla: yes

#463 Bump tpi images used by serverless
  config/serverless/values.yaml
Labels: lgtm, size/XS, kind/chore, cla: yes

#464 Bump tpi images used by serverless 1.2
  .version
  config/serverless/values.yaml
  sec-scanners-config.yaml
Labels: size/S, lgtm, kind/chore, cla: yes

#466 Fix redundant kyma-system namespcace
  components/operator/hack/ci/Makefile
Labels: lgtm, size/XS, cla: yes

#451 Implementation of validation for resurce profile
  components/serverless/Makefile
  components/serverless/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/serverless/internal/controllers/serverless/function_reconcile_test.go
  components/serverless/internal/controllers/serverless/suite_test.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_types.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_x_validation_test.go
  config/serverless/templates/crds.yaml
  config/serverless/values.yaml
  tests/serverless/internal/assertion/cloud_events.go
  tests/serverless/internal/resources/runtimes/git_function.go
  tests/serverless/internal/resources/runtimes/nodejs.go
  tests/serverless/internal/resources/runtimes/python.go
Labels: lgtm, size/L, cla: yes

#468 K3d upgrade test wo lfm 1.2
  components/operator/hack/ci/Makefile
Labels: size/S, lgtm, area/ci, cla: yes

#470 bump rc tag
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore, cla: yes

#469 Validate envs in runtime
  components/serverless/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/serverless/internal/controllers/serverless/validation.go
  components/serverless/internal/controllers/serverless/validation_test.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_types.go
  config/serverless/templates/crds.yaml
  config/serverless/values.yaml
Labels: lgtm, size/L, cla: yes

#471 Simple validation
  components/serverless/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/serverless/pkg/apis/serverless/v1alpha2/function_types.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_x_validation_test.go
  config/serverless/templates/crds.yaml
  config/serverless/values.yaml
Labels: size/M, lgtm, cla: yes

#472 Remove the `moduletemplate.yaml` asset from release
  .github/scripts/release.sh
Labels: lgtm, size/XS, kind/cleanup, area/ci, cla: yes

#473 Remove the `moduletemplate.yaml` asset from release
  .github/scripts/release.sh
Labels: lgtm, size/XS, kind/cleanup, area/ci, cla: yes

#467 Use branch name instead of latest word
  sec-scanners-config.yaml
Labels: kind/feature, size/S, lgtm, area/ci, cla: yes
