Repository kyma-project/serverless, pull requests merged in 2023-08, with the labels that each got.

#166 Move the technical docs to serverless-manager
  docs/README.md
  docs/assets/svls-api-rules.drawio.svg
  docs/assets/svls-architecture.drawio.svg
  docs/assets/svls-built.drawio.svg
  docs/assets/svls-configured.drawio.svg
  docs/assets/svls-function-ui.png
  docs/assets/svls-internal-registry.drawio.svg
  docs/assets/svls-kyma-cli-functions.png
  docs/assets/svls-running.drawio.svg
  docs/configurability-of-serverless.md
  docs/contributor/configurability-of-serverless.md
  docs/contributor/manual-installation-on-k3d.md
  docs/user/00-01-tutorials.md
  docs/user/00-02-technical-reference.md
  docs/user/00-03-troubleshooting-guides.md
  docs/user/00-10-from-code-to-function.md
  docs/user/00-20-container-registries.md
  docs/user/00-30-development-toolkit.md
  docs/user/00-40-security-considerations.md
  docs/user/00-50-limitations.md
  docs/user/01-10-create-inline-function.md
  docs/user/01-100-customize-function-traces.md
  docs/user/01-11-create-git-function.md
  docs/user/01-110-override-runtime-image.md
  docs/user/01-120-inject-envs.md
  docs/user/01-130-use-external-scalers.md
  docs/user/01-140-use-secret-mounts.md
  docs/user/01-20-expose-function.md
  docs/user/01-30-manage-functions-with-kyma-cli.md
  docs/user/01-40-debug-function.md
  docs/user/01-50-sync-function-with-gitops.md
  docs/user/01-60-set-external-registry.md
  docs/user/01-80-log-into-private-packages-registry.md
  docs/user/01-90-set-asynchronous-connection.md
  docs/user/03-10-cannot-build-functions.md
  docs/user/03-20-failing-function-container.md
  docs/user/03-40-function-build-failing-k3d.md
  docs/user/03-50-serverless-periodically-restaring.md
  docs/user/03-70-switch-to-external-registry.md
  docs/user/04-10-architecture.md
  docs/user/04-20-internal-registry.md
  docs/user/05-20-env-variables.md
  docs/user/07-10-sample-functions.md
  docs/user/07-20-function-processing-stages.md
  docs/user/07-40-git-source-type.md
  docs/user/07-60-function-configuration-file.md
  docs/user/07-70-function-specification.md
  docs/user/07-80-available-presets.md
  docs/user/08-10-best-practices.md
  docs/user/README.md
  docs/user/_sidebar.md
  docs/user/resources/06-10-function-cr.md
Labels: area/serverless, lgtm, size/XXL, area/documentation

#177 Cleanup and document Serverless CR
  api/v1alpha1/serverless_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_serverlesses.yaml
  docs/serverless-CR.md
  docs/user/resources/06-20-serverless-cr.md
Labels: lgtm, size/L, kind/cleanup, area/documentation

#181 Improve serverless cr descriptions
  docs/user/resources/06-20-serverless-cr.md
Labels: lgtm, size/XS, area/documentation

#178 Automated release workflow for Serverless Operator
  .env
  .github/workflows/create-release.yaml
  .github/workflows/run-unit-tests.yaml
  .version
  CODEOWNERS
  Makefile
  config/operator/kustomization.yaml
  hack/ci/Makefile
  hack/common/Makefile
  scripts/check_image.sh
  scripts/check_release_tag.sh
  scripts/create_changelog.sh
  scripts/create_draft_release.sh
  scripts/publish_release.sh
  scripts/release.sh
  scripts/verify-serverless-status.sh
  sec-scanners-config-local.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/L, area/ci

#182 Bump .version before the release
  .version
Labels: lgtm, size/XS

#183 Fix variable name for GH Actions
  .github/workflows/create-release.yaml
Labels: lgtm, size/XS, area/ci

#184 Bump image before release
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#185 Renaming leftover in script
  scripts/release.sh
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#175 Dynamic tracing configuration
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/serverless_helpers.go
  controllers/serverless_controller.go
  controllers/serverless_controller_test.go
  controllers/testhelper_test.go
  go.mod
  go.sum
  internal/state/optional_dependencies.go
  internal/state/optional_dependencies_test.go
  internal/state/served_filter.go
  internal/state/serverless_utils.go
  internal/tracing/tracing.go
  internal/tracing/watcher.go
  main.go
Labels: lgtm, size/XL

#187 Bump version for release
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#188 Bumps for release
  scripts/release.sh
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#193 Include serverless workloads images in scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore

#190 Change all links to relative ones
  docs/assets/modular-serverless.svg
  docs/assets/svls-add-ssh-key.png
  docs/assets/svls-api-rules.svg
  docs/assets/svls-architecture.svg
  docs/assets/svls-built.svg
  docs/assets/svls-configured.svg
  docs/assets/svls-create-ssh-key.png
  docs/assets/svls-internal-registry.svg
  docs/assets/svls-running.svg
  docs/assets/svls-settings.png
  docs/user/00-01-tutorials.md
  docs/user/00-02-technical-reference.md
  docs/user/00-03-troubleshooting-guides.md
  docs/user/00-10-from-code-to-function.md
  docs/user/00-20-configure-serverless.md
  docs/user/00-40-security-considerations.md
  docs/user/00-50-limitations.md
  docs/user/08-10-best-practices.md
  docs/user/README.md
  docs/user/_sidebar.md
  docs/user/resources/README.md
  docs/user/resources/_sidebar.md
  docs/user/technical-reference/04-10-architecture.md
  docs/user/technical-reference/04-20-internal-registry.md
  docs/user/technical-reference/05-20-env-variables.md
  docs/user/technical-reference/07-10-sample-functions.md
  docs/user/technical-reference/07-20-function-processing-stages.md
  docs/user/technical-reference/07-40-git-source-type.md
  docs/user/technical-reference/07-60-function-configuration-file.md
  docs/user/technical-reference/07-70-function-specification.md
  docs/user/technical-reference/07-80-available-presets.md
  docs/user/technical-reference/README.md
  docs/user/technical-reference/_sidebar.md
  docs/user/troubleshooting-guides/03-10-cannot-build-functions.md
  docs/user/troubleshooting-guides/03-20-failing-function-container.md
  docs/user/troubleshooting-guides/03-40-function-build-failing-k3d.md
  docs/user/troubleshooting-guides/03-50-serverless-periodically-restaring.md
  docs/user/troubleshooting-guides/README.md
  docs/user/troubleshooting-guides/_sidebar.md
  docs/user/tutorials/01-10-create-inline-function.md
  docs/user/tutorials/01-100-customize-function-traces.md
  docs/user/tutorials/01-11-create-git-function.md
  docs/user/tutorials/01-110-override-runtime-image.md
  docs/user/tutorials/01-120-inject-envs.md
  docs/user/tutorials/01-130-use-external-scalers.md
  docs/user/tutorials/01-140-use-secret-mounts.md
  docs/user/tutorials/01-20-expose-function.md
  docs/user/tutorials/01-30-manage-functions-with-kyma-cli.md
  docs/user/tutorials/01-40-debug-function.md
  docs/user/tutorials/01-50-sync-function-with-gitops.md
  docs/user/tutorials/01-60-set-external-registry.md
  docs/user/tutorials/01-80-log-into-private-packages-registry.md
  docs/user/tutorials/01-90-set-asynchronous-connection.md
  docs/user/tutorials/README.md
  docs/user/tutorials/_sidebar.md
Labels: lgtm, size/L, area/documentation

#194 Bump golang runtime to 1.20.7
  Dockerfile
Labels: lgtm, size/XS, kind/chore

#195 Bump operator image
  sec-scanners-config.yaml
Labels: area/serverless, lgtm, size/XS, kind/chore

#196 Bump serverless-manager version (0.2.2)
  .version
Labels: lgtm, size/XS

#197 Adjust image name in release scripts
  scripts/check_image.sh
Labels: lgtm, size/XS

#198 Bump operator image
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#199 Fix Tracing & Eventing Endpoints Defaulting
  api/v1alpha1/serverless_helpers.go
  controllers/serverless_controller_test.go
  controllers/testhelper_test.go
  internal/state/optional_dependencies.go
  internal/state/optional_dependencies_test.go
Labels: size/S, lgtm

#201 speed up tests
  controllers/suite_test.go
Labels: size/S, lgtm

#200 Add template to release assets
  scripts/release.sh
Labels: size/S, lgtm

#202 Remove label
  hack/common/Makefile
Labels: lgtm, size/XS

#203 Release Bumps
  .version
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#204 Fix for release.sh
  scripts/release.sh
  sec-scanners-config.yaml
Labels: size/S, lgtm

#206 Change variable assignement
  scripts/release.sh
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#207 Release Script Fix
  scripts/release.sh
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#205 Adjust default PVC size to currently installed
  internal/chart/install.go
  internal/chart/pvc.go
  internal/chart/pvc_test.go
Labels: lgtm, size/L

#209 Unifying release assets names
  .gitignore
  Makefile
  README.md
  config/samples/default_serverless_cr.yaml
  config/samples/default_serverless_cr_k3d.yaml
  config/samples/default_serverless_cr_k3d_explicit.yaml
  config/ui-extensions/serverless/general
  docs/contributor/manual-installation-on-k3d.md
  hack/ci/Makefile
  hack/common/Makefile
  scripts/release.sh
Labels: size/M, area/serverless, lgtm, kind/cleanup, area/documentation

#192 expose aditional config into serverless cr
  api/v1alpha1/serverless_helpers.go
  api/v1alpha1/serverless_types.go
  config/crd/bases/operator.kyma-project.io_serverlesses.yaml
  controllers/serverless_controller_test.go
  controllers/testhelper_test.go
  internal/chart/flags.go
  internal/chart/flags_test.go
  internal/state/optional_dependencies.go
  internal/state/optional_dependencies_test.go
Labels: lgtm, size/L

#218 Adjust docs to exposing aditional config into serverless cr
  docs/user/00-20-configure-serverless.md
  docs/user/resources/06-20-serverless-cr.md
Labels: lgtm, size/L, area/documentation

#222 Propagate default presets to webhook overrides
  config/ui-extensions/serverless/details
  internal/chart/flags.go
  internal/state/optional_dependencies.go
Labels: size/M, lgtm

#228 Bump serverelss operator version
  .version
  config/operator/kustomization.yaml
Labels: lgtm, size/XS, kind/chore

#229 Bump image versions in sec config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore

#225 cleanup the README file
  README.md
  docs/contributor/01-10-manual-installation-on-k3d.md
  docs/contributor/03-10-scripts-not-working.md
  docs/contributor/04-10-testing-strategy.md
Labels: size/M, lgtm, area/documentation

#231 Bump serverelss operator version v0.3.1
  .version
  config/operator/kustomization.yaml
Labels: lgtm, size/XS, kind/chore

#230 Added Error Handling
  internal/chart/install.go
Labels: area/serverless, lgtm, size/XS, kind/cleanup

#234 Bump image versions in sec config (0.3.1)
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore

#233 check if data from cache was loaded
  internal/chart/verify.go
  internal/chart/verify_test.go
  internal/state/state_test.go
Labels: kind/bug, area/serverless, size/S, lgtm

#237 Provide better sample custom trace collector endpoint
  docs/user/00-20-configure-serverless.md
Labels: kind/bug, documentation, lgtm, size/XS

#240 Improve the requireEqualFunc implementation
  internal/state/state_test.go
Labels: size/M, lgtm

#243 Update Security scanner exclusions
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#242 Add check if serverless images use PR tags
  .github/workflows/create-release.yaml
  scripts/verify-serverless-manifest-images.sh
Labels: size/M, lgtm, area/ci

#238 add descriptions to severless cr spec
  api/v1alpha1/serverless_types.go
  docs/user/resources/06-20-serverless-cr.md
Labels: size/M, lgtm, area/documentation

#223 Gardener integration test
  .github/workflows/gardener-integration.yaml
  hack/ci/Makefile
  hack/common/Makefile
Labels: size/M, lgtm, area/ci

#245 Fix `gerdener-integration-test` action
  .github/workflows/gardener-integration.yaml
  hack/common/Makefile
Labels: kind/bug, lgtm, size/XS, area/ci
