Repository kyma-project/serverless, pull requests merged in 2023-09, with the labels that each got.

#246 Block release on action fail
  .github/workflows/create-release.yaml
  scripts/check_image.sh
  scripts/create_changelog.sh
  scripts/verify-actions-status.sh
  scripts/verify-serverless-manifest-images.sh
  scripts/verify-serverless-status.sh
Labels: size/M, lgtm, area/ci

#255 Get rid of main in release runs
  .github/workflows/create-release.yaml
Labels: size/S, lgtm, area/ci

#257 Allow running gardener test manually
  .github/workflows/gardener-integration.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, area/ci

#258 Set Warning state when orphaned functions found at deletion
  internal/state/delete.go
  internal/state/delete_test.go
Labels: kind/bug, lgtm, size/XS

#260 Bump versions in security config
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#261 Release v1.0.0
  .version
  config/operator/kustomization.yaml
Labels: lgtm, size/XS, kind/chore

#262 Bump operator image in security config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore

#263 Update 04-10-testing-strategy.md
  docs/contributor/04-10-testing-strategy.md
Labels: documentation, lgtm, size/XS, area/documentation

#266 Adjust serverless overrides paths
  internal/chart/flags.go
  internal/state/optional_dependencies_test.go
Labels: size/M, area/serverless, lgtm

#265 add removing orphaned config maps and secrets
  internal/chart/uninstall.go
  internal/chart/uninstall_test.go
  internal/state/delete.go
  internal/state/delete_test.go
Labels: area/serverless, lgtm, size/L

#267 Release v1.0.1
  .version
  config/operator/kustomization.yaml
Labels: lgtm, size/XS, kind/chore

#268 Bump operator image in security config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore

#271 Drop leader election capabilities - no HA use case
  config/operator/operator.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  internal/chart/uninstall.go
  internal/chart/uninstall_test.go
  internal/state/delete_test.go
  main.go
Labels: lgtm, size/L, kind/cleanup

#273 Use latest available k8s version in gardener test
  hack/common/Makefile
Labels: lgtm, size/XS, area/ci

#276 Release 1.0
  hack/clone_dir_from_github.sh
  internal/chart/flags.go
  internal/state/optional_dependencies_test.go
Labels: size/M, lgtm

#277 release v1.0.2
  .version
  config/operator/kustomization.yaml
  sec-scanners-config.yaml
Labels: size/S, lgtm

#279 bump-operator-img-release v1.0.2
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore

#280 Run gardener integration action on every release branch
  .github/workflows/gardener-integration.yaml
Labels: lgtm, size/XS, area/ci

#281 Fix branch for verification images
  scripts/verify-serverless-manifest-images.sh
Labels: lgtm, size/XS

#282 bump-operator-img-release v1.0.2
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore

#283 bump-operator-img-release v1.0.2
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#284 Revert "bump-operator-img-release v1.0.2 (#282)"
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#285 Bump image
  .github/workflows/gardener-integration.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, area/ci

#244 Implement module-config template
  .gitignore
  Makefile
  module-config-template.yaml
Labels: size/M, lgtm

#290 bump next version v1.1.0
  .version
  config/operator/kustomization.yaml
Labels: lgtm, size/XS, kind/chore

#292 Match module name in sec config file-v1.0
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore

#293 bump version v1.0.3
  .version
  config/operator/kustomization.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore

#294 Match module name
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore

#272 Move status update strategy to the FSM
  internal/state/apply.go
  internal/state/apply_test.go
  internal/state/delete.go
  internal/state/delete_test.go
  internal/state/emit_event.go
  internal/state/fsm.go
  internal/state/fsm_test.go
  internal/state/initialize.go
  internal/state/initialize_test.go
  internal/state/optional_dependencies.go
  internal/state/optional_dependencies_test.go
  internal/state/registry.go
  internal/state/registry_test.go
  internal/state/remove_finalizer.go
  internal/state/remove_finalizer_test.go
  internal/state/served_filter.go
  internal/state/served_filter_test.go
  internal/state/update_status.go
  internal/state/verify.go
  internal/state/verify_test.go
  main.go
Labels: kind/feature, area/serverless, lgtm, size/L

#286 Refactor save snapshot
  internal/state/emit_event.go
  internal/state/emit_event_test.go
  internal/state/fsm.go
  internal/state/fsm_test.go
  internal/state/optional_dependencies_test.go
  internal/state/registry_test.go
  internal/state/update_status.go
Labels: size/M, area/serverless, lgtm, kind/cleanup

#287 Use requeueAfter secret are deleted
  internal/state/delete.go
Labels: area/serverless, lgtm, size/XS, kind/cleanup

#291 Rename the `stopWithError` func
  internal/state/apply.go
  internal/state/delete.go
  internal/state/registry.go
  internal/state/remove_finalizer.go
  internal/state/served_filter.go
  internal/state/state.go
  internal/state/verify.go
Labels: area/serverless, size/S, lgtm, kind/cleanup

#296 rename stopWithPossibleError
  internal/state/apply.go
  internal/state/delete.go
  internal/state/registry.go
  internal/state/remove_finalizer.go
  internal/state/served_filter.go
  internal/state/state.go
  internal/state/verify.go
Labels: area/serverless, lgtm, kind/cleanup

#295 refactor sFnServedFilter
  internal/state/served_filter.go
Labels: size/M, area/serverless, lgtm, kind/cleanup

#298 Fix flags
  internal/chart/flags.go
Labels: size/M, lgtm

#302 Adjust .gitignore for nodejs and java runtimes
  components/runtimes/java17/.gitignore
  components/runtimes/java17/Dockerfile-jvm-function-local
  components/runtimes/nodejs/.gitignore
  components/runtimes/nodejs/nodejs16/package.json
  components/runtimes/nodejs/nodejs18/package.json
Labels: kind/feature, size/M, area/serverless, lgtm

#297 refactor state function sFnInitialize
  internal/state/add_finalizer.go
  internal/state/add_finalizer_test.go
  internal/state/initialize.go
  internal/state/initialize_test.go
  internal/state/served_filter.go
  internal/state/served_filter_test.go
  internal/state/state_test.go
  internal/state/verify_test.go
Labels: area/serverless, lgtm, size/L, kind/cleanup

#303 Include docu link and repo url in module-config template
  module-config-template.yaml
Labels: lgtm, size/XS

#304 Improve optional dependencies state function
  api/v1alpha1/serverless_types.go
  internal/state/optional_dependencies.go
  internal/state/optional_dependencies_test.go
  internal/state/state_test.go
Labels: area/serverless, lgtm, size/L, kind/cleanup

#305 temporarily exclude serverless directories from controller-gen scope
  Makefile
Labels: area/serverless, lgtm, size/XS, kind/cleanup

#301 Provide more details in the Git Function tutorial
  docs/user/tutorials/01-10-create-inline-function.md
  docs/user/tutorials/01-11-create-git-function.md
  docs/user/tutorials/01-20-expose-function.md
Labels: documentation, size/M, area/serverless, lgtm, area/documentation

#307 State tests cleanup
  internal/state/add_finalizer_test.go
  internal/state/apply_test.go
  internal/state/delete_test.go
  internal/state/emit_event_test.go
  internal/state/fsm_test.go
  internal/state/initialize_test.go
  internal/state/optional_dependencies_test.go
  internal/state/registry_test.go
  internal/state/remove_finalizer_test.go
  internal/state/served_filter_test.go
  internal/state/verify_test.go
Labels: area/serverless, lgtm, kind/cleanup

#311 Add darwin arm64 to script
  hack/get_kyma_file_name.sh
Labels: lgtm, size/XS

#217 reuse compliance
  .reuse/dep5
  LICENSES/Apache-2.0.txt
  README.md
Labels: lgtm, size/L

#312 Improve building flags mechanism
  go.mod
  internal/chart/chart.go
  internal/chart/chart_test.go
  internal/chart/flags.go
  internal/chart/flags_test.go
  internal/chart/install.go
  internal/chart/install_test.go
  internal/state/apply.go
  internal/state/apply_test.go
  internal/state/fsm.go
  internal/state/optional_dependencies.go
  internal/state/optional_dependencies_test.go
  internal/state/registry.go
  internal/state/registry_test.go
  internal/state/state_test.go
Labels: area/serverless, lgtm, kind/cleanup, size/XL
