Repository kyma-project/serverless, pull requests merged in 2023-12, with the labels that each got.

#476 remove env validation from webhook
  components/serverless/pkg/apis/serverless/v1alpha2/function_validation.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_validation_test.go
  config/serverless/values.yaml
Labels: kind/feature, size/M, area/serverless, lgtm, cla: yes

#477 Remove the `.version` file
  .github/scripts/check_release_tag.sh
  .github/workflows/create-release.yaml
  .github/workflows/gardener-integration.yaml
  .version
  components/operator/Makefile
  components/operator/hack/ci/Makefile
  components/operator/hack/common/Makefile
  config/operator/operator/kustomization.yaml
Labels: size/M, lgtm, kind/cleanup, area/ci, cla: yes

#478 remove resources validation from webhook
  components/serverless/pkg/apis/serverless/v1alpha2/function_validation.go
  config/serverless/values.yaml
Labels: kind/feature, size/M, area/serverless, lgtm, cla: yes

#481 Remove templates from function's api
  components/serverless/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/serverless/internal/controllers/serverless/system_state.go
  components/serverless/internal/controllers/serverless/system_state_test.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_types.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_validation.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_validation_test.go
  config/serverless/templates/crds.yaml
  config/serverless/values.yaml
  docs/user/resources/06-10-function-cr.md
Labels: kind/feature, area/serverless, lgtm, size/L, area/documentation, cla: yes

#483 remove runtime validation from webhook
  components/serverless/pkg/apis/serverless/v1alpha2/function_validation.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_validation_test.go
  config/serverless/values.yaml
Labels: kind/feature, size/M, area/serverless, lgtm, cla: yes

#487 Release test
  .github/workflows/create-release.yaml
  config/serverless/values.yaml
  sec-scanners-config.yaml
Labels: size/M, lgtm, area/ci, cla: yes

#489 Release test
  sec-scanners-config.yaml
Labels: size/S, lgtm, area/ci, cla: yes

#495 Move asset generation and verification to a Github Step (Propagating changes to main branch)
  .github/scripts/create_changelog.sh
  .github/scripts/release.sh
  .github/scripts/verify-serverless-jobs-status.sh
  .github/workflows/create-release.yaml
Labels: kind/feature, size/M, lgtm, area/ci, cla: yes

#493 Validate secret mounts to controller
  components/serverless/internal/controllers/serverless/validation.go
  components/serverless/internal/controllers/serverless/validation_test.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_validation.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_validation_test.go
  config/serverless/values.yaml
Labels: kind/feature, area/serverless, lgtm, size/L, cla: yes

#498 move source validation from webhook to x-kubernetes-validations
  components/serverless/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/serverless/pkg/apis/serverless/v1alpha2/function_types.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_validation.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_x_validation_test.go
  config/serverless/templates/crds.yaml
  config/serverless/values.yaml
Labels: kind/feature, area/serverless, lgtm, size/L, cla: yes

#497 Cleanup the registry garbage collector from serverless resources
  config/serverless/charts/docker-registry/templates/cronjob.yaml
  config/serverless/charts/docker-registry/templates/deployment.yaml
  config/serverless/charts/docker-registry/templates/rbac.yaml
  config/serverless/charts/docker-registry/values.yaml
  config/serverless/values.yaml
Labels: area/serverless, lgtm, size/L, kind/cleanup, cla: yes

#500 fix warning reported by linter
  components/serverless/internal/controllers/serverless/validation.go
  config/serverless/values.yaml
Labels: area/serverless, size/S, lgtm, kind/failing-test, cla: yes

#499 Adjust Serverless to new guidelines
  README.md
  components/serverless/README.md
  docs/contributor/03-10-scripts-not-working.md
  docs/user/00-10-from-code-to-function.md
  docs/user/00-20-configure-serverless.md
  docs/user/00-30-development-toolkit.md
  docs/user/00-40-security-considerations.md
  docs/user/00-50-limitations.md
  docs/user/08-10-best-practices.md
  docs/user/_sidebar.md
  docs/user/resources/06-10-function-cr.md
  docs/user/resources/06-20-serverless-cr.md
  docs/user/technical-reference/04-10-architecture.md
  docs/user/technical-reference/04-20-internal-registry.md
  docs/user/technical-reference/05-20-env-variables.md
  docs/user/technical-reference/07-20-function-processing-stages.md
  docs/user/technical-reference/07-40-git-source-type.md
  docs/user/technical-reference/07-60-function-configuration-file.md
  docs/user/technical-reference/07-70-function-specification.md
  docs/user/technical-reference/07-80-available-presets.md
  docs/user/technical-reference/README.md
  docs/user/troubleshooting-guides/03-10-cannot-build-functions.md
  docs/user/troubleshooting-guides/03-20-failing-function-container.md
  docs/user/troubleshooting-guides/03-40-function-build-failing-k3d.md
  docs/user/troubleshooting-guides/03-50-serverless-periodically-restaring.md
  docs/user/tutorials/01-10-create-inline-function.md
  docs/user/tutorials/01-100-customize-function-traces.md
  docs/user/tutorials/01-11-create-git-function.md
  docs/user/tutorials/01-110-override-runtime-image.md
  docs/user/tutorials/01-120-inject-envs.md
  docs/user/tutorials/01-130-use-external-scalers.md
  docs/user/tutorials/01-140-use-secret-mounts.md
  docs/user/tutorials/01-20-expose-function.md
  docs/user/tutorials/01-50-sync-function-with-gitops.md
  docs/user/tutorials/01-60-set-external-registry.md
  docs/user/tutorials/01-80-log-into-private-packages-registry.md
  docs/user/tutorials/01-90-set-asynchronous-connection.md
  tests/serverless/README.md
Labels: lgtm, size/L, area/documentation, cla: yes

#494 Replace k8s-tools with basic kubectl image
  config/serverless/charts/webhook/templates/deployment.yaml
  config/serverless/values.yaml
Labels: size/S, lgtm, kind/chore, cla: yes

#502 move validation of inline source dependencies
  components/serverless/internal/controllers/serverless/validation.go
  components/serverless/internal/controllers/serverless/validation_test.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_validation.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_validation_test.go
  config/serverless/values.yaml
Labels: kind/feature, area/serverless, lgtm, size/L, cla: yes

#507 Use same tpi images in sec-scanners-config and values
  sec-scanners-config.yaml
Labels: area/security, lgtm, size/XS, kind/cleanup, cla: yes

#504 Validate labels and annotations to controller
  components/serverless/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/serverless/internal/controllers/serverless/fsm.go
  components/serverless/internal/controllers/serverless/validation.go
  components/serverless/internal/controllers/serverless/validation_test.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_types.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_validation.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_validation_test.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_x_validation_test.go
  config/serverless/templates/crds.yaml
  config/serverless/values.yaml
Labels: kind/feature, area/serverless, lgtm, size/L, cla: yes

#509 remove checking function type in webhook
  components/serverless/internal/webhook/validating_webhook_test.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_validation.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_validation_test.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_x_validation_test.go
  config/serverless/values.yaml
Labels: kind/feature, size/M, area/serverless, lgtm, cla: yes

#511 Release values autobump
  .github/scripts/upgrade-sec-scanners-config.sh
  .github/workflows/create-release.yaml
Labels: kind/feature, size/M, lgtm, area/ci, cla: yes

#516 Removed unnecessary steps from release flow
  .github/scripts/check_image.sh
  .github/scripts/verify-serverless-manifest-images.sh
  .github/workflows/create-release.yaml
  components/operator/hack/ci/Makefile
Labels: size/M, lgtm, kind/cleanup, area/ci, cla: yes

#513 Block PR is developer changed main tag
  .github/scripts/verify-image-changes.sh
  .github/workflows/pr-verify-main-images.yaml
Labels: size/M, lgtm, kind/missing-test, area/ci, cla: yes

#517 Remove job requirement from verify-head-status
  .github/workflows/create-release.yaml
Labels: kind/bug, lgtm, size/XS, area/ci, cla: yes

#518 Fix release job and change script
  .github/scripts/upgrade-sec-scanners-config.sh
  .github/workflows/create-release.yaml
Labels: kind/bug, lgtm, size/XS, area/ci, cla: yes

#520 Fix release checkout
  .github/workflows/create-release.yaml
Labels: kind/bug, lgtm, size/XS, area/ci, cla: yes

#521 Add missing IMG env to the `release.sh` file
  .github/scripts/release.sh
  .github/workflows/create-release.yaml
Labels: kind/bug, size/S, lgtm, area/ci, cla: yes

#514 move baseDir and reference validations to x-kubernetes-validations
  components/serverless/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/serverless/internal/webhook/validating_webhook_test.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_types.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_validation.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_validation_test.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_x_validation_test.go
  components/serverless/pkg/apis/serverless/v1alpha2/validation_helpers.go
  config/serverless/templates/crds.yaml
Labels: kind/feature, area/serverless, lgtm, size/L, cla: yes

#522 Increase release verify timeouts
  .github/scripts/verify-serverless-jobs-status.sh
  .github/workflows/create-release.yaml
Labels: kind/bug, size/S, lgtm, area/ci, cla: yes

#523 Create dev and release dockerfiles for operator
  README.md
  components/operator/Dockerfile.dev
  components/operator/Dockerfile.release
  components/operator/Makefile
  components/operator/hack/ci/Makefile
  components/operator/hack/common/Makefile
  components/operator/hack/local/Makefile
Labels: kind/feature, size/M, lgtm, area/ci, cla: yes

#525 Use query params in hello world sample
  config/serverless/templates/busola-serverless-extension.yaml
Labels: size/M, lgtm, cla: yes

#526 Automatically swap images for local development
  components/operator/Dockerfile.dev
  components/operator/hack/ci/Makefile
  components/operator/hack/common/Makefile
  components/operator/hack/local/Makefile
  components/operator/hack/local/build_local_images.sh
  docker-compose.yaml
Labels: kind/feature, area/serverless, lgtm, size/L, cla: yes

#515 remove object meta validation from webhook
  components/serverless/pkg/apis/serverless/v1alpha2/function_validation.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_validation_test.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_x_validation_test.go
Labels: kind/feature, size/M, area/serverless, lgtm, cla: yes
