Repository kyma-project/serverless, pull requests merged in 2023-06, with the labels that each got.

#112 Fix release name
  internal/state/fsm.go
Labels: lgtm, size/XS

#111 Remove istio prerequisite check from reconciliation logic
  Makefile
  README.md
  config/rbac/role.yaml
  config/samples/operator_v1alpha1_serverless.yaml
  controllers/serverless_controller_rbac.go
  docs/assets/modular-serverless.drawio.svg
  docs/configurability-of-serverless.md
  hack/common/Makefile
  internal/chart/flags.go
  internal/chart/flags_test.go
  internal/dependencies/prerequisites.go
  internal/dependencies/prerequisites_test.go
  internal/state/initialize.go
  internal/state/initialize_test.go
  internal/state/prerequisites.go
  internal/state/prerequisites_test.go
Labels: kind/feature, lgtm, size/L, area/documentation

#114 Fix finalizer deletion
  hack/ci/Makefile
  internal/state/delete.go
  internal/state/delete_test.go
  internal/state/remove_finalizer.go
  internal/state/remove_finalizer_test.go
Labels: size/M, lgtm

#119 Bump version to 0.0.4
  .env
  config/manager/kustomization.yaml
Labels: lgtm, size/XS, kind/chore

#123 Fix orphan check
  hack/local/Makefile
  internal/chart/check.go
  internal/chart/check_test.go
Labels: size/M, lgtm

#122 Implement secret cache
  config/manager/manager.yaml
  controllers/serverless_controller.go
  internal/chart/cache.go
  internal/chart/cache_test.go
  internal/chart/chart.go
  internal/chart/check_test.go
  internal/chart/install_test.go
  internal/chart/uninstall.go
  internal/chart/uninstall_test.go
  internal/chart/verify_test.go
  internal/state/apply_test.go
  internal/state/delete_test.go
  internal/state/fsm.go
  internal/state/fsm_test.go
  internal/state/new.go
  internal/state/state_test.go
  internal/state/verify_test.go
Labels: lgtm, size/XL

#125 Generalize api
  api/v1alpha1/serverless_helpers.go
  api/v1alpha1/serverless_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_serverlesses.yaml
  controllers/serverless_controller_test.go
  controllers/testhelper_test.go
  internal/state/optional_dependencies.go
  internal/state/optional_dependencies_test.go
  internal/state/state_test.go
Labels: lgtm, size/L

#126 Reimplement cache strategy
  internal/chart/cache.go
  internal/chart/cache_test.go
  internal/chart/chart.go
  internal/chart/check.go
  internal/chart/install.go
  internal/chart/uninstall.go
  internal/chart/verify.go
  internal/state/apply_test.go
  internal/state/delete_test.go
  internal/state/state_test.go
  internal/state/verify_test.go
Labels: size/M, lgtm

#127 Small improvements
  api/v1alpha1/serverless_types.go
  config/crd/bases/operator.kyma-project.io_serverlesses.yaml
  controllers/serverless_controller_test.go
  internal/state/state_test.go
Labels: lgtm, size/XS

#129 Group cache interface arguments
  internal/chart/cache.go
  internal/chart/cache_test.go
  internal/chart/chart.go
  internal/chart/check.go
  internal/chart/check_test.go
  internal/chart/install.go
  internal/chart/install_test.go
  internal/chart/uninstall.go
  internal/chart/uninstall_test.go
  internal/chart/verify.go
  internal/chart/verify_test.go
  internal/state/state_test.go
  internal/state/verify_test.go
Labels: lgtm, size/L, kind/cleanup

#130 Regenerate manifest when manager is changed
  config/manager/manager.yaml
  internal/chart/cache.go
  internal/chart/chart.go
  internal/chart/chart_test.go
  internal/chart/install.go
  internal/state/fsm.go
  internal/state/new.go
Labels: lgtm, size/L, kind/cleanup

#128 fix deletion after error
  internal/state/fsm.go
  internal/state/initialize.go
Labels: size/M, lgtm, kind/cleanup

#131 remove unused resource
  internal/chart/chart.go
  internal/chart/chart_test.go
  internal/chart/install.go
  internal/chart/install_test.go
  internal/chart/uninstall.go
Labels: area/serverless, lgtm, size/L

#135 Bump manager version before release
  .env
  config/manager/kustomization.yaml
Labels: lgtm, size/XS

#132 Detect custom external docker registry
  api/v1alpha1/serverless_types.go
  config/crd/bases/operator.kyma-project.io_serverlesses.yaml
  internal/registry/secret.go
  internal/registry/secret_test.go
  internal/state/update_status.go
  internal/state/verify.go
  internal/state/verify_test.go
Labels: kind/feature, lgtm, size/L

#140 Registry configuration status
  api/v1alpha1/serverless_types.go
  config/crd/bases/operator.kyma-project.io_serverlesses.yaml
  controllers/serverless_controller_test.go
  internal/chart/flags.go
  internal/chart/flags_test.go
  internal/state/fsm.go
  internal/state/initialize.go
  internal/state/initialize_test.go
  internal/state/registry.go
  internal/state/registry_test.go
  internal/state/update_status.go
  internal/state/verify.go
Labels: lgtm, size/XL
