Repository kyma-project/serverless, pull requests merged in 2023-10, with the labels that each got.

#314 Split optional dependencies state
  internal/state/controller_configuration.go
  internal/state/controller_configuration_test.go
  internal/state/optional_dependencies.go
  internal/state/optional_dependencies_test.go
  internal/state/registry.go
  internal/state/registry_test.go
  internal/state/state.go
Labels: area/serverless, lgtm, size/L, kind/cleanup

#319 Unify fqdn for serverless module
  Makefile
  docs/contributor/01-10-manual-installation-on-k3d.md
Labels: lgtm, size/XS, kind/cleanup, area/documentation

#317 Make loggers more consistent
  main.go
Labels: area/serverless, lgtm, size/XS, kind/cleanup

#318 Remove unnecessary ifs from the `delete.go` file
  internal/state/delete.go
Labels: area/serverless, size/S, lgtm, kind/cleanup

#313 Get rid of setup
  api/v1alpha1/serverless_helpers.go
  internal/state/fsm.go
  internal/state/initialize.go
  internal/state/registry.go
  internal/state/update_status.go
Labels: size/M, lgtm

#320 Change workflow to match Sec_scanner_config with new release version
  .github/workflows/create-release.yaml
  scripts/check_image.sh
Labels: size/S, lgtm, area/ci

#323 sync serverless from kyma sources
  components/serverless/README.md
  components/serverless/hack/libgit.tgz
  config/serverless/values.yaml
Labels: size/M, area/serverless, lgtm, kind/cleanup

#325 Update git server used in tests
  tests/function-controller/internal/config.go
  tests/gitserver/Dockerfile
Labels: area/serverless, lgtm, size/XS, kind/cleanup

#326 Use post gitserver image
  tests/function-controller/internal/config.go
Labels: lgtm, size/XS

#337 Prepare v1.1.0 release
  .reuse/dep5
  Dockerfile
  sec-scanners-config.yaml
Labels: size/S, lgtm

#339 Assume no v prefix
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#324 Remove makefile targets for kyma sources
  Makefile
  hack/ci/Makefile
  hack/clone_dir_from_github.sh
  hack/common/Makefile
  hack/generate_module-chart.sh
Labels: kind/feature, area/serverless, lgtm, size/L

#341 Adjust make manifest to work in serverless-manager
  components/serverless/Makefile
Labels: size/S, lgtm

#342 Copy serverless-bench tests from kyma to serverless-manager
  tests/serverless-bench/Dockerfile
  tests/serverless-bench/Makefile
  tests/serverless-bench/README.md
  tests/serverless-bench/fixtures/functions/nodejs16-l.yaml
  tests/serverless-bench/fixtures/functions/nodejs16-m.yaml
  tests/serverless-bench/fixtures/functions/nodejs16-s.yaml
  tests/serverless-bench/fixtures/functions/nodejs16-xl.yaml
  tests/serverless-bench/fixtures/functions/nodejs16-xs.yaml
  tests/serverless-bench/fixtures/functions/nodejs18-l.yaml
  tests/serverless-bench/fixtures/functions/nodejs18-m.yaml
  tests/serverless-bench/fixtures/functions/nodejs18-s.yaml
  tests/serverless-bench/fixtures/functions/nodejs18-xl.yaml
  tests/serverless-bench/fixtures/functions/nodejs18-xs.yaml
  tests/serverless-bench/fixtures/functions/python39-l.yaml
  tests/serverless-bench/fixtures/functions/python39-m.yaml
  tests/serverless-bench/fixtures/functions/python39-s.yaml
  tests/serverless-bench/fixtures/functions/python39-xl.yaml
  tests/serverless-bench/fixtures/local-test/grafana-datasource.yaml
  tests/serverless-bench/fixtures/local-test/local-mysql.yaml
  tests/serverless-bench/fixtures/local-test/serverless-bench-grafana-dashboard.yaml
  tests/serverless-bench/fixtures/serverless-benchmark-job.yaml
  tests/serverless-bench/locust.py
  tests/serverless-bench/requirements.txt
  tests/serverless-bench/run-benchmarks.sh
Labels: lgtm, size/XXL

#340 Rename test dir to serverless
  hack/ci/Makefile
  tests/serverless/.gitignore
  tests/serverless/Makefile
  tests/serverless/README.md
  tests/serverless/cmd/main.go
  tests/serverless/go.mod
  tests/serverless/go.sum
  tests/serverless/internal/assertion/check.go
  tests/serverless/internal/assertion/check_test.go
  tests/serverless/internal/assertion/cloud_events.go
  tests/serverless/internal/config.go
  tests/serverless/internal/executor/cli.go
  tests/serverless/internal/executor/consts.go
  tests/serverless/internal/executor/fixtures_test.go
  tests/serverless/internal/executor/parallel.go
  tests/serverless/internal/executor/parallel_test.go
  tests/serverless/internal/executor/retry.go
  tests/serverless/internal/executor/runner.go
  tests/serverless/internal/executor/serial.go
  tests/serverless/internal/executor/serial_test.go
  tests/serverless/internal/executor/step.go
  tests/serverless/internal/resources/app/app.go
  tests/serverless/internal/resources/app/deployment.go
  tests/serverless/internal/resources/app/service.go
  tests/serverless/internal/resources/configmap/configmap.go
  tests/serverless/internal/resources/configmap/step.go
  tests/serverless/internal/resources/function/function.go
  tests/serverless/internal/resources/function/steps.go
  tests/serverless/internal/resources/git/client.go
  tests/serverless/internal/resources/git/commitchanges.go
  tests/serverless/internal/resources/git/git_cfg.go
  tests/serverless/internal/resources/git/gitserver.go
  tests/serverless/internal/resources/git/step.go
  tests/serverless/internal/resources/namespace/namespace.go
  tests/serverless/internal/resources/namespace/step.go
  tests/serverless/internal/resources/resource.go
  tests/serverless/internal/resources/runtimes/git_function.go
  tests/serverless/internal/resources/runtimes/nodejs.go
  tests/serverless/internal/resources/runtimes/python.go
  tests/serverless/internal/resources/secret/secret.go
  tests/serverless/internal/resources/secret/step.go
  tests/serverless/internal/testsuite/api_gateway.go
  tests/serverless/internal/testsuite/cloud_events.go
  tests/serverless/internal/testsuite/gitauth.go
  tests/serverless/internal/testsuite/gitops.go
  tests/serverless/internal/testsuite/light_runtimes.go
  tests/serverless/internal/testsuite/tracing.go
  tests/serverless/internal/utils/container.go
  tests/serverless/internal/utils/poller.go
  tests/serverless/internal/utils/pretty.go
  tests/serverless/internal/utils/retry.go
  tests/serverless/internal/utils/url.go
  tests/serverless/run-local.sh
Labels: lgtm, size/XS

#343 remove makefile target run-without-lifecycle-manager-operator
  hack/ci/Makefile
Labels: area/serverless, lgtm, size/XS, kind/cleanup

#348 Fix function default preset
  components/serverless/internal/controllers/serverless/build_resources_test.go
  components/serverless/internal/controllers/serverless/config.go
  components/serverless/internal/controllers/serverless/system_state.go
  config/serverless/values.yaml
Labels: size/M, lgtm

#352 Bump serverless images before v1.1.0 release
  config/serverless/values.yaml
  sec-scanners-config.yaml
Labels: size/M, area/serverless, lgtm, kind/chore

#358 fix released images verification
  scripts/verify-serverless-manifest-images.sh
Labels: area/serverless, lgtm, size/XS, kind/chore

#354 add more release logs
  scripts/release.sh
Labels: area/serverless, size/S, lgtm, kind/cleanup

#360 No v prefix for release tags
  scripts/check_release_tag.sh
Labels: kind/bug, lgtm, size/XS, area/ci

#357 Move github actions scripts to .github/scripts
  .github/scripts/check_image.sh
  .github/scripts/check_release_tag.sh
  .github/scripts/create_changelog.sh
  .github/scripts/create_draft_release.sh
  .github/scripts/publish_release.sh
  .github/scripts/release.sh
  .github/scripts/verify-actions-status.sh
  .github/scripts/verify-serverless-manifest-images.sh
  .github/scripts/verify-serverless-status.sh
  .github/workflows/create-release.yaml
Labels: size/S, lgtm, area/ci

#353 Improve flag builder impl
  internal/chart/flags.go
Labels: lgtm, size/L

#355 Extract testenv
  components/serverless/internal/controllers/kubernetes/configmap_controller_test.go
  components/serverless/internal/controllers/kubernetes/helpers_test.go
  components/serverless/internal/controllers/kubernetes/namespace_controller_test.go
  components/serverless/internal/controllers/kubernetes/secret_controller_test.go
  components/serverless/internal/controllers/kubernetes/serviceaccount_controller_test.go
  components/serverless/internal/testenv/testenv.go
  config/serverless/values.yaml
Labels: lgtm, size/L

#350 Move `serverless-manager` config files to `config/operator`
  Makefile
  components/serverless/Makefile
  config/operator/crd/bases/operator.kyma-project.io_serverlesses.yaml
  config/operator/crd/kustomization.yaml
  config/operator/crd/kustomizeconfig.yaml
  config/operator/default/kustomization.yaml
  config/operator/operator/kustomization.yaml
  config/operator/operator/operator.yaml
  config/operator/rbac/kustomization.yaml
  config/operator/rbac/role.yaml
  config/operator/rbac/role_binding.yaml
  config/operator/rbac/serverless_editor_role.yaml
  config/operator/rbac/serverless_viewer_role.yaml
  config/operator/rbac/service_account.yaml
  config/operator/ui-extensions/kustomization.yaml
  config/operator/ui-extensions/serverless/details
  config/operator/ui-extensions/serverless/form
  config/operator/ui-extensions/serverless/general
  config/operator/ui-extensions/serverless/kustomization.yaml
  config/operator/ui-extensions/serverless/list
  controllers/suite_test.go
Labels: size/M, lgtm, area/ci

#356 Upgrade k8s deps
  components/serverless/go.mod
  components/serverless/go.sum
  components/serverless/internal/controllers/serverless/system_state.go
  config/serverless/values.yaml
Labels: lgtm, size/L

#338 Add first version of x-kuberneets impl with unit tests
  components/serverless/.gitignore
  components/serverless/Makefile
  components/serverless/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/serverless/config/rbac/role.yaml
  components/serverless/config/webhook/manifests.yaml
  components/serverless/internal/testenv/testenv.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_types.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_x_validation_test.go
  config/serverless/templates/crds.yaml
  config/serverless/values.yaml
Labels: lgtm, size/L

#351 Reflect used presets in status
  components/serverless/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/serverless/internal/controllers/serverless/fsm.go
  components/serverless/internal/controllers/serverless/function_reconcile_test.go
  components/serverless/internal/controllers/serverless/suite_test.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_types.go
  config/serverless/templates/crds.yaml
  config/serverless/values.yaml
Labels: lgtm, size/L

#362 Reaarange test cases
  components/serverless/pkg/apis/serverless/v1alpha2/function_x_validation_test.go
  config/serverless/values.yaml
Labels: lgtm, size/L

#366 Copy api to components/operator
  components/operator/api/v1alpha1/groupversion_info.go
  components/operator/api/v1alpha1/serverless_helpers.go
  components/operator/api/v1alpha1/serverless_types.go
  components/operator/api/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, size/L

#363 Add labels validation
  components/serverless/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/serverless/pkg/apis/serverless/v1alpha2/function_types.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_x_validation_test.go
  config/serverless/templates/crds.yaml
  config/serverless/values.yaml
Labels: size/M, lgtm

#364 Add annotations validation
  components/serverless/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/serverless/pkg/apis/serverless/v1alpha2/function_types.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_x_validation_test.go
  config/serverless/templates/crds.yaml
  config/serverless/values.yaml
Labels: size/M, lgtm

#365 Add runtime validation
  components/serverless/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/serverless/pkg/apis/serverless/v1alpha2/function_types.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_x_validation_test.go
  config/serverless/templates/crds.yaml
  config/serverless/values.yaml
Labels: size/M, lgtm

#367 Add env names validation
  components/serverless/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/serverless/pkg/apis/serverless/v1alpha2/function_types.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_x_validation_test.go
  config/serverless/templates/crds.yaml
  config/serverless/values.yaml
Labels: lgtm, size/L

#368 Add onError loggers and fix proxy mock
  tests/serverless/internal/assertion/check_test.go
  tests/serverless/internal/assertion/cloud_events.go
  tests/serverless/internal/resources/runtimes/python.go
  tests/serverless/internal/testsuite/cloud_events.go
Labels: size/M, lgtm

#361 Move api to components/operator
  .dockerignore
  Dockerfile
  Makefile
  PROJECT
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/serverless_helpers.go
  api/v1alpha1/serverless_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/operator/operator/kustomization.yaml
  controllers/serverless_controller.go
  controllers/serverless_controller_test.go
  controllers/suite_test.go
  controllers/testhelper_test.go
  docs/user/resources/06-20-serverless-cr.md
  internal/state/add_finalizer_test.go
  internal/state/apply.go
  internal/state/apply_test.go
  internal/state/controller_configuration.go
  internal/state/controller_configuration_test.go
  internal/state/delete.go
  internal/state/delete_test.go
  internal/state/emit_event_test.go
  internal/state/fsm.go
  internal/state/fsm_test.go
  internal/state/initialize_test.go
  internal/state/new.go
  internal/state/optional_dependencies.go
  internal/state/optional_dependencies_test.go
  internal/state/registry.go
  internal/state/registry_test.go
  internal/state/remove_finalizer_test.go
  internal/state/served_filter.go
  internal/state/served_filter_test.go
  internal/state/serverless_utils.go
  internal/state/state.go
  internal/state/state_test.go
  internal/state/verify.go
  internal/state/verify_test.go
  main.go
Labels: lgtm, kind/cleanup, size/XL, area/documentation

#369 Update deps
  Dockerfile
  components/runtimes/python39/Dockerfile
  components/serverless/deploy/jobinit/Dockerfile
  components/serverless/deploy/manager/Dockerfile
  components/serverless/deploy/registry-gc/Dockerfile
  components/serverless/deploy/webhook/Dockerfile
  config/serverless/values.yaml
Labels: size/M, lgtm

#372 Add source validation
  components/serverless/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/serverless/pkg/apis/serverless/v1alpha2/function_types.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_x_validation_test.go
  config/serverless/templates/crds.yaml
  config/serverless/values.yaml
Labels: lgtm, size/L

#374 Add collect logs script to serverless integration tests
  components/runtimes/nodejs/.gitignore
  tests/serverless/collect_logs.sh
  tests/serverless/internal/resources/runtimes/nodejs.go
  tests/serverless/run-local.sh
Labels: size/M, lgtm

#375 add simple for secretMount validation
  components/serverless/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/serverless/pkg/apis/serverless/v1alpha2/function_types.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_x_validation_test.go
  config/serverless/templates/crds.yaml
  config/serverless/values.yaml
Labels: size/M, lgtm

#378 Temporary copy module-chart also to components/operator
  Makefile
Labels: lgtm, size/XS

#376 Align the default Serverless name to the agreed format
  .github/scripts/release.sh
  README.md
  config/operator/ui-extensions/serverless/general
  config/samples/default-serverless-cr-k3d-explicit.yaml
  config/samples/default-serverless-cr-k3d.yaml
  config/samples/default-serverless-cr.yaml
  hack/common/Makefile
  module-config-template.yaml
Labels: size/S, lgtm, area/ci

#385 Remove module chart
  .dockerignore
  Dockerfile
  Makefile
  components/operator/controllers/suite_test.go
Labels: size/M, lgtm

#382 namespaced scope secrets warning
  components/operator/internal/registry/secret.go
  components/operator/internal/registry/secret_test.go
  components/operator/internal/state/registry.go
  components/operator/internal/state/registry_test.go
Labels: kind/feature, area/serverless, lgtm, size/L

#386 unify quotation in doc
  components/serverless/README.md
  components/serverless/design/extend_function_spec_proposal.md
  config/serverless/charts/docker-registry/README.md
  docs/contributor/01-10-manual-installation-on-k3d.md
  docs/user/00-20-configure-serverless.md
  docs/user/technical-reference/05-20-env-variables.md
  docs/user/technical-reference/07-10-sample-functions.md
  docs/user/technical-reference/07-60-function-configuration-file.md
  docs/user/technical-reference/07-70-function-specification.md
  docs/user/tutorials/01-10-create-inline-function.md
  docs/user/tutorials/01-100-customize-function-traces.md
  docs/user/tutorials/01-11-create-git-function.md
  docs/user/tutorials/01-110-override-runtime-image.md
  docs/user/tutorials/01-120-inject-envs.md
  docs/user/tutorials/01-130-use-external-scalers.md
  docs/user/tutorials/01-140-use-secret-mounts.md
  docs/user/tutorials/01-20-expose-function.md
  docs/user/tutorials/01-30-manage-functions-with-kyma-cli.md
  docs/user/tutorials/01-80-log-into-private-packages-registry.md
Labels: lgtm, size/L, area/documentation
