Repository kyma-project/serverless, pull requests merged in 2023-01, with the labels that each got.

#38 Remove module chart from repo
  .gitignore
  module-chart/Chart.yaml
  module-chart/README.md
  module-chart/charts/docker-registry/.helmignore
  module-chart/charts/docker-registry/Chart.yaml
  module-chart/charts/docker-registry/README.md
  module-chart/charts/docker-registry/templates/NOTES.txt
  module-chart/charts/docker-registry/templates/_helpers.tpl
  module-chart/charts/docker-registry/templates/configmap.yaml
  module-chart/charts/docker-registry/templates/cronjob.yaml
  module-chart/charts/docker-registry/templates/deployment.yaml
  module-chart/charts/docker-registry/templates/destination-rule.yaml
  module-chart/charts/docker-registry/templates/ingress.yaml
  module-chart/charts/docker-registry/templates/poddisruptionbudget.yaml
  module-chart/charts/docker-registry/templates/pvc.yaml
  module-chart/charts/docker-registry/templates/rbac.yaml
  module-chart/charts/docker-registry/templates/secret.yaml
  module-chart/charts/docker-registry/templates/service.yaml
  module-chart/charts/docker-registry/values.yaml
  module-chart/charts/k3s-tests/Chart.yaml
  module-chart/charts/k3s-tests/README.md
  module-chart/charts/k3s-tests/templates/_helpers.tpl
  module-chart/charts/k3s-tests/templates/k3s-test.yaml
  module-chart/charts/k3s-tests/values.yaml
  module-chart/charts/webhook/Chart.yaml
  module-chart/charts/webhook/README.md
  module-chart/charts/webhook/templates/_helpers.tpl
  module-chart/charts/webhook/templates/cluster-role-binding.yaml
  module-chart/charts/webhook/templates/cluster-role.yaml
  module-chart/charts/webhook/templates/config-observability.yaml
  module-chart/charts/webhook/templates/configmap.yaml
  module-chart/charts/webhook/templates/deployment.yaml
  module-chart/charts/webhook/templates/secret.yaml
  module-chart/charts/webhook/templates/service-account.yaml
  module-chart/charts/webhook/templates/service.yaml
  module-chart/charts/webhook/templates/webhooks.yaml
  module-chart/charts/webhook/values.yaml
  module-chart/profile-evaluation.yaml
  module-chart/profile-production.yaml
  module-chart/templates/_helper_tests.txt
  module-chart/templates/_helpers.tpl
  module-chart/templates/cluster-role-binding.yaml
  module-chart/templates/cluster-role.yaml
  module-chart/templates/configmap.yaml
  module-chart/templates/daemonset-certs-configmap.yaml
  module-chart/templates/daemonset-certs.yaml
  module-chart/templates/daemonset-service-account.yaml
  module-chart/templates/deployment.yaml
  module-chart/templates/function-dashboard.yaml
  module-chart/templates/function-metrics-dashboard.yaml
  module-chart/templates/leader-election-role-binding.yaml
  module-chart/templates/leader-election-role.yaml
  module-chart/templates/runtimes.yaml
  module-chart/templates/secrets.yaml
  module-chart/templates/service-accounts.yaml
  module-chart/templates/service-monitor.yaml
  module-chart/templates/service.yaml
  module-chart/templates/virtualservice.yaml
  module-chart/values.yaml
Labels: lgtm, size/XXL

#32 Remove redundant coreDNS patching
  README.md
  hack/get_kyma_localhost_registry_name.sh
  hack/local/serverless/Makefile
Labels: size/M, lgtm, do-not-merge/hold

#49 Introduce latest changes to fix pipelines
  Makefile
  README.md
  config/samples/operator_v1alpha1_serverless_k3d_explicit.yaml
  hack/local/serverless/Makefile
  hack/verify_kyma_status.sh
Labels: size/M, area/serverless, lgtm, kind/cleanup

#51 Add MK to codeowners
  CODEOWNERS
Labels: lgtm, size/XS
