Repository kyma-project/serverless, pull requests merged in 2023-04, with the labels that each got.

#85 Add deletion strategy
  internal/chart/check.go
  internal/chart/check_test.go
  internal/chart/install_test.go
  internal/chart/uninstall.go
  internal/state/apply.go
  internal/state/delete.go
  internal/state/initialize.go
  internal/state/prerequisites.go
  internal/state/remove_finalizer.go
  internal/state/state.go
  internal/state/state_functions.go
  internal/state/verify.go
Labels: area/serverless, lgtm, size/XL

#86 Add render-manifest make target
  .env
  .gitignore
  Makefile
  hack/ci/Makefile
Labels: size/S, lgtm

#90 Remove deleted condition
  api/v1alpha1/serverless_types.go
  go.mod
  go.sum
  internal/state/delete.go
  internal/state/emmit_event.go
  internal/state/emmit_event_test.go
  internal/state/update_status.go
Labels: area/serverless, lgtm, size/L

#95 Makefile cleanup
  .gitignore
  Makefile
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_serverlesses.yaml
  config/crd/patches/webhook_in_serverlesses.yaml
  config/default/kustomization.yaml
  config/default/manager_config_patch.yaml
  config/manager/kustomization.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  config/samples/operator_v1alpha1_serverless_k3d.yaml
  config/samples/operator_v1alpha1_serverless_k3d_explicit.yaml
  docs/manual-installation-on-k3d.md
  hack/common/Makefile
  hack/common/k3d-patches/patch-kyma.yaml
  hack/common/verify_serverless_status.sh
Labels: lgtm, size/L, area/documentation

#93 Improve status update states
  api/v1alpha1/serverless_helpers.go
  internal/state/apply.go
  internal/state/apply_test.go
  internal/state/delete.go
  internal/state/delete_test.go
  internal/state/emit_event_test.go
  internal/state/emmit_event_test.go
  internal/state/fsm.go
  internal/state/initialize.go
  internal/state/initialize_test.go
  internal/state/prerequisites.go
  internal/state/prerequisites_test.go
  internal/state/remove_finalizer.go
  internal/state/remove_finalizer_test.go
  internal/state/take_snapshot.go
  internal/state/take_snapshot_test.go
  internal/state/update_status.go
  internal/state/verify.go
  internal/state/verify_test.go
Labels: area/serverless, lgtm, kind/cleanup, size/XL

#94 Implement the PublisherProxyURL and the TraceCollectorURL
  .gitignore
  api/v1alpha1/serverless_helpers.go
  api/v1alpha1/serverless_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_serverlesses.yaml
  controllers/serverless_controller_test.go
  controllers/testhelper_test.go
  internal/chart/flags.go
  internal/chart/flags_test.go
  internal/dependencies/optional.go
  internal/state/emit_event.go
  internal/state/emit_event_test.go
  internal/state/initialize.go
  internal/state/initialize_test.go
  internal/state/optional_dependencies.go
  internal/state/optional_dependencies_test.go
  internal/state/prerequisites.go
  internal/state/prerequisites_test.go
  internal/state/state_test.go
  internal/state/take_snapshot.go
  internal/state/take_snapshot_test.go
  internal/state/update_status.go
Labels: lgtm, size/L
