Repository kyma-project/serverless, pull requests merged in 2023-07, with the labels that each got.

#143 State update refactor 2
  internal/state/apply.go
  internal/state/apply_test.go
  internal/state/delete.go
  internal/state/delete_test.go
  internal/state/emit_event.go
  internal/state/emit_event_test.go
  internal/state/initialize.go
  internal/state/initialize_test.go
  internal/state/optional_dependencies.go
  internal/state/optional_dependencies_test.go
  internal/state/registry.go
  internal/state/registry_test.go
  internal/state/remove_finalizer.go
  internal/state/remove_finalizer_test.go
  internal/state/served_filter.go
  internal/state/served_filter_test.go
  internal/state/state.go
  internal/state/state_test.go
  internal/state/take_snapshot.go
  internal/state/take_snapshot_test.go
  internal/state/update_status.go
  internal/state/update_status_test.go
  internal/state/verify.go
  internal/state/verify_test.go
Labels: lgtm, size/XXL

#144 State update refactor cleanup
  internal/chart/check_test.go
  internal/chart/install_test.go
  internal/chart/uninstall_test.go
  internal/state/apply.go
  internal/state/delete.go
  internal/state/emit_event.go
  internal/state/fsm.go
  internal/state/initialize.go
  internal/state/initialize_test.go
  internal/state/optional_dependencies.go
  internal/state/remove_finalizer.go
  internal/state/verify_test.go
Labels: size/M, lgtm

#145 remove not necessary setServed
  internal/state/verify.go
Labels: lgtm, size/XS

#146 Add Do Not Edit Disclaimer to managed objects
  internal/annotation/disclaimer.go
  internal/annotation/disclaimer_test.go
  internal/chart/install.go
Labels: size/M, lgtm

#147 fix configurationCheckErr
  api/v1alpha1/serverless_helpers.go
  internal/state/registry.go
  internal/state/registry_test.go
  internal/state/state_test.go
Labels: size/M, area/serverless, lgtm

#148 add checking condition statuses in tests
  internal/state/apply_test.go
  internal/state/delete_test.go
  internal/state/optional_dependencies_test.go
  internal/state/registry_test.go
  internal/state/served_filter_test.go
  internal/state/state_test.go
  internal/state/verify_test.go
Labels: size/M, lgtm

#151 Refactor fix-configurationCheckErr PR
  api/v1alpha1/serverless_helpers.go
  internal/state/optional_dependencies.go
  internal/state/optional_dependencies_test.go
  internal/state/registry.go
  internal/state/registry_test.go
Labels: area/serverless, lgtm, size/L

#150 Remove reconciler DO NOT EDIT disclaimer
  internal/annotation/disclaimer.go
  internal/annotation/disclaimer_test.go
  internal/chart/install.go
Labels: lgtm, size/L

#152 Unify config creation
  controllers/serverless_controller.go
  controllers/suite_test.go
  go.mod
  go.sum
  internal/config/config.go
  internal/state/new.go
  main.go
Labels: size/M, lgtm

#142 Resolve Node Port conflict
  .gitignore
  Makefile
  internal/chart/chart.go
  internal/chart/flags.go
  internal/registry/node_port.go
  internal/registry/node_port_test.go
  internal/state/fsm.go
  internal/state/optional_dependencies_test.go
  internal/state/registry.go
  internal/state/registry_test.go
Labels: lgtm, size/L

#153 Add targets to deploy on k3d
  hack/common/Makefile
  hack/local/Makefile
Labels: size/S, lgtm

#154 Renaming Serverless Operator
  api/v1alpha1/serverless_types.go
  config/default/kustomization.yaml
  config/manager/manager.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role_binding.yaml
  config/rbac/serverless_editor_role.yaml
  config/rbac/serverless_viewer_role.yaml
  config/rbac/service_account.yaml
Labels: size/M, lgtm

#155 Fix a broken link
  README.md
Labels: lgtm, size/XS

#156 Prepare makefiles for new test-infra dind image
  hack/ci/Makefile
  hack/common/Makefile
Labels: lgtm, size/XS

#159 Configure UI for Serverless CRD
  config/default/kustomization.yaml
  config/ui-extensions/kustomization.yaml
  config/ui-extensions/serverless/details
  config/ui-extensions/serverless/form
  config/ui-extensions/serverless/general
  config/ui-extensions/serverless/kustomization.yaml
  config/ui-extensions/serverless/list
Labels: kind/feature, area/serverless, lgtm, size/L

#158 set status.dockerRegistry from serverless cluster-wide external registry secret when it exists
  internal/registry/secret.go
  internal/registry/secret_test.go
  internal/registry/test_helpers.go
  internal/state/registry.go
  internal/state/registry_test.go
  internal/state/verify_test.go
Labels: lgtm, size/L

#164 Rename Trace Endoint in UI
  config/ui-extensions/serverless/details
  config/ui-extensions/serverless/form
Labels: area/serverless, lgtm, size/XS, kind/cleanup

#157 Rename to Serverless Operator #2
  .gitignore
  Dockerfile
  Makefile
  README.md
  config/default/kustomization.yaml
  config/operator/kustomization.yaml
  config/operator/operator.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/serverless_editor_role.yaml
  config/rbac/serverless_viewer_role.yaml
  config/rbac/service_account.yaml
  config/ui-extensions/serverless/kustomization.yaml
  docs/configurability-of-serverless.md
  docs/manual-installation-on-k3d.md
  docs/serverless-CR.md
  hack/common/Makefile
  internal/chart/install.go
  internal/state/optional_dependencies.go
  main.go
Labels: lgtm, size/L, area/documentation

#160 Implement upgradability test scenario
  hack/ci/Makefile
Labels: size/S, lgtm

#162 Detect serverless docker registry misconfigurations
  internal/registry/secret.go
  internal/registry/secret_test.go
  internal/state/delete.go
  internal/state/emit_event.go
  internal/state/fsm.go
  internal/state/optional_dependencies.go
  internal/state/registry.go
  internal/state/registry_test.go
  internal/state/verify.go
  internal/state/verify_test.go
  internal/warning/warning.go
  internal/warning/warning_test.go
Labels: lgtm, size/L

#141 Move Overview and Tutorials documentation to Serverless manager repo
  docs/user/00-10-from-code-to-function.md
  docs/user/00-20-container-registries.md
  docs/user/01-10-development-toolkit.md
  docs/user/02-10-security-considerations.md
  docs/user/02-20-limitations.md
  docs/user/03-10-create-inline-function.md
  docs/user/03-100-customize-function-traces.md
  docs/user/03-11-create-git-function.md
  docs/user/03-110-override-runtime-image.md
  docs/user/03-120-inject-envs.md
  docs/user/03-130-use-external-scalers.md
  docs/user/03-140-use-secret-mounts.md
  docs/user/03-20-expose-function.md
  docs/user/03-30-manage-functions-with-kyma-cli.md
  docs/user/03-40-debug-function.md
  docs/user/03-50-sync-function-with-gitops.md
  docs/user/03-60-set-external-registry.md
  docs/user/03-70-switch-to-external-registry.md
  docs/user/03-80-log-into-private-packages-registry.md
  docs/user/03-90-set-asynchronous-connection.md
  docs/user/README.md
Labels: lgtm, size/XXL, area/documentation

#170 Remove checking external registry secret type
  internal/registry/secret.go
  internal/registry/secret_test.go
Labels: size/S, lgtm

#169 Add status badge to readme
  README.md
Labels: lgtm, size/XS

#174 Run k3d upgrade test using k3d registry
  .gitignore
  hack/ci/Makefile
Labels: lgtm, size/XS
