Repository kyma-project/serverless, pull requests merged in 2023-05, with the labels that each got.

#99 Change order of parsed resources
  internal/chart/chart.go
Labels: kind/bug, area/serverless, lgtm, size/XS

#97 add Serverless CR doc
  docs/serverless-CR.md
Labels: size/M, area/serverless, lgtm, area/documentation

#106 Bump version before release
  .env
  config/manager/kustomization.yaml
Labels: lgtm, size/XS

#102 Cover case when Serverless CR is duplicated
  api/v1alpha1/serverless_types.go
  config/crd/bases/operator.kyma-project.io_serverlesses.yaml
  internal/chart/install.go
  internal/state/fsm.go
  internal/state/new.go
  internal/state/served_filter.go
  internal/state/served_filter_test.go
  internal/state/update_status.go
  internal/state/update_status_test.go
Labels: lgtm, size/L
