Repository kyma-project/serverless, pull requests merged in 2023-03, with the labels that each got.

#54 add makefile rules for integration tests
  .env
  Makefile
  README.md
  config/moduletemplates/kustomization.yaml
  hack/ci/Makefile
  hack/generate_module-chart.sh
  hack/local/serverless/Makefile
  hack/verify_kyma_status.sh
Labels: lgtm, size/L

#58 Fix error msg to test CI/CD jobs
  pkg/reconciler/reconciler.go
Labels: lgtm, size/XS

#60 Improve template print
  hack/ci/Makefile
  hack/local/serverless/Makefile
Labels: lgtm, size/XS

#62 Remove dependency to ServiceMonitor CRD
  .gitignore
  Makefile
  controllers/serverless_controller_rbac.go
  controllers/suite_test.go
  internal/dependencies/prerequisites.go
  internal/dependencies/prerequisites_test.go
Labels: size/M, lgtm

#66 Registry configuration secret doc
  README.md
  docs/configurability-of-serverless.md
Labels: size/S, lgtm, area/documentation

#63 Use the `kubectl apply` instead of `alpha deploy --templates`
  Makefile
  config/moduletemplates/kustomization.yaml
  hack/ci/Makefile
  hack/local/serverless/Makefile
Labels: size/S, lgtm, kind/cleanup

#64 Add target to run manager without lifecycle-manager
  config/rbac/role.yaml
  hack/local/serverless/Makefile
Labels: size/S, lgtm, kind/cleanup

#61 allow configuration for external docker registry via Serverless CR
  api/v1alpha1/serverless_helpers.go
  api/v1alpha1/serverless_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_serverlesses.yaml
  config/samples/operator_v1alpha1_serverless_k3d_explicit.yaml
  controllers/serverless_controller_test.go
  controllers/testhelper_test.go
  internal/state/fsm.go
  internal/state/state_functions.go
Labels: lgtm, size/L

#68 Prepare doc with the makefiles architecture
  hack/makefile-strategy.md
  hack/makefile-strategy.png
Labels: size/M, lgtm

#72 Add simple installation instructions
  README.md
  docs/manual-installation-on-k3d.md
Labels: lgtm, size/L, area/documentation

#74 Remove unused make targets
  Makefile
  README.md
  hack/ci/Makefile
  hack/local/serverless/Makefile
Labels: area/serverless, size/S, lgtm, kind/cleanup

#76 Run the serverless integration test from local sources
  .gitignore
  Makefile
  hack/ci/Makefile
Labels: size/M, area/serverless, lgtm

#79 Improve hack/common Makefile descriptions
  hack/common/Makefile
Labels: size/M, area/serverless, lgtm, kind/cleanup

#80 Remove dependency to cluster-essentials
  README.md
  config/rbac/role.yaml
  controllers/serverless_controller_rbac.go
  docs/manual-installation-on-k3d.md
  hack/common/Makefile
Labels: size/M, lgtm, area/documentation

#83 Remove kube-rbac container from serverless operator
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
Labels: lgtm, size/L, kind/cleanup

#82 Get rid of the module-manager
  controllers/serverless_controller.go
  controllers/serverless_controller_test.go
  go.mod
  go.sum
  internal/chart/cache.go
  internal/chart/chart.go
  internal/chart/client_getter.go
  internal/chart/install.go
  internal/chart/install_test.go
  internal/chart/uninstall.go
  internal/chart/uninstall_test.go
  internal/chart/verify.go
  internal/chart/verify_test.go
  internal/state/fsm.go
  internal/state/fsm_test.go
  internal/state/new.go
  internal/state/state_functions.go
Labels: lgtm, size/XL
