Repository kyma-project/serverless, pull requests merged in 2024-03, with the labels that each got.

#780 Fix unit tests after k8s upgrade
  components/serverless/internal/controllers/serverless/function_reconcile_test.go
Labels: lgtm, size/XS, cla: yes

#784 Add flag to ignore GCE creds helper creation for kaniko job
  components/serverless/internal/controllers/serverless/system_state.go
Labels: kind/bug, area/serverless, lgtm, size/XS, cla: yes

#785 Remove not used docker compose
  components/operator/hack/build_local_images.sh
  docker-compose.yaml
Labels: size/M, lgtm, cla: yes

#753 Move gardener to GitHub actions
  .github/workflows/operator-verify.yaml
  hack/Makefile
Labels: size/S, lgtm, cla: yes

#786 Use not deprecated machine in gardener tests
  hack/gardener.mk
Labels: lgtm, size/XS, cla: yes

#791 fix slack channel address
  docs/user/troubleshooting-guides/README.md
Labels: area/serverless, lgtm, size/XS, kind/cleanup, cla: yes

#790 fix typo in makefile variable
  hack/gardener.mk
Labels: area/serverless, lgtm, size/XS, kind/cleanup, cla: yes

#794 fix gardener linux version
  hack/gardener.mk
Labels: area/serverless, lgtm, size/XS, kind/cleanup, cla: yes

#797 adjust project README
  README.md
Labels: size/M, area/serverless, lgtm, kind/cleanup, cla: yes

#798 adjust testing strategy
  docs/contributor/04-10-testing-strategy.md
Labels: area/serverless, size/S, lgtm, kind/cleanup, cla: yes

#796 Make Python 3.12 default, deprecate 3.9
  components/serverless/.golangci.yaml
  components/serverless/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/serverless/hack/controller.env
  components/serverless/internal/controllers/serverless/build_resources_test.go
  components/serverless/internal/controllers/serverless/metrics/function_metrics_test.go
  components/serverless/internal/controllers/serverless/validation_test.go
  components/serverless/internal/webhook/fixtures_test.go
  components/serverless/internal/webhook/validating_webhook_test.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_types.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_x_validation_test.go
  config/serverless/templates/busola-serverless-extension.yaml
  config/serverless/templates/crds.yaml
  docs/user/resources/06-10-function-cr.md
  docs/user/technical-reference/05-20-env-variables.md
  docs/user/technical-reference/07-10-sample-functions.md
  docs/user/technical-reference/07-60-function-configuration-file.md
  docs/user/technical-reference/07-70-function-specification.md
  docs/user/tutorials/01-110-override-runtime-image.md
  docs/user/tutorials/01-140-use-secret-mounts.md
  docs/user/tutorials/01-30-manage-functions-with-kyma-cli.md
  docs/user/tutorials/01-50-sync-function-with-gitops.md
  examples/python-text2img/config.yaml
  examples/python-text2img/resources/function.yaml
  tests/serverless/internal/resources/runtimes/python.go
  tests/serverless/internal/testsuite/cloud_events.go
  tests/serverless/internal/testsuite/gitauth.go
Labels: area/serverless, lgtm, size/L, kind/chore, cla: yes

#792 runtimes: Add nodejs20 image
  .github/dependabot.yml
  components/runtimes/nodejs/nodejs20/Dockerfile
  components/runtimes/nodejs/nodejs20/package.json
  sec-scanners-config.yaml
Labels: size/M, lgtm, cla: yes

#799 Fix unit tests on Mac
  hack/tools.mk
Labels: lgtm, size/XS, cla: yes

#811 add makefile strategy description
  hack/makefile-strategy.md
Labels: size/M, area/serverless, lgtm, kind/cleanup, cla: yes

#817 Fix opentelemetry api import for SpanStatusCodes
  components/runtimes/nodejs/lib/helper.js
  components/runtimes/nodejs/nodejs16/package.json
  components/runtimes/nodejs/nodejs18/package.json
Labels: kind/bug, size/S, lgtm, cla: yes

#815 Move relevant examples to the Serverless repo
  examples/custom-serverless-runtime-image/Dockerfile
  examples/custom-serverless-runtime-image/README.md
  examples/custom-serverless-runtime-image/kubeless/ce.py
  examples/custom-serverless-runtime-image/kubeless/kubeless.py
  examples/custom-serverless-runtime-image/kubeless/requirements.txt
  examples/custom-serverless-runtime-image/kubeless/tracing.py
  examples/incluster_eventing/Makefile
  examples/incluster_eventing/README.md
  examples/incluster_eventing/k8s-resources/emitter-fn.yaml
  examples/incluster_eventing/k8s-resources/receiver-fn.yaml
  examples/incluster_eventing/src/emitter-fn/config.yaml
  examples/incluster_eventing/src/emitter-fn/handler.js
  examples/incluster_eventing/src/emitter-fn/package.json
  examples/incluster_eventing/src/receiver-fn/config.yaml
  examples/incluster_eventing/src/receiver-fn/handler.js
  examples/incluster_eventing/src/receiver-fn/package.json
Labels: area/serverless, lgtm, size/XL, area/documentation, cla: yes

#800 Add nodejs 20 runtime
  components/serverless/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/serverless/internal/controllers/serverless/build_resources_test.go
  components/serverless/internal/controllers/serverless/runtime/runtime.go
  components/serverless/internal/controllers/serverless/runtime/runtime_test.go
  components/serverless/internal/controllers/serverless/utils.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_types.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_x_validation_test.go
  components/serverless/pkg/apis/serverless/v1alpha2/runtime_validation.go
  config/serverless/templates/busola-serverless-extension.yaml
  config/serverless/templates/crds.yaml
  config/serverless/templates/runtimes.yaml
  config/serverless/values.yaml
  docs/user/resources/06-10-function-cr.md
  docs/user/technical-reference/05-20-env-variables.md
  docs/user/technical-reference/07-60-function-configuration-file.md
  docs/user/technical-reference/07-70-function-specification.md
  tests/serverless-bench/fixtures/functions/nodejs20-l.yaml
  tests/serverless-bench/fixtures/functions/nodejs20-m.yaml
  tests/serverless-bench/fixtures/functions/nodejs20-s.yaml
  tests/serverless-bench/fixtures/functions/nodejs20-xl.yaml
  tests/serverless-bench/fixtures/functions/nodejs20-xs.yaml
  tests/serverless-bench/run-benchmarks.sh
  tests/serverless/internal/testsuite/api_gateway.go
  tests/serverless/internal/testsuite/cloud_events.go
  tests/serverless/internal/testsuite/light_runtimes.go
  tests/serverless/internal/testsuite/tracing.go
Labels: kind/feature, area/serverless, lgtm, size/L, cla: yes

#809 Remove Nodejs16 image
  .github/dependabot.yml
  components/runtimes/nodejs/nodejs16/Dockerfile
  components/runtimes/nodejs/nodejs16/package.json
Labels: size/M, lgtm, kind/chore, cla: yes

#827 chore: Deprecate Nodejs18 environment
  components/serverless/.golangci.yaml
  components/serverless/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/serverless/internal/controllers/serverless/utils_test.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_types.go
  config/serverless/templates/busola-serverless-extension.yaml
  config/serverless/templates/crds.yaml
  docs/user/resources/06-10-function-cr.md
  docs/user/technical-reference/05-20-env-variables.md
  docs/user/technical-reference/07-60-function-configuration-file.md
  docs/user/technical-reference/07-70-function-specification.md
Labels: size/M, lgtm, cla: yes

#832 Fix link to examples in docs
  docs/user/08-10-best-practices.md
  docs/user/tutorials/01-11-create-git-function.md
  docs/user/tutorials/01-110-override-runtime-image.md
  docs/user/tutorials/01-90-set-asynchronous-connection.md
Labels: size/S, lgtm, cla: yes

#831 Make Nodejs20 default
  components/serverless/design/extend_function_spec_proposal.md
  components/serverless/internal/controllers/serverless/build_resources_test.go
  components/serverless/internal/controllers/serverless/fixtures_test.go
  components/serverless/internal/controllers/serverless/function_reconcile_gitops_test.go
  components/serverless/internal/controllers/serverless/function_reconcile_test.go
  components/serverless/internal/controllers/serverless/gitops_test.go
  components/serverless/internal/controllers/serverless/runtime/nodejs_test.go
  components/serverless/internal/controllers/serverless/validation_test.go
  components/serverless/internal/webhook/webhook_config.go
  config/serverless/templates/busola-serverless-extension.yaml
  docs/user/resources/06-10-function-cr.md
  docs/user/technical-reference/05-20-env-variables.md
  docs/user/technical-reference/07-10-sample-functions.md
  docs/user/technical-reference/07-20-function-processing-stages.md
  docs/user/technical-reference/07-60-function-configuration-file.md
  docs/user/technical-reference/07-70-function-specification.md
  docs/user/troubleshooting-guides/03-20-failing-function-container.md
  docs/user/troubleshooting-guides/03-40-function-build-failing-k3d.md
  docs/user/tutorials/01-10-create-inline-function.md
  docs/user/tutorials/01-11-create-git-function.md
  docs/user/tutorials/01-120-inject-envs.md
  docs/user/tutorials/01-130-use-external-scalers.md
  docs/user/tutorials/01-80-log-into-private-packages-registry.md
  docs/user/tutorials/01-90-set-asynchronous-connection.md
  examples/incluster_eventing/k8s-resources/emitter-fn.yaml
  examples/incluster_eventing/k8s-resources/receiver-fn.yaml
  examples/incluster_eventing/src/emitter-fn/config.yaml
  examples/incluster_eventing/src/receiver-fn/config.yaml
  tests/serverless/internal/testsuite/gitauth.go
  tests/serverless/internal/testsuite/gitops.go
  tests/serverless/internal/testsuite/light_runtimes.go
Labels: lgtm, size/L, cla: yes

#834 Apply markdowlint rules in the serverless repository
  .markdownlint.yaml
  .markdownlintignore
  docs/contributor/03-10-scripts-not-working.md
  docs/contributor/04-10-testing-strategy.md
  docs/user/00-10-from-code-to-function.md
  docs/user/00-20-configure-serverless.md
  docs/user/00-30-development-toolkit.md
  docs/user/00-40-security-considerations.md
  docs/user/00-50-limitations.md
  docs/user/08-10-best-practices.md
  docs/user/README.md
  docs/user/resources/06-20-serverless-cr.md
  docs/user/resources/README.md
  docs/user/technical-reference/04-10-architecture.md
  docs/user/technical-reference/04-20-internal-registry.md
  docs/user/technical-reference/05-20-env-variables.md
  docs/user/technical-reference/07-40-git-source-type.md
  docs/user/technical-reference/07-70-function-specification.md
  docs/user/technical-reference/07-80-available-presets.md
  docs/user/troubleshooting-guides/03-10-cannot-build-functions.md
  docs/user/troubleshooting-guides/03-40-function-build-failing-k3d.md
  docs/user/troubleshooting-guides/03-50-serverless-periodically-restaring.md
  docs/user/troubleshooting-guides/README.md
  docs/user/tutorials/01-10-create-inline-function.md
  docs/user/tutorials/01-100-customize-function-traces.md
  docs/user/tutorials/01-11-create-git-function.md
  docs/user/tutorials/01-120-inject-envs.md
  docs/user/tutorials/01-130-use-external-scalers.md
  docs/user/tutorials/01-140-use-secret-mounts.md
  docs/user/tutorials/01-20-expose-function.md
  docs/user/tutorials/01-30-manage-functions-with-kyma-cli.md
  docs/user/tutorials/01-40-debug-function.md
  docs/user/tutorials/01-50-sync-function-with-gitops.md
  docs/user/tutorials/01-60-set-external-registry.md
  docs/user/tutorials/01-90-set-asynchronous-connection.md
  docs/user/tutorials/README.md
  markdown_heading_capitalization.js
Labels: lgtm, size/L, area/documentation, cla: yes

#835 Add missing clusterrole verbs
  components/operator/controllers/serverless_controller_rbac.go
  config/operator/base/rbac/role.yaml
Labels: kind/bug, area/serverless, lgtm, size/XS, cla: yes

#837 mark Python 3.9 deprecated in Busola
  config/serverless/templates/busola-serverless-extension.yaml
Labels: lgtm, size/XS, cla: yes

#838 Set all log level to debug in k8s resources controllers
  components/serverless/Makefile
  components/serverless/internal/controllers/kubernetes/configmap_service.go
  components/serverless/internal/controllers/kubernetes/namespace_controller.go
  components/serverless/internal/controllers/kubernetes/secret_service.go
  components/serverless/internal/controllers/kubernetes/serviceaccount_service.go
Labels: size/S, lgtm, cla: yes

#839 Adjust Python
  components/runtimes/python/.gitignore
  components/runtimes/python/README.md
  components/runtimes/python/kubeless.py
  components/runtimes/python/lib/ce.py
  components/runtimes/python/lib/tracing.py
  components/runtimes/python/python312/Dockerfile
  components/runtimes/python/python39/Dockerfile
Labels: size/S, lgtm, cla: yes

#840 Remove webhook from sec-scanners-config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes
