Repository kyma-project/serverless, pull requests merged in 2024-02, with the labels that each got.

#595 Use latest k3s in serverless CI tests
  .github/workflows/operator-verify.yaml
Labels: area/serverless, lgtm, size/XS, area/ci, cla: yes

#681 Apply the flexible alerts plugin to the Serverless docs
  docs/user/00-10-from-code-to-function.md
  docs/user/00-20-configure-serverless.md
  docs/user/00-50-limitations.md
  docs/user/08-10-best-practices.md
  docs/user/technical-reference/04-10-architecture.md
  docs/user/technical-reference/04-20-internal-registry.md
  docs/user/technical-reference/07-10-sample-functions.md
  docs/user/technical-reference/07-20-function-processing-stages.md
  docs/user/technical-reference/07-40-git-source-type.md
  docs/user/technical-reference/07-60-function-configuration-file.md
  docs/user/technical-reference/07-70-function-specification.md
  docs/user/troubleshooting-guides/03-10-cannot-build-functions.md
  docs/user/tutorials/01-10-create-inline-function.md
  docs/user/tutorials/01-11-create-git-function.md
  docs/user/tutorials/01-130-use-external-scalers.md
  docs/user/tutorials/01-140-use-secret-mounts.md
  docs/user/tutorials/01-20-expose-function.md
  docs/user/tutorials/01-30-manage-functions-with-kyma-cli.md
  docs/user/tutorials/01-50-sync-function-with-gitops.md
  docs/user/tutorials/01-60-set-external-registry.md
  docs/user/tutorials/01-80-log-into-private-packages-registry.md
  docs/user/tutorials/01-90-set-asynchronous-connection.md
Labels: lgtm, size/L, area/documentation, cla: yes

#680 remove unused makefile targets
  README.md
  components/operator/Makefile
  components/operator/hack/ci/Makefile
  components/operator/hack/common/Makefile
  components/operator/hack/common/k3d-patches/patch-k3d-lifecycle-manager-clusterrole.yaml
  components/operator/hack/local/Makefile
Labels: area/serverless, lgtm, size/L, kind/cleanup, cla: yes

#683 Migrate serverless integration tests
  .github/workflows/serverless-verify.yaml
Labels: size/M, lgtm, kind/missing-test, area/ci, cla: yes

#685 remove unused makefile targets (2)
  components/operator/Makefile
  components/operator/hack/ci/Makefile
  components/operator/hack/common/Makefile
  components/operator/hack/common/verify_kyma_status.sh
Labels: size/M, area/serverless, lgtm, kind/cleanup, cla: yes

#687 Fix image tag in git auth integration test
  .github/workflows/serverless-verify.yaml
Labels: lgtm, size/XS, cla: yes

#688 Remove redundant integration test
  .github/workflows/serverless-verify.yaml
Labels: lgtm, size/XS, cla: yes

#690 Fix operator image directory in post git-auth tests
  .github/workflows/serverless-verify.yaml
Labels: lgtm, size/XS, kind/failing-test, area/tests, cla: yes

#674 add branch protection rule exemption
  .github/workflows/create-release.yaml
Labels: lgtm, size/XS, cla: yes

#694 Print more details in serverless integration tests
  tests/serverless/cmd/main.go
  tests/serverless/collect_logs.sh
  tests/serverless/internal/assertion/cloud_events.go
  tests/serverless/internal/resources/runtimes/nodejs.go
  tests/serverless/internal/resources/runtimes/python.go
Labels: size/M, lgtm, kind/failing-test, area/tests, cla: yes

#695 Makefile remove unused 2
  components/operator/hack/ci/Makefile
  components/operator/hack/local/Makefile
Labels: area/serverless, size/S, lgtm, kind/cleanup, cla: yes

#696 Add make_latest release based on semantic version
  .github/scripts/publish_release.sh
  .github/workflows/create-release.yaml
Labels: lgtm, size/XS, cla: yes

#700 Change make_latest to be based on boolean
  .github/scripts/publish_release.sh
  .github/workflows/create-release.yaml
Labels: size/S, lgtm, cla: yes

#701 Release latest config, make_latest legacy
  .github/scripts/create_draft_release.sh
  .github/scripts/publish_release.sh
  .github/workflows/create-release.yaml
Labels: size/S, lgtm, cla: yes

#698 Improve runtimes logs in tests
  tests/serverless/collect_logs.sh
  tests/serverless/internal/resources/runtimes/nodejs.go
  tests/serverless/internal/resources/runtimes/python.go
Labels: size/M, lgtm, kind/failing-test, area/tests, cla: yes

#699 Secrets deletion refactor
  components/operator/internal/state/delete.go
Labels: size/M, area/serverless, lgtm, kind/cleanup, cla: yes

#703 Remove unbound variable from release script
  .github/scripts/publish_release.sh
Labels: lgtm, size/XS, cla: yes

#702 Fix unstable integration tests
  tests/serverless/internal/assertion/check_test.go
  tests/serverless/internal/assertion/cloud_events.go
  tests/serverless/internal/resources/runtimes/nodejs.go
  tests/serverless/internal/resources/runtimes/python.go
  tests/serverless/internal/testsuite/cloud_events.go
Labels: size/M, lgtm, kind/failing-test, area/tests, cla: yes

#705 Retry GET request to function
  tests/serverless/internal/assertion/cloud_events.go
  tests/serverless/internal/resources/function/steps.go
Labels: size/M, lgtm, kind/failing-test, area/tests, cla: yes

#706 improve the isConditionReady func
  tests/serverless/internal/resources/function/function.go
Labels: size/S, lgtm, kind/failing-test, area/tests, cla: yes

#715 Force rebuild of gitserver
  tests/gitserver/Dockerfile
  tests/serverless/internal/config.go
Labels: lgtm, size/XS, cla: yes

#714 Use prod image of the gitserver
  tests/serverless/internal/config.go
Labels: area/serverless, lgtm, size/XS, cla: yes

#704 remove not necessary variables from operator makefiles
  components/operator/Makefile
  components/operator/hack/ci/Makefile
  components/operator/hack/common/Makefile
  components/operator/hack/local/Makefile
Labels: size/M, area/serverless, lgtm, kind/cleanup, cla: yes

#713 Add flag to choose if the release is latest or is not
  .github/scripts/create_draft_release.sh
  .github/workflows/create-release.yaml
Labels: size/S, lgtm, cla: yes

#716 Fix not passing second parameter to the script
  .github/workflows/create-release.yaml
Labels: lgtm, size/XS, cla: yes

#718 Revert "actions(deps): bump golangci/golangci-lint-action from 3 to 4"
  .github/workflows/operator-verify.yaml
  .github/workflows/serverless-verify.yaml
Labels: lgtm, size/XS, cla: yes

#719 Fix latest release by moving make_latest
  .github/scripts/create_draft_release.sh
  .github/scripts/publish_release.sh
  .github/workflows/create-release.yaml
Labels: size/S, lgtm, cla: yes

#724 Fix 1.3 gitserver image
  tests/serverless/internal/config.go
Labels: lgtm, size/XS, cla: yes

#721 Adjust release-1.3.x to be able to specify if it's latest or not
  .github/scripts/publish_release.sh
  .github/workflows/create-release.yaml
Labels: lgtm, size/XS, cla: yes

#725 Test serverless on k8s 1.28.6
  .github/workflows/operator-verify.yaml
  .github/workflows/serverless-verify.yaml
  README.md
Labels: lgtm, size/XS, kind/chore, cla: yes

#722 Smart function presets defaulting
  components/operator/controllers/serverless_controller_rbac.go
  components/operator/internal/state/controller_configuration.go
  components/operator/internal/state/controller_configuration_test.go
  components/operator/internal/state/optional_dependencies.go
  components/operator/internal/state/optional_dependencies_test.go
  components/operator/internal/state/state.go
  config/operator/rbac/role.yaml
Labels: kind/feature, area/serverless, lgtm, size/L, cla: yes

#720 Improve the Serverless testing strategy doc
  .github/workflows/serverless-verify.yaml
  docs/contributor/04-10-testing-strategy.md
Labels: size/M, lgtm, area/documentation, cla: yes

#734 add grouping depandabot PRs by k8s.io
  .github/dependabot.yml
Labels: lgtm, size/XS, kind/cleanup, area/dependency, cla: yes

#736 Change on cluster to in cluster
  README.md
  components/serverless/design/glossary_proposal.md
  components/serverless/design/internal_registry_garbage_collection.md
  docs/contributor/04-10-testing-strategy.md
  docs/user/00-30-development-toolkit.md
  docs/user/technical-reference/05-20-env-variables.md
  docs/user/technical-reference/07-60-function-configuration-file.md
  docs/user/tutorials/01-110-override-runtime-image.md
  docs/user/tutorials/01-120-inject-envs.md
  docs/user/tutorials/01-140-use-secret-mounts.md
  docs/user/tutorials/01-30-manage-functions-with-kyma-cli.md
  docs/user/tutorials/01-50-sync-function-with-gitops.md
  docs/user/tutorials/01-60-set-external-registry.md
Labels: size/M, lgtm, cla: yes

#739 Extract gardener target to separate makefile
  components/operator/hack/ci/Makefile
  components/operator/hack/common/Makefile
Labels: size/M, lgtm, cla: yes

#737 Extract tools installer makefile
  components/operator/Makefile
  components/operator/hack/common/Makefile
  components/operator/hack/get_kyma_file_name.sh
  components/serverless/Makefile
  config/operator/crd/bases/operator.kyma-project.io_serverlesses.yaml
  config/operator/rbac/role.yaml
  hack/tools/Makefile
  hack/tools/get_kyma_file_name.sh
Labels: lgtm, size/L, cla: yes

#738 Extract help
  components/operator/Dockerfile.dev
  components/operator/Dockerfile.local
  components/operator/Dockerfile.release
  components/operator/Makefile
  components/operator/hack/ci/Makefile
  components/operator/hack/common/Makefile
  components/operator/hack/local/Makefile
  components/serverless/Makefile
  hack/tools/help.Makefile
  tests/gitserver/Makefile
  tests/serverless-bench/Makefile
  tests/serverless/Makefile
Labels: size/M, lgtm, cla: yes

#741 Extract gardener targets
  components/operator/hack/ci/Makefile
  hack/tools/gardener.Makefile
Labels: size/M, lgtm, cla: yes

#743 Include tools makefile in ci
  components/operator/hack/ci/Makefile
Labels: lgtm, size/XS, cla: yes

#744 Fix gardener job
  components/operator/hack/ci/Makefile
  components/operator/hack/common/Makefile
  hack/tools/gardener.Makefile
Labels: lgtm, size/XS, cla: yes

#750 merge operator dockerfiles into one dockerfile
  components/operator/Dockerfile
  components/operator/Dockerfile.dev
  components/operator/Dockerfile.release
  components/operator/Makefile
Labels: size/M, area/serverless, lgtm, kind/cleanup, cla: yes

#752 Handle /favicon.ico requests in python runtimes the same as in case of nodejs
  components/runtimes/python39/kubeless/kubeless.py
Labels: lgtm, size/XS, cla: yes

#751 Change the structure of makefiles
  .github/workflows/operator-verify.yaml
  .github/workflows/serverless-verify.yaml
  Makefile
  components/operator/Makefile
  components/operator/hack/ci/Makefile
  components/operator/hack/common/Makefile
  hack/ci/Makefile
Labels: lgtm, size/L, cla: yes

#758 Fix tests
  Makefile
  hack/ci/Makefile
Labels: size/S, lgtm, cla: yes

#759 Fix makefiles 2
  Makefile
  hack/ci/Makefile
Labels: lgtm, size/XS, cla: yes

#760 Fix
  hack/ci/Makefile
Labels: lgtm, size/XS, cla: yes

#754 remove unused operator dockerfiles
  components/operator/Dockerfile.dev
  components/operator/Dockerfile.release
Labels: lgtm, size/L, cla: yes

#761 fix
  hack/ci/Makefile
Labels: lgtm, size/XS, cla: yes

#762 Makefile refactor images replacing
  .github/workflows/create-release.yaml
  components/operator/Dockerfile
  components/operator/hack/ci/Makefile
  hack/ci/Makefile
Labels: area/serverless, size/S, lgtm, kind/cleanup, cla: yes

#763 Extract k3d makefile
  components/operator/Makefile
  components/operator/hack/common/Makefile
  components/operator/hack/local/Makefile
  components/serverless/Makefile
  hack/tools/k3d.Makefile
Labels: size/M, lgtm, cla: yes

#764 Add dev overlay to operator kustomize
  Makefile
  components/operator/Makefile
  components/operator/controllers/suite_test.go
  config/operator/base/crd/bases/operator.kyma-project.io_serverlesses.yaml
  config/operator/base/crd/kustomization.yaml
  config/operator/base/crd/kustomizeconfig.yaml
  config/operator/base/deployment/deployment.yaml
  config/operator/base/deployment/kustomization.yaml
  config/operator/base/kustomization.yaml
  config/operator/base/rbac/kustomization.yaml
  config/operator/base/rbac/role.yaml
  config/operator/base/rbac/role_binding.yaml
  config/operator/base/rbac/serverless_editor_role.yaml
  config/operator/base/rbac/serverless_viewer_role.yaml
  config/operator/base/rbac/service_account.yaml
  config/operator/base/ui-extensions/kustomization.yaml
  config/operator/base/ui-extensions/serverless/details
  config/operator/base/ui-extensions/serverless/form
  config/operator/base/ui-extensions/serverless/general
  config/operator/base/ui-extensions/serverless/kustomization.yaml
  config/operator/base/ui-extensions/serverless/list
  config/operator/dev/.gitignore
  config/operator/dev/kustomization.yaml.tpl
  config/operator/operator/kustomization.yaml
Labels: size/M, lgtm, cla: yes

#765 Makefile extract images replacing
  .github/workflows/create-release.yaml
  components/operator/Dockerfile
  components/operator/hack/ci/Makefile
  hack/tools/replace_serverless_chart_images.sh
Labels: size/M, area/serverless, lgtm, kind/cleanup, cla: yes

#766 Add local development targets
  Makefile
  components/operator/Makefile
  components/operator/hack/build_local_images.sh
  components/operator/hack/common/Makefile
  components/operator/hack/local/Makefile
  components/operator/hack/makefile-strategy.md
  components/operator/hack/makefile-strategy.png
  components/operator/hack/verify_serverless_status.sh
  components/serverless/Makefile
  hack/tools/Makefile
  hack/tools/k3d.Makefile
Labels: lgtm, size/L, cla: yes

#769 Revert "actions(deps): bump golangci/golangci-lint-action from 3 to 4"
  .github/workflows/operator-verify.yaml
  .github/workflows/serverless-verify.yaml
Labels: lgtm, size/XS, cla: yes

#767 Makefile rename
  .github/workflows/create-release.yaml
  .github/workflows/operator-verify.yaml
  .github/workflows/serverless-verify.yaml
  Makefile
  components/operator/Dockerfile
  components/operator/Makefile
  components/serverless/Makefile
  hack/Makefile
  hack/gardener.mk
  hack/get_kyma_file_name.sh
  hack/help.mk
  hack/k3d.mk
  hack/replace_serverless_chart_images.sh
  hack/tools.mk
  tests/gitserver/Makefile
  tests/serverless-bench/Makefile
  tests/serverless/Makefile
Labels: size/M, area/serverless, lgtm, kind/cleanup, cla: yes

#768 Bump k8s envtest version
  components/operator/controllers/serverless_controller_test.go
  components/operator/controllers/testhelper_test.go
  components/operator/internal/chart/install.go
  components/operator/internal/state/controller_configuration_test.go
  components/operator/internal/state/registry_test.go
  components/operator/internal/state/state_test.go
  components/operator/main.go
  components/serverless/cmd/manager/main.go
  components/serverless/cmd/webhook/main.go
  components/serverless/internal/controllers/serverless/deployment_test.go
  components/serverless/internal/controllers/serverless/function_reconcile_test.go
  components/serverless/internal/controllers/serverless/scaling_test.go
  components/serverless/internal/controllers/serverless/system_state.go
  go.mod
  go.sum
  hack/tools.mk
Labels: lgtm, size/L, cla: yes

#770 remove dependabot for GH actions
  .github/dependabot.yml
Labels: size/S, lgtm, cla: yes

#777 change extension of github workflow from yaml to yml
  .github/workflows/serverless-verify.yml
Labels: area/serverless, lgtm, size/XS, kind/cleanup, cla: yes

#778 Revert "change extension of github workflow from yaml to yml"
  .github/workflows/serverless-verify.yaml
Labels: lgtm, size/XS, cla: yes

#779 adjust PROJECT_ROOT paths
  Makefile
  hack/gardener.mk
  hack/k3d.mk
  hack/tools.mk
Labels: area/serverless, size/S, lgtm, kind/cleanup, cla: yes
