Repository kyma-project/serverless, pull requests merged in 2024-10, with the labels that each got.

#1196 Set fixed lint action version
  .github/workflows/lint.yaml
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#1195 feat: Add proper categories for CRDs
  components/operator/api/v1alpha1/serverless_types.go
  components/serverless/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/serverless/pkg/apis/serverless/v1alpha2/function_types.go
  config/operator/base/crd/bases/operator.kyma-project.io_serverlesses.yaml
  config/serverless/templates/crds.yaml
Labels: size/XS, cla: yes

#1199 normalize github script names
  .github/scripts/create-draft-release.sh
  .github/scripts/publish-release.sh
  .github/workflows/create-release.yaml
Labels: size/XS, cla: yes

#1200 Simplify release id for assets
  .github/scripts/release.sh
  .github/workflows/create-release.yaml
Labels: size/S, cla: yes

#1201 Tests and bump k8s from 1.29 to 1.30
  .github/actions/create-k3d-cluster/action.yaml
  hack/gardener.mk
Labels: lgtm, size/XS, cla: yes

#1207 Fix link checker version
  .github/workflows/markdown.yaml
Labels: size/S, cla: yes

#1210 Remove Python39
  .github/dependabot.yml
  .github/workflows/_build.yaml
  components/runtimes/python/python39/.dockerignore
  components/runtimes/python/python39/Dockerfile
  components/runtimes/python/python39/requirements.txt
  components/serverless/.golangci.yaml
  components/serverless/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/serverless/hack/controller.env
  components/serverless/internal/controllers/serverless/build_resources_test.go
  components/serverless/internal/controllers/serverless/runtime/runtime.go
  components/serverless/internal/controllers/serverless/runtime/runtime_test.go
  components/serverless/internal/controllers/serverless/utils.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_types.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_x_validation_test.go
  components/serverless/pkg/apis/serverless/v1alpha2/runtime_validation.go
  config/serverless/templates/busola-serverless-extension.yaml
  config/serverless/templates/crds.yaml
  config/serverless/templates/runtimes.yaml
  config/serverless/values.yaml
  docs/user/resources/06-10-function-cr.md
  docs/user/technical-reference/05-20-env-variables.md
  docs/user/technical-reference/07-60-function-configuration-file.md
  docs/user/technical-reference/07-70-function-specification.md
  go.sum
  hack/docker-compose.yaml
  sec-scanners-config.yaml
  tests/serverless-bench/fixtures/functions/python39-l.yaml
  tests/serverless-bench/fixtures/functions/python39-m.yaml
  tests/serverless-bench/fixtures/functions/python39-s.yaml
  tests/serverless-bench/fixtures/functions/python39-xl.yaml
  tests/serverless-bench/run-benchmarks.sh
  tests/serverless/internal/testsuite/api_gateway.go
  tests/serverless/internal/testsuite/cloud_events.go
  tests/serverless/internal/testsuite/light_runtimes.go
  tests/serverless/internal/testsuite/tracing.go
Labels: lgtm, size/L, cla: yes

#1213 Remove Nodejs18
  .github/dependabot.yml
  .github/workflows/_build.yaml
  components/runtimes/nodejs/nodejs18/Dockerfile
  components/runtimes/nodejs/nodejs18/package.json
  components/serverless/.golangci.yaml
  components/serverless/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/serverless/internal/controllers/serverless/build_resources_test.go
  components/serverless/internal/controllers/serverless/runtime/runtime.go
  components/serverless/internal/controllers/serverless/runtime/runtime_test.go
  components/serverless/internal/controllers/serverless/utils.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_types.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_x_validation_test.go
  components/serverless/pkg/apis/serverless/v1alpha2/runtime_validation.go
  config/serverless/templates/busola-serverless-extension.yaml
  config/serverless/templates/crds.yaml
  config/serverless/templates/runtimes.yaml
  config/serverless/values.yaml
  docs/user/resources/06-10-function-cr.md
  docs/user/technical-reference/05-20-env-variables.md
  docs/user/technical-reference/07-60-function-configuration-file.md
  docs/user/technical-reference/07-70-function-specification.md
  hack/docker-compose.yaml
  sec-scanners-config.yaml
  tests/serverless-bench/fixtures/functions/nodejs18-l.yaml
  tests/serverless-bench/fixtures/functions/nodejs18-m.yaml
  tests/serverless-bench/fixtures/functions/nodejs18-s.yaml
  tests/serverless-bench/fixtures/functions/nodejs18-xl.yaml
  tests/serverless-bench/fixtures/functions/nodejs18-xs.yaml
  tests/serverless-bench/run-benchmarks.sh
  tests/serverless/internal/testsuite/api_gateway.go
  tests/serverless/internal/testsuite/cloud_events.go
  tests/serverless/internal/testsuite/light_runtimes.go
  tests/serverless/internal/testsuite/tracing.go
Labels: lgtm, size/L, cla: yes

#1220 Fix nodejs18 references
  tests/serverless/internal/testsuite/hana_client.go
Labels: lgtm, size/XS, cla: yes

#1219 add nodejs22 image
  .github/dependabot.yml
  .github/workflows/_build.yaml
  components/runtimes/nodejs/nodejs22/Dockerfile
  components/runtimes/nodejs/nodejs22/package.json
  sec-scanners-config.yaml
Labels: lgtm, size/L, cla: yes

#1222 Add image syncer job
  .github/workflows/sync-external-images.yaml
Labels: size/S, cla: yes

#1223 Add image syncer config
  external-images.yaml
Labels: lgtm, size/XS, cla: yes

#1231 Update current nodejs version in docs
  docs/user/technical-reference/07-10-sample-functions.md
Labels: size/XS, cla: yes

#1235 Prevent requeueing after 1s when the validation failed
  components/serverless/internal/controllers/serverless/validation.go
Labels: size/XS, cla: yes

#1229 Add deprecation notices
  components/serverless/.golangci.yaml
  components/serverless/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/serverless/design/scaling_functions.md
  components/serverless/pkg/apis/serverless/v1alpha2/function_types.go
  config/serverless/templates/crds.yaml
  docs/user/resources/06-10-function-cr.md
Labels: size/M, lgtm, cla: yes

#1230 Add deprecation notices to operator
  components/operator/.golangci.yaml
  components/operator/api/v1alpha1/serverless_types.go
  config/operator/base/crd/bases/operator.kyma-project.io_serverlesses.yaml
  docs/user/00-20-configure-serverless.md
  docs/user/resources/06-20-serverless-cr.md
Labels: size/M, lgtm, cla: yes
