Repository kyma-project/serverless, pull requests merged in 2024-11, with the labels that each got.

#1248 Remove Python version from the runtime header
  docs/user/technical-reference/07-10-sample-functions.md
Labels: size/XS, cla: yes

#1250 limit caching secrets by label
  components/serverless/cmd/manager/main.go
Labels: lgtm, size/XS, cla: yes

#1254 Bump synced alpine image
  external-images.yaml
Labels: size/XS, cla: yes

#1270 Run integration tests with k8s v1.31
  .github/actions/create-k3d-cluster/action.yaml
  hack/gardener.mk
Labels: lgtm, size/XS, cla: yes

#1266 Bump Go dependencies
  components/operator/api/v1alpha1/serverless_types.go
  components/operator/internal/tracing/watcher.go
  components/serverless/cmd/manager/main.go
  components/serverless/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/serverless/config/rbac/role.yaml
  components/serverless/internal/controllers/serverless/function_reconcile.go
  components/serverless/internal/logging/tracing/helper_test.go
  components/serverless/internal/webhook/defaulting_webhook.go
  components/serverless/internal/webhook/resources/resources.go
  components/serverless/internal/webhook/validating_webhook.go
  components/serverless/internal/webhook/validating_webhook_test.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_x_validation_test.go
  config/operator/base/crd/bases/operator.kyma-project.io_serverlesses.yaml
  config/operator/base/rbac/role.yaml
  config/serverless/templates/crds.yaml
  go.mod
  go.sum
  hack/tools.mk
Labels: size/XL, cla: yes

#1271 Add libgit to release workflow
  .github/workflows/create-release.yaml
Labels: lgtm, size/XS, cla: yes

#1272 Add libgit to release workflow (#1271)
  .github/workflows/create-release.yaml
Labels: lgtm, size/XS, cla: yes
