Repository kyma-project/serverless, pull requests merged in 2024-08, with the labels that each got.

#1119 Limit Python images bump to patch version
  .github/dependabot.yml
Labels: lgtm, size/XS, cla: yes

#1120 Fix the `serverless-operator` image name
  .github/workflows/create-release.yaml
Labels: kind/bug, lgtm, size/XS, area/ci, cla: yes

#1123 fix: adjust function form to handle the permissions model
  config/serverless/templates/busola-serverless-extension.yaml
Labels: size/S, lgtm, cla: yes
