Repository kyma-project/serverless, pull requests merged in 2024-12, with the labels that each got.

#1278 use tf actions from external repo
  .github/actions/create-sap-btp-kyma/action.yaml
  .github/actions/create-sap-btp-kyma/main.tf
  .github/actions/create-sap-btp-kyma/variables.tf
  .github/actions/force-delete-sap-btp-subaccount/action.yaml
  .github/actions/setup-btp/action.yaml
  .github/workflows/_integration-tests.yaml
Labels: lgtm, size/L, cla: yes

#1279 Bump tf actions
  .github/workflows/_integration-tests.yaml
Labels: lgtm, size/XS, cla: yes

#1280 Get rid of flaky gardener test
  .github/workflows/_integration-tests.yaml
  docs/contributor/04-10-testing-strategy.md
  hack/Makefile
  hack/gardener.mk
  hack/provision_gardener.sh
  hack/shoot_template.yaml
Labels: lgtm, size/L, cla: yes

#1281 Bump base images
  external-images.yaml
Labels: size/S, cla: yes

#1252 fix nodejs22 image
  .github/dependabot.yml
  components/runtimes/nodejs/nodejs20/Dockerfile
  components/runtimes/nodejs/nodejs22/Dockerfile
Labels: size/M, cla: yes

#1305 Run generate on buildless-serverless
  components/buildless-serverless/api/v1alpha2/zz_generated.deepcopy.go
Labels: size/XS, cla: yes

#1304 bump base go image
  external-images.yaml
Labels: lgtm, size/XS, cla: yes

#1303 replace buildless base image
  .github/dependabot.yml
  components/buildless-serverless/Dockerfile
Labels: size/S, lgtm, cla: yes

#1306 BUmp base go images
  components/operator/Dockerfile
  components/serverless/deploy/jobinit/Dockerfile
  components/serverless/deploy/manager/Dockerfile
  components/serverless/deploy/webhook/Dockerfile
Labels: size/XS, cla: yes

#1307 fix images versions inside operator image
  .github/workflows/_build.yaml
  .github/workflows/pull.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
Labels: size/M, cla: yes

#1308 fix broken pull and push gh workflows
  .github/workflows/pull.yaml
  .github/workflows/push.yaml
Labels: lgtm, size/XS, cla: yes

#1310 fix broken pull and push gh workflows (part 2)
  .github/workflows/_build.yaml
Labels: lgtm, size/XS, cla: yes

#1216 add nodejs22 support
  components/serverless/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/serverless/design/extend_function_spec_proposal.md
  components/serverless/internal/controllers/serverless/build_resources_test.go
  components/serverless/internal/controllers/serverless/fixtures_test.go
  components/serverless/internal/controllers/serverless/function_reconcile_gitops_test.go
  components/serverless/internal/controllers/serverless/function_reconcile_test.go
  components/serverless/internal/controllers/serverless/gitops_test.go
  components/serverless/internal/controllers/serverless/runtime/nodejs_test.go
  components/serverless/internal/controllers/serverless/runtime/runtime.go
  components/serverless/internal/controllers/serverless/runtime/runtime_test.go
  components/serverless/internal/controllers/serverless/utils.go
  components/serverless/internal/controllers/serverless/utils_test.go
  components/serverless/internal/controllers/serverless/validation_test.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_types.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_x_validation_test.go
  components/serverless/pkg/apis/serverless/v1alpha2/runtime_validation.go
  config/serverless/templates/busola-serverless-extension.yaml
  config/serverless/templates/crds.yaml
  config/serverless/templates/runtimes.yaml
  config/serverless/values.yaml
  tests/serverless-bench/fixtures/functions/nodejs22-l.yaml
  tests/serverless-bench/fixtures/functions/nodejs22-m.yaml
  tests/serverless-bench/fixtures/functions/nodejs22-s.yaml
  tests/serverless-bench/fixtures/functions/nodejs22-xl.yaml
  tests/serverless-bench/fixtures/functions/nodejs22-xs.yaml
  tests/serverless-bench/run-benchmarks.sh
  tests/serverless/internal/testsuite/api_gateway.go
  tests/serverless/internal/testsuite/cloud_events.go
  tests/serverless/internal/testsuite/gitauth.go
  tests/serverless/internal/testsuite/gitops.go
  tests/serverless/internal/testsuite/hana_client.go
  tests/serverless/internal/testsuite/light_runtimes.go
  tests/serverless/internal/testsuite/tracing.go
Labels: size/L, cla: yes

#1299 enabling buildless-serverless to be run by the operator
  components/buildless-serverless/Dockerfile
  components/buildless-serverless/internal/controller/state/build_deployment.go
  config/buildless-serverless/templates/deployment.yaml
  config/buildless-serverless/values.yaml
  config/operator/base/deployment/deployment.yaml
Labels: size/M, lgtm, cla: yes

#1311 Fix currentSpan handling
  components/runtimes/nodejs/server.mjs
Labels: lgtm, size/XS, cla: yes

#1313 fix make manifests for buildless serverless
  components/buildless-serverless/Makefile
Labels: lgtm, size/XS, cla: yes

#1314 fix make manifests for buildless serverless (2)
  components/buildless-serverless/Makefile
Labels: size/XS, cla: yes

#1312 add service to buildless-serverless
  components/buildless-serverless/api/v1alpha2/function_types.go
  components/buildless-serverless/config/rbac/role.yaml
  components/buildless-serverless/internal/controller/function_controller.go
  components/buildless-serverless/internal/controller/state/build_deployment.go
  components/buildless-serverless/internal/controller/state/build_service.go
  components/buildless-serverless/internal/controller/state/handle_deployment.go
  components/buildless-serverless/internal/controller/state/handle_service.go
  components/buildless-serverless/internal/controller/state/utils.go
  config/buildless-serverless/templates/cluster-role.yaml
Labels: lgtm, size/L, cla: yes

#1321 Fix busola rendering problem
  config/serverless/templates/busola-serverless-extension.yaml
Labels: lgtm, size/XS, cla: yes

#1322 Fix busola rendering problem (#1321)
  config/serverless/templates/busola-serverless-extension.yaml
Labels: lgtm, size/XS, cla: yes

#1327 Validate spec.runtime
  components/buildless-serverless/api/v1alpha2/function_types.go
  components/buildless-serverless/internal/controller/state/validate_function.go
  components/serverless/internal/controllers/serverless/validation.go
  components/serverless/internal/controllers/serverless/validation_test.go
  components/serverless/pkg/apis/serverless/v1alpha2/runtime_validation.go
Labels: size/M, lgtm, cla: yes

#1329 Show warning badge (not error) when running condition is true
  config/serverless/templates/busola-serverless-extension.yaml
Labels: lgtm, size/XS, cla: yes

#1330 Validate runtimes fix 1.6
  components/buildless-serverless/api/v1alpha2/function_types.go
  components/buildless-serverless/internal/controller/state/validate_function.go
  components/serverless/internal/controllers/serverless/validation.go
  components/serverless/internal/controllers/serverless/validation_test.go
  components/serverless/pkg/apis/serverless/v1alpha2/runtime_validation.go
  config/serverless/templates/busola-serverless-extension.yaml
Labels: size/M, lgtm, cla: yes

#1331 fix image version bump during release
  .github/workflows/_build.yaml
Labels: lgtm, size/XS, cla: yes

#1332 fix image version bump during release - double quotes are not allowed
  .github/workflows/_build.yaml
Labels: lgtm, size/XS, cla: yes

#1333 fix image version bump during release - fix input.tag
  .github/workflows/_build.yaml
Labels: lgtm, size/XS, cla: yes

#1328 Add handling package registry
  components/buildless-serverless/internal/config/function_config.go
  components/buildless-serverless/internal/controller/state/build_deployment.go
  config/buildless-serverless/templates/deployment.yaml
  config/buildless-serverless/values.yaml
Labels: size/M, cla: yes

#1341 Fix tag resolving in release process
  .github/workflows/create-release-on-tag.yaml
Labels: kind/bug, lgtm, size/XS, area/ci, cla: yes

#1342 Tag release with custom token
  .github/workflows/create-release.yaml
Labels: kind/bug, size/XS, area/ci

#1344 Fix release 1.6
  .github/workflows/create-release-on-tag.yaml
  .github/workflows/create-release.yaml
Labels: lgtm, size/L, cla: yes

#1346 Support adding any annotation to functions spec annotations
  components/serverless/internal/controllers/serverless/function_reconcile_test.go
  components/serverless/internal/controllers/serverless/system_state.go
Labels: kind/bug, area/serverless, size/S, lgtm, cla: yes

#1347 Include busola config in buildless variant
  config/buildless-serverless/templates/busola-serverless-extension.yaml
Labels: lgtm, size/XL, cla: yes

#1343 buildless project refactor
  components/buildless-serverless/internal/controller/fsm/fsm.go
  components/buildless-serverless/internal/controller/function_controller.go
  components/buildless-serverless/internal/controller/resources/deployment.go
  components/buildless-serverless/internal/controller/resources/service.go
  components/buildless-serverless/internal/controller/state/adjust_status.go
  components/buildless-serverless/internal/controller/state/deployment_status.go
  components/buildless-serverless/internal/controller/state/fsm.go
  components/buildless-serverless/internal/controller/state/handle_deployment.go
  components/buildless-serverless/internal/controller/state/handle_service.go
  components/buildless-serverless/internal/controller/state/state.go
  components/buildless-serverless/internal/controller/state/validate_function.go
Labels: lgtm, size/XL, cla: yes

#1353 Cherry-Pick: Support adding any annotation to functions spec annotations
  components/serverless/internal/controllers/serverless/function_reconcile_test.go
  components/serverless/internal/controllers/serverless/system_state.go
Labels: area/serverless, size/S, lgtm, kind/chore, cla: yes
