Repository kyma-project/serverless, pull requests merged in 2024-05, with the labels that each got.

#946 Show warning in UI when internal docker registry is configured
  config/operator/base/ui-extensions/serverless/details
  config/operator/base/ui-extensions/serverless/form
  config/operator/base/ui-extensions/serverless/kustomization.yaml
  config/operator/base/ui-extensions/serverless/translations
Labels: lgtm, size/XS, cla: yes

#954 chore: Update dependencies
  components/runtimes/nodejs/nodejs18/package.json
  components/runtimes/nodejs/nodejs20/package.json
  components/runtimes/python/python312/requirements.txt
  components/runtimes/python/python39/requirements.txt
  go.mod
  go.sum
Labels: lgtm, size/L, area/dependency, kind/chore, cla: yes

#956 Move setup go to separate action
  .github/actions/setup-go/action.yaml
  .github/workflows/create-release.yaml
  .github/workflows/operator-verify.yaml
  .github/workflows/serverless-verify.yaml
Labels: kind/feature, size/M, area/serverless, lgtm, kind/cleanup, cla: yes

#957 Move create single cluster to seperate action
  .github/actions/create-single-cluster/action.yaml
  .github/workflows/operator-verify.yaml
  .github/workflows/serverless-verify.yaml
Labels: kind/feature, size/M, area/serverless, lgtm, kind/cleanup, cla: yes

#958 Bump rc-tag
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#967 Add sample function using ESM node syntax
  docs/user/technical-reference/07-10-sample-functions.md
Labels: documentation, size/M, lgtm, cla: yes

#968 Add Hint about SSH URL when defining git functions from provate repos
  docs/user/tutorials/01-11-create-git-function.md
Labels: kind/bug, documentation, size/S, lgtm, cla: yes

#970 Adjust testing strategy after refactor of gh tests
  docs/contributor/04-10-testing-strategy.md
Labels: kind/feature, size/M, area/serverless, lgtm, kind/cleanup, cla: yes

#965 Allow for mjs imports in nodejs functions
  components/runtimes/nodejs/nodejs18/Dockerfile
  components/runtimes/nodejs/nodejs18/package.json
  components/runtimes/nodejs/nodejs20/Dockerfile
  components/runtimes/nodejs/nodejs20/package.json
  components/runtimes/nodejs/server.mjs
Labels: kind/feature, size/M, lgtm, cla: yes

#959 Create the `rebase` action
  .github/actions/rebase/action.yaml
  .github/workflows/gitleaks.yaml
  .github/workflows/integration-tests-pull.yaml
  .github/workflows/lint.yaml
  .github/workflows/markdown.yaml
  .github/workflows/unit-tests.yaml
Labels: size/M, lgtm, area/ci, kind/chore, cla: yes

#972 Cover case when the `main` branch exists
  .github/actions/rebase/action.yaml
Labels: kind/bug, area/serverless, lgtm, size/XS, cla: yes

#966 Add inline hint how to switch to mjs syntax
  config/serverless/templates/busola-serverless-extension.yaml
Labels: size/M, lgtm, cla: yes

#899 Cleanup unused configuration fields
  components/operator/api/v1alpha1/serverless_types.go
  components/operator/internal/chart/flags.go
  components/operator/internal/chart/flags_test.go
  components/operator/internal/state/controller_configuration.go
  components/operator/internal/state/controller_configuration_test.go
  config/operator/base/crd/bases/operator.kyma-project.io_serverlesses.yaml
  config/operator/base/ui-extensions/serverless/details
  docs/user/00-20-configure-serverless.md
  docs/user/resources/06-20-serverless-cr.md
Labels: size/M, lgtm, kind/cleanup, cla: yes

#973 Fix bug when updating main
  .github/actions/rebase/action.yaml
Labels: kind/bug, area/serverless, lgtm, size/XS, cla: yes

#960 Add architecture diagram
  .gitignore
  README.md
  architecture.svg
  components/operator/Makefile
Labels: size/S, lgtm, cla: yes

#974 small improvements in gh actions
  .github/actions/create-k3d-cluster/action.yaml
  .github/workflows/integration-tests-pull.yaml
  .github/workflows/integration-tests-push.yaml
  .github/workflows/upgrade-tests.yaml
Labels: area/serverless, size/S, lgtm, kind/cleanup, area/ci, cla: yes

#975 adjust testing strategy
  docs/contributor/04-10-testing-strategy.md
Labels: lgtm, size/XS, kind/cleanup, area/documentation, cla: yes

#565 Improve ifology
  components/serverless/internal/controllers/serverless/utils.go
  components/serverless/internal/testenv/testenv.go
Labels: size/M, lgtm, cla: yes

#962 extract version of go to input in action setup-go
  .github/actions/setup-go/action.yaml
Labels: kind/feature, area/serverless, lgtm, size/XS, cla: yes

#984 Add cloud events contract tests diagram
  tests/serverless/README.md
  tests/serverless/eventing_flow.svg
  tests/serverless/internal/assertion/cloud_events.go
Labels: size/S, lgtm, cla: yes

#988 Unify CR description in Kyma dashboard
  config/operator/base/ui-extensions/serverless/general
Labels: documentation, lgtm, size/XS, cla: yes

#999 Fix gitserver version
  tests/serverless/internal/config.go
Labels: size/S, lgtm, kind/failing-test, area/tests, cla: yes

#990 Change default build job preset to normal
  components/operator/internal/state/controller_configuration.go
  components/operator/internal/state/controller_configuration_test.go
  components/serverless/hack/controller.env
  config/serverless/values.yaml
  docs/user/technical-reference/07-80-available-presets.md
  tests/operator/main.go
Labels: size/M, lgtm, cla: yes

#994 Include build configuration in busola config
  config/operator/base/ui-extensions/serverless/details
  config/operator/base/ui-extensions/serverless/form
Labels: kind/feature, size/M, lgtm, cla: yes

#1000 Deprecate kyma provision gardener
  hack/gardener.mk
  hack/provision_gardener.sh
  hack/shoot_template.yaml
Labels: size/M, lgtm, cla: yes

#1001 Static apache2 version in the gitserver image
  tests/gitserver/Dockerfile
Labels: lgtm, size/XS, kind/failing-test, area/tests, cla: yes

#1002 Fix Gardener provisioning
  hack/gardener.mk
Labels: lgtm, size/XS, cla: yes

#1004 Update the `rc-tag` in the `sec-scanners-config.yaml`
  sec-scanners-config.yaml
Labels: area/serverless, lgtm, size/XS, kind/chore, cla: yes
