Repository kyma-project/serverless, pull requests merged in 2024-07, with the labels that each got.

#1041 Serverless operator build job
  .github/workflows/serverless-operator-build.yaml
Labels: size/S, lgtm, cla: yes

#1043 Use GA build in integration pull tests
  .github/workflows/integration-tests-pull.yaml
  .github/workflows/serverless-operator-build.yaml
Labels: size/S, lgtm, cla: yes

#1037 Modify GH issue template for New Features
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: size/M, lgtm, area/documentation, cla: yes

#1042 Add pull serverless runtimes build
  .github/workflows/serverless-build-runtimes.yaml
Labels: size/M, lgtm, cla: yes

#1045 Add pull gitserver build workflow
  .github/workflows/gitserver-build-pull.yaml
Labels: size/S, lgtm, cla: yes

#1048 Add serverless operator build push
  .github/workflows/serverless-operator-build-pull.yaml
  .github/workflows/serverless-operator-build-push.yaml
Labels: size/M, lgtm, cla: yes

#1055 Fix operator build push job
  .github/workflows/serverless-operator-build-push.yaml
Labels: lgtm, size/XS, cla: yes

#1058 Add serverless runtimes build (push)
  .github/workflows/serverless-build-runtime-push.yaml
  .github/workflows/serverless-build-runtimes-pull.yaml
  .github/workflows/serverless-operator-build-push.yaml
Labels: size/M, lgtm, cla: yes

#1059 Add serverless build (push)
  .github/workflows/serverless-build-push.yaml
Labels: size/M, lgtm, cla: yes

#1060 Add serverless release build
  .github/workflows/release-serverless-build.yaml
Labels: size/M, lgtm, cla: yes

#1066 Bump nodejs base image
  components/runtimes/nodejs/nodejs18/Dockerfile
  components/runtimes/nodejs/nodejs20/Dockerfile
Labels: size/S, lgtm, cla: yes

#1065 Move GA builds to -pull, -push and -release files
  .github/workflows/build-pull.yaml
  .github/workflows/build-push.yaml
  .github/workflows/build-release.yaml
  .github/workflows/gitserver-build-pull.yaml
  .github/workflows/integration-tests-pull.yaml
  .github/workflows/serverless-build-pull.yaml
  .github/workflows/serverless-build-push.yaml
  .github/workflows/serverless-build-runtimes-pull.yaml
  .github/workflows/serverless-operator-build-pull.yaml
  .github/workflows/serverless-operator-build-push.yaml
Labels: lgtm, size/L, cla: yes

#1071 Remove java runtime
  .github/workflows/build-pull.yaml
  .github/workflows/build-push-release.yaml
  components/runtimes/java17/.gitignore
  components/runtimes/java17/Dockerfile-jvm-function-local
  components/runtimes/java17/Dockerfile-jvm-function.tpl
  components/runtimes/java17/Dockerfile-jvm-runtime
  components/runtimes/java17/Makefile
  components/runtimes/java17/examples/hello-world/.Dockerignore
  components/runtimes/java17/examples/hello-world/.gitignore
  components/runtimes/java17/examples/hello-world/pom.xml
  components/runtimes/java17/examples/hello-world/src/main/java/io/project/kyma/serverless/handler/Handler.java
  components/runtimes/java17/pom.xml
  components/runtimes/java17/resources/.gitignore
  components/runtimes/java17/resources/cm.yaml.tpl
  components/runtimes/java17/resources/generate-cm.py
  components/runtimes/java17/resources/generate-dockerfile.py
  components/runtimes/java17/serverless-java-sdk/Makefile
  components/runtimes/java17/serverless-java-sdk/pom.xml
  components/runtimes/java17/serverless-java-sdk/src/main/java/io/project/kyma/serverless/sdk/CloudEvent.java
  components/runtimes/java17/serverless-java-sdk/src/main/java/io/project/kyma/serverless/sdk/Function.java
  components/runtimes/java17/serverless-java-sdk/src/main/java/io/project/kyma/serverless/sdk/ResponseCloudEvent.java
  components/runtimes/java17/src/main/java/io/project/kyma/serverless/Config.java
  components/runtimes/java17/src/main/java/io/project/kyma/serverless/JerseyServer.java
  components/runtimes/java17/src/main/java/io/project/kyma/serverless/Main.java
  components/runtimes/java17/src/main/java/io/project/kyma/serverless/handler/Handler.java
  components/runtimes/java17/src/main/test/io/project/kyma/serverless/MainTest.java
Labels: area/serverless, lgtm, kind/cleanup, size/XL, cla: yes

#1068 Use synced images
  components/operator/Dockerfile
  components/runtimes/nodejs/nodejs18/Dockerfile
  components/runtimes/nodejs/nodejs20/Dockerfile
  components/runtimes/python/python312/Dockerfile
  components/runtimes/python/python39/Dockerfile
  components/serverless/deploy/jobinit/Dockerfile
  components/serverless/deploy/manager/Dockerfile
  components/serverless/deploy/webhook/Dockerfile
  config/serverless/charts/docker-registry/templates/deployment.yaml
  config/serverless/values.yaml
  sec-scanners-config.yaml
  tests/gitserver/Dockerfile
Labels: size/M, area/serverless, lgtm, kind/chore, cla: yes

#1074 Hana client contract test hardening
  tests/serverless/internal/resources/runtimes/nodejs.go
  tests/serverless/internal/testsuite/hana_client.go
Labels: size/S, lgtm, kind/failing-test, cla: yes

#1078 Always run most important jobs
  .github/workflows/images-verify.yaml
  .github/workflows/integration-tests-pull.yaml
  .github/workflows/lint.yaml
  .github/workflows/unit-tests.yaml
Labels: size/S, lgtm, area/ci, kind/chore, cla: yes

#1079 Init common pull workflow
  .github/workflows/build-pull.yaml
  .github/workflows/build-push-release.yaml
  .github/workflows/gitleaks.yaml
  .github/workflows/images-verify.yaml
  .github/workflows/integration-tests-pull.yaml
  .github/workflows/integration-tests-push.yaml
  .github/workflows/lint.yaml
  .github/workflows/markdown.yaml
  .github/workflows/pull.yaml
  .github/workflows/unit-tests.yaml
  .github/workflows/upgrade-tests.yaml
Labels: size/S, lgtm, kind/cleanup, area/ci, cla: yes

#1080 Add ordered workflows for each event
  .github/workflows/markdown.yaml
  .github/workflows/pull.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
Labels: size/M, lgtm, kind/cleanup, area/ci, cla: yes

#1062 Update the tutorial Expose a Function with an APIRule
  docs/user/tutorials/01-20-expose-function.md
Labels: lgtm, size/L, cla: yes

#1082 merge gh workflows
  .github/workflows/_build-push-release.yaml
  .github/workflows/_build.yaml
  .github/workflows/_integration-tests-pull.yaml
  .github/workflows/_integration-tests.yaml
  .github/workflows/pull.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
Labels: area/serverless, lgtm, size/L, kind/cleanup, area/ci, cla: yes

#1084 Revert "merge gh workflows (#1082)"
  .github/workflows/_build-pull.yaml
  .github/workflows/_build-push-release.yaml
  .github/workflows/_integration-tests-pull.yaml
  .github/workflows/_integration-tests-push.yaml
  .github/workflows/pull.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
Labels: area/serverless, lgtm, size/L, kind/cleanup, area/ci, cla: yes

#1085 Fix broken links
  docs/contributor/04-10-testing-strategy.md
Labels: size/S, lgtm, cla: yes

#1087 merge build gh workflows
  .github/workflows/_build-push-release.yaml
  .github/workflows/_build.yaml
  .github/workflows/_integration-tests.yaml
  .github/workflows/pull.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
Labels: size/M, area/serverless, lgtm, kind/cleanup, area/ci, cla: yes

#1091 allow paralell run for unit-test and build gh workflows
  .github/workflows/_build.yaml
  .github/workflows/pull.yaml
Labels: area/serverless, size/S, lgtm, kind/cleanup, area/ci, cla: yes

#1093 [docs] Fix broken links
  docs/contributor/04-10-testing-strategy.md
Labels: documentation, size/S, lgtm, area/documentation, cla: yes

#1073 Improve the docu issue template
  .github/ISSUE_TEMPLATE/documentation-improvement.md
Labels: size/M, lgtm, area/documentation, cla: yes

#1104 Pass kubeconfig as arg
  hack/provision_gardener.sh
Labels: lgtm, size/XS, kind/failing-test, area/ci, cla: yes

#1105 Print how many line number of a SA file
  .github/workflows/_integration-tests.yaml
Labels: size/S, lgtm, kind/failing-test, area/ci, cla: yes

#1106 Fix SA path
  .github/workflows/_integration-tests.yaml
Labels: lgtm, size/XS, kind/failing-test, area/ci, cla: yes

#1092 adjust test jobs' names in testing strategy
  docs/contributor/04-10-testing-strategy.md
Labels: area/serverless, size/S, lgtm, kind/cleanup, area/ci, cla: yes

#1109 Pass secrets to called integration and upgrade workflows
  .github/workflows/pull.yaml
  .github/workflows/push.yaml
Labels: lgtm, size/XS, kind/failing-test, area/ci, cla: yes

#1113 Fail workflow when provisioning is not succeed
  hack/provision_gardener.sh
Labels: lgtm, size/XS, kind/failing-test, area/ci, cla: yes

#1111 Bump alpine
  components/runtimes/nodejs/nodejs18/Dockerfile
  components/runtimes/nodejs/nodejs20/Dockerfile
  components/serverless/deploy/webhook/Dockerfile
Labels: size/S, lgtm, cla: yes

#1114 Change enable and disable to add and delete in the Serverless repo
  docs/user/README.md
  docs/user/tutorials/01-130-use-external-scalers.md
Labels: lgtm, size/XS, cla: yes

#1112 Add missing images to dependabot
  .github/dependabot.yml
Labels: size/M, lgtm, cla: yes

#1115 Bump registry image
  config/serverless/values.yaml
Labels: lgtm, size/XS, cla: yes

#1116 Bump registry image in sec-config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1118 Cherry pick release rework from the docker-registry repo
  .github/scripts/verify-serverless-jobs-status.sh
  .github/workflows/_build.yaml
  .github/workflows/_integration-tests.yaml
  .github/workflows/create-release.yaml
Labels: lgtm, size/L, kind/cleanup, area/ci, kind/chore, cla: yes
