Repository kyma-project/serverless, pull requests merged in 2024-04, with the labels that each got.

#846 Bump Sec Scanner Config
  sec-scanners-config.yaml
Labels: area/serverless, lgtm, size/XS, kind/chore, cla: yes

#841 Remove not used env
  components/operator/controllers/serverless_controller.go
  components/operator/controllers/suite_test.go
  components/operator/internal/config/config.go
  components/operator/internal/state/fsm.go
  components/operator/internal/state/new.go
  components/operator/main.go
  config/operator/base/deployment/deployment.yaml
Labels: size/S, lgtm, cla: yes

#851 Merge main to 1.4
  components/operator/controllers/serverless_controller.go
  components/operator/controllers/suite_test.go
  components/operator/internal/config/config.go
  components/operator/internal/state/fsm.go
  components/operator/internal/state/new.go
  components/operator/main.go
  config/operator/base/deployment/deployment.yaml
  sec-scanners-config.yaml
Labels: size/S, lgtm, cla: yes

#853 Cleanup function webhook from helm chart values
  config/serverless/values.yaml
Labels: lgtm, size/XS, cla: yes

#854 Upgrade the helm dependency version
  components/operator/internal/chart/client_getter.go
  components/operator/internal/chart/pvc_test.go
  go.mod
  go.sum
Labels: area/serverless, lgtm, kind/cleanup, size/XXL, cla: yes

#855 Cherry-pick: Upgrade the helm dependency version (#854)
  components/operator/internal/chart/client_getter.go
  components/operator/internal/chart/pvc_test.go
  go.mod
  go.sum
Labels: lgtm, size/XXL, cla: yes

#845 Improve makefiles
  Makefile
  README.md
  components/operator/Makefile
  components/operator/README.md
  components/serverless/Makefile
  components/serverless/README.md
  hack/makefile-strategy.md
Labels: lgtm, size/L, cla: yes

#870 Upgrade project go version
  .github/workflows/operator-verify.yaml
  .github/workflows/serverless-verify.yaml
  components/operator/Dockerfile
  components/operator/internal/state/state_test.go
  components/serverless/deploy/webhook/Dockerfile
  go.mod
Labels: area/serverless, lgtm, size/L, cla: yes

#871 Serverless Promote Release Workflow
  .github/workflows/promote-to-release-channel.yaml
  hack/Makefile
  module-config-template.yaml
Labels: kind/feature, lgtm, size/L, cla: yes

#872 chore: Bump nodejs runtimes base images
  components/runtimes/nodejs/nodejs18/Dockerfile
  components/runtimes/nodejs/nodejs20/Dockerfile
Labels: lgtm, size/XS, cla: yes

#868 Disable custom user docker registry configuration that bypasses serverless CR spec
  components/operator/internal/registry/secret.go
  components/operator/internal/registry/secret_test.go
  components/operator/internal/registry/test_helpers.go
  components/operator/internal/state/registry.go
  components/operator/internal/state/registry_test.go
  components/serverless/internal/controllers/serverless/config.go
  components/serverless/internal/controllers/serverless/function_reconcile.go
  components/serverless/internal/controllers/serverless/function_reconcile_test.go
Labels: lgtm, size/L, kind/cleanup, cla: yes

#873 Enable gitleaks check
  .github/workflows/pull-gitleaks.yaml
Labels: size/S, lgtm, area/ci, cla: yes

#877 Add missing space
  .github/scripts/release.sh
Labels: lgtm, size/XS, kind/cleanup, area/ci, cla: yes

#878 Update deprecated Port fields
  components/operator/main.go
  components/serverless/cmd/manager/main.go
Labels: size/S, lgtm, cla: yes

#879 Use right go version in release action
  .github/workflows/create-release.yaml
Labels: kind/bug, lgtm, size/XS, area/ci, cla: yes

#882 Update Reuse repo link
  .reuse/dep5
Labels: lgtm, size/XS, cla: yes

#883 Use correct env for GH tools bot
  .github/workflows/promote-to-release-channel.yaml
Labels: lgtm, size/XS, cla: yes

#884 Update links used in readme.md for Reuse tool
  README.md
Labels: size/S, lgtm, cla: yes

#880 bump docker
  go.mod
  go.sum
Labels: size/S, lgtm, cla: yes

#875 Adjust busola extension to have dependancies as string
  config/serverless/templates/busola-serverless-extension.yaml
Labels: lgtm, size/XS, cla: yes

#885 Add debug log when serverless status is updating
  components/operator/internal/state/update_status.go
Labels: kind/feature, area/serverless, lgtm, size/XS, cla: yes

#890 Add required env to GH Cli command
  .github/workflows/promote-to-release-channel.yaml
Labels: lgtm, size/XS, cla: yes

#891 Fix typo in promote release workflow
  .github/workflows/promote-to-release-channel.yaml
Labels: lgtm, size/XS, cla: yes

#892 Add Config to the promote workflow
  .github/workflows/promote-to-release-channel.yaml
Labels: lgtm, size/XS, cla: yes

#894 Add Env to promote workflow as workaround
  .github/workflows/promote-to-release-channel.yaml
Labels: lgtm, size/XS, cla: yes

#896 Implement integration-test scaffold
  go.mod
  go.sum
  tests/operator/Makefile
  tests/operator/logger/logger.go
  tests/operator/main.go
  tests/operator/utils/client.go
  tests/operator/utils/pointer.go
  tests/operator/utils/types.go
Labels: area/serverless, lgtm, size/L, kind/missing-test, cla: yes

#897 Create namespace for integration-test
  tests/operator/main.go
  tests/operator/namespace/create.go
  tests/operator/namespace/delete.go
Labels: size/M, area/serverless, lgtm, kind/missing-test, cla: yes

#900 Warn if dead fields are used
  components/operator/internal/state/controller_configuration.go
  components/operator/internal/state/controller_configuration_test.go
Labels: size/M, lgtm, cla: yes

#910 Disable md checks for shields and reuse links
  .mlc.config.json
Labels: kind/bug, lgtm, size/XS, area/ci, cla: yes

#909 Cleanup deprecated image pull secret configuration
  config/serverless/templates/deployment.yaml
  config/serverless/templates/service-accounts.yaml
  config/serverless/values.yaml
Labels: lgtm, size/XS, cla: yes

#908 Always run specified GH Actions
  .github/workflows/operator-verify.yaml
  .github/workflows/serverless-verify.yaml
Labels: size/S, lgtm, cla: yes

#913 Test with k8s v1.29.3
  .github/workflows/operator-verify.yaml
  .github/workflows/serverless-verify.yaml
  hack/gardener.mk
Labels: lgtm, size/XS, kind/chore, cla: yes

#914 Cleanup deprecated image pull secret configuration (#909)
  config/serverless/templates/deployment.yaml
  config/serverless/templates/service-accounts.yaml
  config/serverless/values.yaml
Labels: kind/bug, lgtm, size/XS, kind/cleanup, cla: yes

#907 Cleanup hack/Makefile
  .github/workflows/operator-verify.yaml
  .github/workflows/serverless-verify.yaml
  hack/Makefile
Labels: size/M, lgtm, kind/missing-test, area/ci, cla: yes

#912 Improve upgrade tests
  .github/workflows/operator-verify.yaml
  .github/workflows/serverless-verify.yaml
  Makefile
  components/operator/Makefile
Labels: size/M, area/serverless, lgtm, area/tests, kind/missing-test, area/ci, cla: yes

#919 Change "workspace" to "app"
  components/operator/Dockerfile
Labels: area/serverless, lgtm, size/XS, kind/chore, cla: yes

#917 chore: Security updates
  components/operator/Dockerfile
  components/runtimes/nodejs/nodejs18/package.json
  components/runtimes/nodejs/nodejs20/package.json
  components/runtimes/python/python312/requirements.txt
  components/runtimes/python/python39/requirements.txt
Labels: size/M, lgtm, kind/chore, cla: yes

#920 Revert "Change "workspace" to "app" (#919)"
  components/operator/Dockerfile
Labels: lgtm, size/XS, cla: yes

#911 Add operator integration test
  .github/workflows/operator-verify.yaml
Labels: size/M, area/serverless, lgtm, area/tests, kind/missing-test, area/ci, cla: yes

#915 Bump controller-runtime and k8s
  components/operator/main.go
  components/serverless/cmd/manager/main.go
  components/serverless/cmd/webhook/main.go
  go.mod
  go.sum
Labels: size/M, lgtm, cla: yes

#916 Cleanup temporary repository files
  components/serverless/internal/git/go2git.go
Labels: lgtm, size/XS, cla: yes

#926 Revert changes in GH workflow
  .github/workflows/operator-verify.yaml
  .github/workflows/serverless-verify.yaml
Labels: size/S, lgtm, cla: yes

#922 Revert image workspace change to release 1.4
  components/operator/Dockerfile
Labels: kind/bug, lgtm, size/XS, cla: yes

#921 Update testing strategy document
  docs/contributor/04-10-testing-strategy.md
Labels: area/serverless, size/S, lgtm, area/tests, area/documentation, kind/chore, cla: yes

#925 Cleanup temporary repository files (#916) in release 1.4
  components/serverless/internal/git/go2git.go
Labels: kind/bug, lgtm, size/XS, cla: yes

#930 Increase operator integration test retry timeout
  tests/operator/utils/retry.go
Labels: lgtm, size/XS, kind/failing-test, area/tests, cla: yes

#927 Prapare images to be usable in ADO build jobs
  components/operator/Dockerfile
Labels: lgtm, size/XS, cla: yes

#932 Prepare images to be usable in ADO build jobs (#927) in release-1.4
  components/operator/Dockerfile
Labels: lgtm, size/XS, cla: yes

#933 Fix image permission after switch to ADO
  components/runtimes/nodejs/nodejs18/Dockerfile
  components/runtimes/nodejs/nodejs20/Dockerfile
  components/runtimes/python/python312/Dockerfile
  components/runtimes/python/python39/Dockerfile
Labels: size/S, lgtm, cla: yes

#934 Fix image permission after switch to ADO (#933) - fix for 1.4 branch
  components/runtimes/nodejs/nodejs18/Dockerfile
  components/runtimes/nodejs/nodejs20/Dockerfile
  components/runtimes/python/python312/Dockerfile
  components/runtimes/python/python39/Dockerfile
Labels: size/S, lgtm, cla: yes

#944 Cherry-pick: chore: Bump nodejs runtimes base images
  components/runtimes/nodejs/nodejs18/Dockerfile
  components/runtimes/nodejs/nodejs20/Dockerfile
Labels: area/serverless, lgtm, size/XS, kind/chore, cla: yes

#929 Improve fn tag calculation
  components/serverless/internal/controllers/serverless/build_resources_test.go
  components/serverless/internal/controllers/serverless/configmap.go
  components/serverless/internal/controllers/serverless/deployment.go
  components/serverless/internal/controllers/serverless/fsm.go
  components/serverless/internal/controllers/serverless/function_reconcile.go
  components/serverless/internal/controllers/serverless/function_reconcile_asserts_test.go
  components/serverless/internal/controllers/serverless/function_reconcile_gitops_test.go
  components/serverless/internal/controllers/serverless/job.go
  components/serverless/internal/controllers/serverless/system_state.go
  components/serverless/internal/controllers/serverless/utils.go
  components/serverless/internal/controllers/serverless/utils_test.go
Labels: lgtm, size/L, cla: yes

#928 Add real local target
  .dockerignore
  Makefile
  README.md
  config/serverless/charts/docker-registry/templates/deployment.yaml
  config/serverless/templates/deployment.yaml
  config/serverless/values.yaml
  hack/build_all.sh
  hack/docker-compose.yaml
  hack/k3d.mk
  hack/replace_serverless_chart_images.sh
Labels: size/M, lgtm, cla: yes

#948 Cherry-Pick: Improve fn tag calculation (#929)
  components/serverless/internal/controllers/serverless/build_resources_test.go
  components/serverless/internal/controllers/serverless/configmap.go
  components/serverless/internal/controllers/serverless/deployment.go
  components/serverless/internal/controllers/serverless/fsm.go
  components/serverless/internal/controllers/serverless/function_reconcile.go
  components/serverless/internal/controllers/serverless/function_reconcile_asserts_test.go
  components/serverless/internal/controllers/serverless/function_reconcile_gitops_test.go
  components/serverless/internal/controllers/serverless/job.go
  components/serverless/internal/controllers/serverless/system_state.go
  components/serverless/internal/controllers/serverless/utils.go
  components/serverless/internal/controllers/serverless/utils_test.go
Labels: kind/feature, area/serverless, lgtm, size/L, kind/chore, cla: yes

#950 Mute the `k3d registry create` help
  hack/k3d.mk
Labels: area/serverless, lgtm, size/XS, kind/cleanup, cla: yes
