Repository kyma-project/serverless, pull requests merged in 2024-06, with the labels that each got.

#1007 Do not generate changelog during release
  .github/scripts/create_changelog.sh
  .github/scripts/create_draft_release.sh
  .github/workflows/create-release.yaml
Labels: size/M, lgtm, kind/cleanup, area/ci, cla: yes

#1015 Use the `Free()` method on all git2go objects
  components/serverless/internal/git/fetcher.go
  components/serverless/internal/git/go2git.go
Labels: area/serverless, size/S, lgtm, kind/cleanup, cla: yes

#1022 Add libraries necessary to run hana-client
  components/runtimes/nodejs/nodejs18/Dockerfile
  components/runtimes/nodejs/nodejs20/Dockerfile
Labels: size/S, lgtm, cla: yes

#1027 Add libraries necessary to run hana-client (#1022)
  components/runtimes/nodejs/nodejs18/Dockerfile
  components/runtimes/nodejs/nodejs20/Dockerfile
Labels: size/S, lgtm, cla: yes

#1012 disable running markdown checker on pull and enable on push
  .github/workflows/markdown.yaml
  docs/contributor/04-10-testing-strategy.md
Labels: area/serverless, size/S, lgtm, kind/cleanup, area/ci, cla: yes

#1028 Use consistent labels
  components/serverless/config/crd/kustomization.yaml
  config/serverless/Chart.yaml
  config/serverless/templates/busola-serverless-extension.yaml
  config/serverless/templates/cluster-role-binding.yaml
  config/serverless/templates/cluster-role.yaml
  config/serverless/templates/configmap.yaml
  config/serverless/templates/crds.yaml
  config/serverless/templates/deployment.yaml
  config/serverless/templates/leader-election-role-binding.yaml
  config/serverless/templates/leader-election-role.yaml
  config/serverless/templates/priorityclass.yaml
  config/serverless/templates/runtimes.yaml
  config/serverless/templates/service-accounts.yaml
  config/serverless/templates/service.yaml
  config/serverless/values.yaml
Labels: size/M, lgtm, cla: yes

#1032 fix: highlights for badges
  config/serverless/templates/busola-serverless-extension.yaml
Labels: size/S, lgtm, cla: yes

#1036 Add contract test for hana-client
  docs/contributor/04-10-testing-strategy.md
  tests/serverless/cmd/main.go
  tests/serverless/internal/resources/runtimes/nodejs.go
  tests/serverless/internal/testsuite/hana_client.go
Labels: lgtm, size/L, kind/missing-test, cla: yes
