Repository kyma-project/serverless, pull requests merged in 2024-09, with the labels that each got.

#1148 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: lgtm, size/XS, cla: yes

#1149 docs: Added mandatory sections to README.md
  README.md
Labels: size/S, lgtm, cla: yes

#1158 Don't bump minor Python images
  .github/dependabot.yml
Labels: lgtm, size/XS, cla: yes

#1161 Add script for automatic version label bumping
  .github/workflows/create-release.yaml
  components/serverless/config/crd/kustomization.yaml
  config/serverless/templates/crds.yaml
  hack/replace_serverless_crd_version.sh
Labels: size/M, cla: yes

#1162 Use go.mod go version in actions
  .github/actions/setup-go/action.yaml
Labels: size/S, lgtm, cla: yes

#1163 Unify linter config
  components/operator/.golangci.yaml
  components/operator/internal/registry/secret.go
  components/operator/internal/state/fsm.go
  components/serverless/.golangci.yaml
  components/serverless/internal/controllers/serverless/build_resources.go
  components/serverless/internal/controllers/serverless/job.go
  components/serverless/internal/controllers/serverless/scaling.go
  components/serverless/internal/git/go2git.go
  components/serverless/internal/webhook/resources/webhook_config.go
Labels: size/M, lgtm, cla: yes

#1165 Revert "Unify linter config (#1163)"
  components/operator/.golangci.yaml
  components/operator/internal/registry/secret.go
  components/operator/internal/state/fsm.go
  components/serverless/.golangci.yaml
  components/serverless/internal/controllers/serverless/build_resources.go
  components/serverless/internal/controllers/serverless/job.go
  components/serverless/internal/controllers/serverless/scaling.go
  components/serverless/internal/git/go2git.go
  components/serverless/internal/webhook/resources/webhook_config.go
Labels: size/M, lgtm, cla: yes

#1166 fix dependabot for nodejs images
  .github/dependabot.yml
Labels: lgtm, size/XS, cla: yes

#1178 Lint tests
  components/operator/.golangci.yaml
  components/operator/internal/registry/secret.go
  components/serverless/.golangci.yaml
  components/serverless/internal/controllers/serverless/job.go
  components/serverless/internal/controllers/serverless/scaling.go
  components/serverless/internal/git/go2git.go
  components/serverless/internal/webhook/resources/webhook_config.go
Labels: size/M, cla: yes

#1177 Specify target ref for pull_request_target workflows
  .github/actions/rebase/action.yaml
  .github/workflows/_build.yaml
  .github/workflows/_gitleaks.yaml
  .github/workflows/_images-verify.yaml
  .github/workflows/_integration-tests.yaml
  .github/workflows/_unit-tests.yaml
  .github/workflows/lint.yaml
  .github/workflows/markdown.yaml
Labels: size/M, lgtm, kind/failing-test, area/tests, cla: yes

#1183 Fix controller-gen target to correctly detect version
  hack/tools.mk
Labels: lgtm, size/XS, cla: yes

#1184 fix: highlights for badges
  config/serverless/templates/busola-serverless-extension.yaml
Labels: size/XS, cla: yes

#1186 Run image-verify workflow on PRs to main only
  .github/workflows/_images-verify.yaml
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#1188 Run image-verify workflow on PRs to main only v2
  .github/workflows/_images-verify.yaml
  .github/workflows/pull.yaml
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes
