Repository kyma-project/serverless, pull requests merged in 2024-01, with the labels that each got.

#534 Fix link to the Scale to Zero With Keda example
  docs/user/tutorials/01-130-use-external-scalers.md
Labels: lgtm, size/XS, area/documentation, cla: yes

#528 Add troubleshooting for Docker + Rosetta
  components/serverless/README.md
Labels: kind/bug, size/S, lgtm, area/documentation, cla: yes

#535 Move Git secretName validation to controller
  components/serverless/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/serverless/pkg/apis/serverless/v1alpha2/function_types.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_validation.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_x_validation_test.go
  config/serverless/templates/crds.yaml
Labels: kind/feature, size/M, area/serverless, lgtm, cla: yes

#536 Move Git auth type validation to controller
  components/serverless/pkg/apis/serverless/v1alpha2/function_types.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_validation.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_x_validation_test.go
Labels: kind/feature, size/M, area/serverless, lgtm, cla: yes

#538 Propagate user defined default presets
  components/operator/internal/chart/flags.go
  components/operator/internal/chart/flags_test.go
Labels: size/M, lgtm, cla: yes

#530 Update module name in tests/serverless
  tests/serverless/cmd/main.go
  tests/serverless/go.mod
  tests/serverless/internal/assertion/check.go
  tests/serverless/internal/assertion/cloud_events.go
  tests/serverless/internal/config.go
  tests/serverless/internal/executor/parallel_test.go
  tests/serverless/internal/executor/serial_test.go
  tests/serverless/internal/resources/app/app.go
  tests/serverless/internal/resources/app/deployment.go
  tests/serverless/internal/resources/app/service.go
  tests/serverless/internal/resources/configmap/configmap.go
  tests/serverless/internal/resources/configmap/step.go
  tests/serverless/internal/resources/function/function.go
  tests/serverless/internal/resources/function/steps.go
  tests/serverless/internal/resources/git/commitchanges.go
  tests/serverless/internal/resources/git/git_cfg.go
  tests/serverless/internal/resources/git/gitserver.go
  tests/serverless/internal/resources/git/step.go
  tests/serverless/internal/resources/namespace/namespace.go
  tests/serverless/internal/resources/namespace/step.go
  tests/serverless/internal/resources/resource.go
  tests/serverless/internal/resources/secret/secret.go
  tests/serverless/internal/resources/secret/step.go
  tests/serverless/internal/testsuite/api_gateway.go
  tests/serverless/internal/testsuite/cloud_events.go
  tests/serverless/internal/testsuite/gitauth.go
  tests/serverless/internal/testsuite/gitops.go
  tests/serverless/internal/testsuite/light_runtimes.go
  tests/serverless/internal/testsuite/tracing.go
Labels: lgtm, size/L, kind/chore, cla: yes

#529 Move value bumping to dockerfile
  components/operator/Dockerfile.dev
  components/operator/Makefile
  components/operator/hack/ci/Makefile
  components/operator/hack/common/Makefile
  components/operator/hack/local/Makefile
Labels: size/M, lgtm, cla: yes

#549 Remove secrets and configmaps from the cache
  components/operator/main.go
  components/serverless/cmd/manager/main.go
  components/serverless/cmd/webhook/main.go
Labels: kind/feature, area/serverless, size/S, lgtm, cla: yes

#550 fix k3d-upgrade-test
  components/operator/hack/ci/Makefile
  components/operator/hack/common/Makefile
Labels: area/serverless, size/S, lgtm, kind/cleanup, area/tests, cla: yes

#543 disable webhooks
  config/serverless/values.yaml
Labels: kind/feature, area/serverless, lgtm, size/XS, cla: yes

#553 Small improvemetns for integration tests
  tests/serverless/Makefile
  tests/serverless/internal/assertion/check_test.go
  tests/serverless/internal/testsuite/gitops.go
  tests/serverless/run-local.sh
Labels: size/S, lgtm, cla: yes

#552 Validate scaleConfig boundaries
  components/serverless/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/serverless/pkg/apis/serverless/v1alpha2/function_types.go
  config/serverless/templates/crds.yaml
Labels: lgtm, size/XS, cla: yes

#548 Remove unused files
  .github/OWNERS
  OWNERS
  OWNERS_ALIASES
  PROJECT
  components/serverless/PROJECT
  docs/OWNERS
Labels: size/M, lgtm, kind/cleanup, area/documentation, area/ci, cla: yes

#555 Fix controller tests for webhook
  components/operator/controllers/serverless_controller_test.go
Labels: kind/bug, size/S, lgtm, cla: yes

#531 Update module name in components/operator
  components/operator/controllers/serverless_controller.go
  components/operator/controllers/serverless_controller_test.go
  components/operator/controllers/suite_test.go
  components/operator/controllers/testhelper_test.go
  components/operator/go.mod
  components/operator/internal/chart/install.go
  components/operator/internal/state/add_finalizer_test.go
  components/operator/internal/state/apply.go
  components/operator/internal/state/apply_test.go
  components/operator/internal/state/controller_configuration.go
  components/operator/internal/state/controller_configuration_test.go
  components/operator/internal/state/delete.go
  components/operator/internal/state/delete_test.go
  components/operator/internal/state/emit_event_test.go
  components/operator/internal/state/fsm.go
  components/operator/internal/state/fsm_test.go
  components/operator/internal/state/initialize_test.go
  components/operator/internal/state/new.go
  components/operator/internal/state/optional_dependencies.go
  components/operator/internal/state/optional_dependencies_test.go
  components/operator/internal/state/registry.go
  components/operator/internal/state/registry_test.go
  components/operator/internal/state/remove_finalizer_test.go
  components/operator/internal/state/served_filter.go
  components/operator/internal/state/served_filter_test.go
  components/operator/internal/state/serverless_utils.go
  components/operator/internal/state/state.go
  components/operator/internal/state/state_test.go
  components/operator/internal/state/verify.go
  components/operator/internal/state/verify_test.go
  components/operator/main.go
Labels: lgtm, size/L, kind/chore, cla: yes

#551 Fix typo in CI test
  components/operator/hack/common/Makefile
Labels: lgtm, size/XS, cla: yes

#556 Rename serverless import in tests
  tests/serverless/go.mod
  tests/serverless/go.sum
  tests/serverless/internal/resources/function/function.go
  tests/serverless/internal/resources/function/steps.go
  tests/serverless/internal/resources/runtimes/git_function.go
  tests/serverless/internal/resources/runtimes/nodejs.go
  tests/serverless/internal/resources/runtimes/python.go
  tests/serverless/internal/testsuite/api_gateway.go
  tests/serverless/internal/testsuite/cloud_events.go
  tests/serverless/internal/testsuite/gitauth.go
  tests/serverless/internal/testsuite/gitops.go
  tests/serverless/internal/testsuite/light_runtimes.go
  tests/serverless/internal/testsuite/tracing.go
Labels: size/M, lgtm, kind/chore, cla: yes

#557 add gh action serverless-operator-unit-tests
  .github/workflows/operator-verify.yaml
Labels: area/serverless, size/S, lgtm, kind/chore, cla: yes

#561 add gh action serverless-operator-verify
  .github/workflows/operator-verify.yaml
  components/operator/hack/ci/Makefile
Labels: size/M, area/serverless, lgtm, kind/chore, cla: yes

#564 Update Readme.md
  README.md
Labels: lgtm, size/XS, cla: yes

#559 Implement proper port for prometheus
  components/serverless/internal/controllers/serverless/service.go
  components/serverless/internal/controllers/serverless/service_test.go
  components/serverless/internal/controllers/serverless/system_state.go
  components/serverless/internal/controllers/serverless/utils.go
Labels: size/M, lgtm, cla: yes

#563 Bump serverless k8s dependency to a common version
  components/serverless/go.mod
  components/serverless/go.sum
  components/serverless/internal/resource/automock/client.go
  components/serverless/internal/resource/automock/k8s_client.go
  components/serverless/internal/resource/resource.go
Labels: lgtm, size/XL, cla: yes

#567 Remove google container
  config/serverless/values.yaml
Labels: lgtm, size/XS, cla: yes

#512 Set app.kubernetes.io/name label for better function instrumentation
  components/runtimes/nodejs/lib/metrics.js
  components/runtimes/nodejs/lib/tracer.js
  components/runtimes/nodejs/server.js
  components/runtimes/python39/kubeless/kubeless.py
  components/runtimes/python39/kubeless/tracing.py
  components/serverless/internal/controllers/serverless/build_resources_test.go
  components/serverless/internal/controllers/serverless/function_reconcile_asserts_test.go
  components/serverless/internal/controllers/serverless/function_reconcile_gitops_test.go
  components/serverless/internal/controllers/serverless/system_state.go
  components/serverless/internal/controllers/serverless/system_state_test.go
  components/serverless/pkg/apis/serverless/v1alpha2/function_types.go
Labels: size/M, lgtm, cla: yes

#566 Migrate lint operator job
  .github/workflows/operator-verify.yaml
Labels: size/S, lgtm, kind/cleanup, area/ci, cla: yes

#569 Move gardener integration test
  .github/workflows/gardener-integration.yaml
  .github/workflows/operator-verify.yaml
Labels: size/M, lgtm, kind/cleanup, area/ci, cla: yes

#571 Reduce logs from tests and serverless-controller
  components/serverless/hack/controller.env
  components/serverless/internal/controllers/serverless/fsm.go
  tests/serverless/internal/resources/function/function.go
Labels: lgtm, size/XS, cla: yes

#574 Remove old file webhook config
  components/serverless/hack/webhook_config.yaml
Labels: size/M, lgtm, cla: yes

#576 merge ga markdown-link-check
  .github/workflows/daily-markdown-link-check.yaml
  .github/workflows/markdown.yaml
Labels: area/serverless, size/S, lgtm, kind/cleanup, cla: yes

#572 Add dependabot for GH actions
  .github/dependabot.yml
Labels: size/S, lgtm, cla: yes

#575 Migrate upgrade test
  .github/workflows/operator-verify.yaml
  components/operator/hack/ci/Makefile
Labels: size/M, lgtm, kind/cleanup, area/ci, cla: yes

#578 Move status badge to status subcategory
  README.md
Labels: lgtm, size/XS, kind/cleanup, area/documentation, cla: yes

#568 Cleanup unused ENVS from docs
  components/serverless/README.md
Labels: area/serverless, lgtm, size/XS, kind/cleanup, area/documentation, cla: yes

#582 Gitserver dockerfile: use one FROM statement
  tests/gitserver/Dockerfile
  tests/serverless/internal/config.go
Labels: lgtm, size/XS, cla: yes

#584 Fix link checker
  components/serverless/README.md
Labels: lgtm, size/XS, cla: yes

#586 Move the `check-serverless-availability` target to the `verify-serverless`
  components/operator/hack/ci/Makefile
  components/operator/hack/common/Makefile
Labels: size/S, lgtm, kind/cleanup, area/ci, cla: yes

#581 Fix OOM for large function images
  components/serverless/README.md
  components/serverless/hack/controller.env
  components/serverless/internal/controllers/serverless/config.go
  config/serverless/values.yaml
  docs/user/00-20-configure-serverless.md
  docs/user/resources/06-20-serverless-cr.md
  docs/user/troubleshooting-guides/03-40-function-build-failing-k3d.md
  sec-scanners-config.yaml
Labels: kind/bug, size/S, lgtm, cla: yes

#577 Rename workflow checking if developer doesn't change main images
  .github/workflows/images-verify.yaml
Labels: lgtm, size/XS, kind/cleanup, area/ci, cla: yes

#588 Fix docs link
  docs/user/tutorials/01-130-use-external-scalers.md
Labels: lgtm, size/XS, cla: yes

#580 Add dependabot for Dockerfiles
  .github/dependabot.yml
Labels: size/M, lgtm, cla: yes

#592 Bump jobinit base images
  components/serverless/deploy/jobinit/Dockerfile
Labels: lgtm, size/XS, cla: yes

#594 Fix legacy upgrade test
  components/operator/hack/ci/Makefile
Labels: lgtm, size/XS, cla: yes

#599 Bump rc-tag 1.3.0
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#598 Bump jobinit base images
  components/serverless/deploy/jobinit/Dockerfile
Labels: lgtm, size/XS, cla: yes

#597 Bump manager base images
  components/serverless/deploy/manager/Dockerfile
Labels: lgtm, size/XS, cla: yes

#603 Fix nil annotations
  components/serverless/internal/controllers/serverless/service.go
Labels: lgtm, size/XS, cla: yes

#605 Fix nil annotations 1.3 (#603)
  components/serverless/internal/controllers/serverless/service.go
Labels: kind/bug, lgtm, size/XS, priority/critical-urgent, cla: yes

#601 Bump requests pip library
  docs/user/technical-reference/07-10-sample-functions.md
  examples/python-text2img/requirements.txt
  examples/python-text2img/resources/function.yaml
  tests/serverless/internal/resources/runtimes/python.go
Labels: size/S, lgtm, cla: yes

#609 Change GCR to Artifact Registry
  docs/user/00-20-configure-serverless.md
Labels: lgtm, size/XS, cla: yes

#587 Enable Dependabot for Python dependencies
  .github/dependabot.yml
Labels: lgtm, size/XS, cla: yes

#596 Enable Dependabot for Node dependencies
  .github/dependabot.yml
Labels: size/M, lgtm, cla: yes

#610 Enable Dependabot for Go dependencies
  .github/dependabot.yml
Labels: size/S, lgtm, cla: yes

#558 Add serverless verify to github action
  .github/workflows/serverless-verify.yaml
Labels: kind/feature, size/M, lgtm, cla: yes

#633 Improve the `verify-serverless` target logging
  components/operator/hack/common/Makefile
Labels: size/S, lgtm, kind/failing-test, area/ci, cla: yes

#634 Fix upgrade test url
  components/operator/hack/ci/Makefile
Labels: lgtm, size/XS, kind/failing-test, area/tests, cla: yes

#638 Print more details when verification fails
  components/operator/hack/common/Makefile
Labels: size/S, lgtm, kind/failing-test, area/tests, cla: yes

#616 Update all pip opentelemetry packages together
  .github/dependabot.yml
Labels: lgtm, size/XS, cla: yes

#641 Fix flaky integration test
  components/operator/hack/common/Makefile
Labels: lgtm, size/XS, kind/failing-test, area/tests, cla: yes

#642 Update all npm opentelemetry packages together
  .github/dependabot.yml
Labels: lgtm, size/XS, cla: yes

#639 Group bump for telemetry
  components/runtimes/nodejs/nodejs16/package.json
  components/runtimes/nodejs/nodejs18/package.json
Labels: area/serverless, size/S, lgtm, kind/chore, cla: yes

#650 Update all npm opentelemetry packages together
  .github/dependabot.yml
Labels: lgtm, size/XS, cla: yes

#659 (pip): Update cherrypy to cheroot 10.0.0
  components/runtimes/python39/kubeless/kubeless.py
  components/runtimes/python39/kubeless/requirements.txt
Labels: lgtm, size/XS, cla: yes

#660 Enable contract tests in integration tests bundle
  components/operator/hack/ci/Makefile
Labels: lgtm, size/XS, area/tests, kind/missing-test, cla: yes

#661 bump opentelemtry sdk (1.22.0) for python functions
  components/runtimes/python39/kubeless/requirements.txt
  tests/serverless/internal/resources/runtimes/python.go
Labels: area/serverless, size/S, lgtm, kind/chore, cla: yes

#635 Move libgit2 installation to seperate action
  .github/actions/setup-libgit2/action.yaml
  .github/workflows/operator-verify.yaml
  .github/workflows/serverless-verify.yaml
Labels: kind/feature, size/M, lgtm, cla: yes

#585 Use static kyma-system namespace
  README.md
  components/operator/hack/common/Makefile
  config/samples/default-serverless-cr-k3d-explicit.yaml
  config/samples/default-serverless-cr-k3d.yaml
  config/samples/default-serverless-cr.yaml
Labels: size/S, lgtm, cla: yes

#583 Regenerate manifests
  components/serverless/config/crd/bases/serverless.kyma-project.io_functions.yaml
  config/serverless/templates/crds.yaml
Labels: size/M, lgtm, cla: yes

#573 Bump k8s go dependencies
  components/operator/Makefile
  components/operator/controllers/serverless_controller.go
  components/operator/internal/state/add_finalizer.go
  components/operator/internal/state/controller_configuration.go
  components/operator/internal/tracing/watcher.go
  components/serverless/Makefile
  components/serverless/cmd/webhook/main.go
  components/serverless/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/serverless/internal/controllers/serverless/automock/git_client.go
  components/serverless/internal/controllers/serverless/automock/git_client_factory.go
  components/serverless/internal/controllers/serverless/automock/stats_collector.go
  components/serverless/internal/controllers/serverless/fsm_test.go
  components/serverless/internal/controllers/serverless/validation_test.go
  components/serverless/internal/resource/automock/client.go
  components/serverless/internal/resource/automock/k8s_client.go
  components/serverless/internal/webhook/resources/resources.go
  components/serverless/internal/webhook/validating_webhook_test.go
  config/serverless/templates/crds.yaml
  go.mod
  go.sum
Labels: lgtm, size/XXL, cla: yes

#665 Bump go dependencies
  go.mod
  go.sum
Labels: size/M, lgtm, cla: yes

#672 Add unit tests for service.go
  components/serverless/internal/controllers/serverless/service_test.go
Labels: lgtm, size/L, cla: yes

#677 Fix broken links
  config/serverless/README.md
  tests/serverless-bench/README.md
  tests/serverless/README.md
Labels: lgtm, size/XS, cla: yes

#676 Improve invalid deployment error handling
  components/serverless/internal/controllers/serverless/deployment.go
Labels: size/S, lgtm, cla: yes
