Repository kyma-project/serverless, pull requests merged in 2025-01, with the labels that each got.

#1355 Get rid of the `verify-actions-status` script
  .github/scripts/verify-actions-status.sh
  .github/workflows/create-release.yaml
Labels: size/M, lgtm, kind/cleanup, area/ci, cla: yes

#1358 Buildless resource tests
  components/buildless-serverless/go.mod
  components/buildless-serverless/internal/controller/resources/deployment.go
  components/buildless-serverless/internal/controller/resources/deployment_test.go
  components/buildless-serverless/internal/controller/resources/service_test.go
Labels: lgtm, size/XL, cla: yes

#1354 Add labels to buildless serverless
  components/buildless-serverless/api/v1alpha2/function_types.go
  components/buildless-serverless/internal/controller/function_controller.go
  components/buildless-serverless/internal/controller/resources/deployment.go
  components/buildless-serverless/internal/controller/resources/deployment_test.go
  components/buildless-serverless/internal/controller/resources/service.go
  components/buildless-serverless/internal/controller/resources/service_test.go
Labels: size/S, lgtm, cla: yes

#1359 add job for buildless serverless unit tests
  .github/workflows/_unit-tests.yaml
Labels: size/S, cla: yes

#1364 Adjust buildless to cloud events
  components/buildless-serverless/Makefile
  components/buildless-serverless/internal/config/function_config.go
  components/buildless-serverless/internal/controller/resources/deployment.go
  components/buildless-serverless/internal/controller/resources/deployment_test.go
  components/buildless-serverless/internal/controller/state/handle_deployment.go
  config/buildless-serverless/templates/deployment.yaml
  config/buildless-serverless/values.yaml
  tests/serverless/internal/resources/runtimes/python.go
Labels: size/M, lgtm, cla: yes

#1368 fix: node22 image building and testing
  components/runtimes/nodejs/nodejs22/Dockerfile
Labels: lgtm, size/XS, cla: yes

#1366 Cleanup Function CR details view
  config/serverless/templates/busola-serverless-extension.yaml
Labels: size/L, cla: yes

#1369 Add node22 support to buildless serverless
  components/buildless-serverless/api/v1alpha2/function_types.go
  components/buildless-serverless/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/buildless-serverless/internal/config/function_config.go
  components/buildless-serverless/internal/controller/resources/deployment.go
  components/buildless-serverless/internal/controller/resources/deployment_test.go
  components/buildless-serverless/internal/controller/state/validate_function.go
  config/buildless-serverless/templates/crds.yaml
Labels: lgtm, size/L, cla: yes

#1370 Use condition lists in busola
  components/runtimes/nodejs/nodejs22/Dockerfile
  config/operator/base/ui-extensions/serverless/details
  config/operator/base/ui-extensions/serverless/kustomization.yaml
  config/serverless/templates/busola-serverless-extension.yaml
Labels: lgtm, size/L, cla: yes

#1371 Bump actions used for kyma terraforming in integration tests
  .github/workflows/_integration-tests.yaml
Labels: size/XS, area/ci, kind/chore

#1376 buildless state tests
  components/buildless-serverless/go.mod
  components/buildless-serverless/internal/controller/state/adjust_status_test.go
  components/buildless-serverless/internal/controller/state/deployment_status.go
  components/buildless-serverless/internal/controller/state/deployment_status_test.go
  components/buildless-serverless/internal/controller/state/handle_service.go
  components/buildless-serverless/internal/controller/state/handle_service_test.go
  components/buildless-serverless/internal/controller/state/state_test.go
Labels: size/XL, kind/missing-test, cla: yes

#1380 Fix Language dropdown population
  config/serverless/templates/busola-serverless-extension.yaml
Labels: kind/bug, lgtm, size/XS, cla: yes

#1381 Fix Language dropdown population (#1380)
  config/serverless/templates/busola-serverless-extension.yaml
Labels: size/XS, cla: yes

#1383 Bump actions used for kyma terraforming in integration tests (#1371)
  .github/workflows/_integration-tests.yaml
Labels: lgtm, size/XS, cla: yes

#1384 Add nodejs22 to deplyoment and adjust log when APP didn't load
  components/buildless-serverless/cmd/main.go
  config/buildless-serverless/templates/deployment.yaml
  config/buildless-serverless/values.yaml
Labels: lgtm, size/XS, cla: yes

#1386 bump: base images
  external-images.yaml
Labels: size/S, cla: yes

#1382 Fix example reference in git function tutorial
  docs/user/tutorials/01-11-create-git-function.md
  examples/incluster_eventing/k8s-resources/emitter-fn.yaml
  examples/incluster_eventing/k8s-resources/receiver-fn.yaml
  examples/orders-service/README.md
  examples/orders-service/handler.js
  examples/orders-service/package.json
Labels: size/L, cla: yes

#1385 Buildless state tests 2
  components/buildless-serverless/internal/controller/state/handle_deployment.go
  components/buildless-serverless/internal/controller/state/handle_deployment_test.go
Labels: size/XL, cla: yes

#1387 Buildless state tests 3
  components/buildless-serverless/internal/controller/state/validate_function.go
  components/buildless-serverless/internal/controller/state/validate_function_test.go
  components/buildless-serverless/internal/controller/validator/validator.go
  components/buildless-serverless/internal/controller/validator/validator_test.go
Labels: lgtm, size/L, kind/missing-test, cla: yes

#1406 Add protocol TCP to deployment to create the service
  components/buildless-serverless/internal/controller/resources/deployment.go
Labels: lgtm, size/XS, cla: yes

#1405 Do not fix static namespace for resources in buildless chart
  config/buildless-serverless/templates/busola-serverless-extension.yaml
  config/buildless-serverless/templates/cluster-role-binding.yaml
  config/buildless-serverless/templates/deployment.yaml
  config/buildless-serverless/templates/leader-election-role-binding.yaml
  config/buildless-serverless/templates/leader-election-role.yaml
  config/buildless-serverless/templates/service-account.yaml
Labels: size/S, cla: yes

#1412 Exclude istio sidecar from buildless serverless
  config/buildless-serverless/templates/deployment.yaml
Labels: lgtm, size/XS, cla: yes

#1410 Update documentation and busola details
  config/operator/base/ui-extensions/serverless/details
  config/operator/base/ui-extensions/serverless/translations
  docs/user/00-20-configure-serverless.md
Labels: size/M, lgtm, cla: yes

#1413 Change labels to function-controller in buildless
  components/buildless-serverless/api/v1alpha2/function_types.go
  components/buildless-serverless/internal/controller/function_controller.go
  components/buildless-serverless/internal/controller/resources/deployment_test.go
  components/buildless-serverless/internal/controller/resources/service.go
  components/buildless-serverless/internal/controller/resources/service_test.go
Labels: size/M, cla: yes

#1411 Adjust security context in buildless serverless
  components/buildless-serverless/internal/controller/resources/deployment.go
Labels: size/S, cla: yes

#1414 Add cli extension for functions
  config/serverless/templates/cli-extension.yaml
Labels: kind/feature, size/M, area/serverless, lgtm, cla: yes

#1418 Allign Serverless docs
  docs/assets/svls-architecture.svg
  docs/assets/svls_architecture_new.png
  docs/user/00-10-from-code-to-function.md
  docs/user/00-20-configure-serverless.md
  docs/user/00-40-security-considerations.md
  docs/user/00-50-limitations.md
  docs/user/README.md
Labels: lgtm, size/L, cla: yes

#1423 Set right condition to true when git auth secret is not found
  components/serverless/internal/controllers/serverless/fsm.go
Labels: kind/bug, area/serverless, size/S, cla: yes

#1424 Cherry-pick: Set right condition to true when git auth secret is not found
  components/serverless/internal/controllers/serverless/fsm.go
Labels: kind/bug, area/serverless, size/S, lgtm, cla: yes

#1417 Buildless status
  components/buildless-serverless/api/v1alpha2/function_types.go
  components/buildless-serverless/internal/config/function_config.go
  components/buildless-serverless/internal/controller/fsm/fsm.go
  components/buildless-serverless/internal/controller/resources/deployment.go
  components/buildless-serverless/internal/controller/resources/deployment_test.go
  components/buildless-serverless/internal/controller/resources/service.go
  components/buildless-serverless/internal/controller/state/adjust_status.go
  components/buildless-serverless/internal/controller/state/adjust_status_test.go
  components/buildless-serverless/internal/controller/state/deployment_status.go
  components/buildless-serverless/internal/controller/state/deployment_status_test.go
  components/buildless-serverless/internal/controller/state/handle_deployment.go
  components/buildless-serverless/internal/controller/state/handle_deployment_test.go
  components/buildless-serverless/internal/controller/state/validate_function.go
  components/buildless-serverless/internal/controller/state/validate_function_test.go
Labels: size/L, cla: yes

#1403 chore: Remove unused part of logger
  components/serverless/internal/logging/logger/logger.go
  components/serverless/internal/logging/logger/logger_test.go
  components/serverless/internal/logging/tracing/helper.go
  components/serverless/internal/logging/tracing/helper_test.go
  components/serverless/internal/logging/tracing/middleware.go
  components/serverless/internal/logging/tracing/middleware_test.go
Labels: lgtm, size/L, cla: yes

#1427 Regenerate CRD
  config/operator/base/crd/bases/operator.kyma-project.io_serverlesses.yaml
Labels: area/serverless, size/S, kind/cleanup, cla: yes
