Repository kyma-project/serverless, pull requests merged in 2025-08, with the labels that each got.

#1817 Update serverless doc link
  module-config-template.yaml
Labels: documentation

#1821 Update buildless docs
  docs/user/00-20-configure-serverless.md
  docs/user/00-50-limitations.md
  docs/user/_sidebar.md
  docs/user/technical-reference/03-10-buildless-serverless.md
Labels: area/serverless, area/documentation

#1825 Return Function's resources by internal endpoint
  components/buildless-serverless/cmd/main.go
  components/buildless-serverless/internal/controller/fsm/fsm.go
  components/buildless-serverless/internal/controller/git/commit_checker.go
  components/buildless-serverless/internal/controller/git/git_auth.go
  components/buildless-serverless/internal/endpoint/endpoint.go
  components/buildless-serverless/internal/endpoint/function.go
  components/buildless-serverless/internal/endpoint/response.go
  components/buildless-serverless/internal/endpoint/server.go
  config/buildless-serverless/templates/cluster-role.yaml
  go.mod
Labels: kind/feature

#1834 Use proper api version for functions in module config
  module-config-template.yaml
Labels: kind/bug

#1853 Cherry pick remove istio annotation
  components/serverless/internal/controllers/serverless/system_state.go
Labels: kind/bug
