Repository kyma-project/serverless, pull requests merged in 2025-09, with the labels that each got.

#1855 Bump terraform module gh actions
  .github/workflows/_integration-tests.yaml
Labels: kind/chore

#1860 Add update rbac of secret to buildless controller
  components/buildless-serverless/internal/controller/function_controller.go
  config/buildless-serverless/templates/cluster-role.yaml
Labels: kind/bug

#1673 Migrate extensions documentation
  docs/user/08-10-best-practices.md
  docs/user/tutorials/01-10-create-inline-function.md
  docs/user/tutorials/01-110-override-runtime-image.md
  docs/user/tutorials/01-30-manage-functions-with-kyma-cli.md
  docs/user/tutorials/01-90-set-asynchronous-connection.md
Labels: documentation, area/serverless, area/cli

#1878 Prototype the `eject` extension command
  components/buildless-serverless/internal/endpoint/server.go
  config/buildless-serverless/files/kyma-commands.yaml
Labels: area/serverless, area/cli, enhancement

#1885 Respect nativeSidecar annotation from Function spec
  components/serverless/internal/controllers/serverless/system_state.go
  components/serverless/internal/controllers/serverless/system_state_test.go
Labels: kind/bug

#1896 Improve eject endpoint to return fully functional application
  components/buildless-serverless/Dockerfile
  components/buildless-serverless/Dockerfile.dockerignore
  components/buildless-serverless/internal/controller/resources/deployment.go
  components/buildless-serverless/internal/controller/resources/deployment_test.go
  components/buildless-serverless/internal/endpoint/function.go
  components/buildless-serverless/internal/endpoint/packagejson/merge.go
  components/runtimes/nodejs20/cli/Dockerfile
  components/runtimes/nodejs20/cli/Makefile
  components/runtimes/nodejs22/cli/Dockerfile
  components/runtimes/nodejs22/cli/Makefile
Labels: kind/feature

#1912 Update docs for kyma function subcommands due to CLI extension changes
  docs/user/tutorials/01-10-create-inline-function.md
  docs/user/tutorials/01-110-override-runtime-image.md
  docs/user/tutorials/01-30-manage-functions-with-kyma-cli.md
  docs/user/tutorials/01-90-set-asynchronous-connection.md
Labels: documentation

#1911 Rename `kubeless.py` into `server.py`
  components/buildless-serverless/internal/controller/resources/deployment.go
  components/buildless-serverless/internal/controller/resources/deployment_test.go
  components/runtimes/python312/Dockerfile
  components/runtimes/python312/server.py
Labels: kind/cleanup

#1915 Describe how to perform a smoke test of serverless module on a cluster
  docs/contributor/04-10-testing-strategy.md
Labels: documentation

#1918 Refactor endpoint sourcecode structure
  components/buildless-serverless/internal/endpoint/function.go
  components/buildless-serverless/internal/endpoint/response.go
  components/buildless-serverless/internal/endpoint/runtime/files.go
  components/buildless-serverless/internal/endpoint/runtime/resources.go
  components/buildless-serverless/internal/endpoint/types/types.go
Labels: kind/cleanup

#1919 Move files from the `cli` dir
  components/buildless-serverless/internal/endpoint/runtime/files.go
  components/runtimes/nodejs20/Dockerfile
  components/runtimes/nodejs20/Makefile
  components/runtimes/nodejs20/cli/Dockerfile
  components/runtimes/nodejs22/Dockerfile
  components/runtimes/nodejs22/Makefile
  components/runtimes/nodejs22/cli/Dockerfile
Labels: kind/cleanup

#1924 Improve ejected function Makefiles
  components/runtimes/nodejs20/Makefile
  components/runtimes/nodejs22/Makefile
  components/runtimes/python312/Makefile
Labels: enhancement

#1925 Eject function with README.md
  components/buildless-serverless/internal/endpoint/runtime/files.go
  components/runtimes/nodejs20/README_template.md
  components/runtimes/nodejs22/README_template.md
  components/runtimes/python312/README_template.md
Labels: enhancement

#1927 Test internal endpoint
  components/buildless-serverless/internal/endpoint/runtime/files.go
  components/buildless-serverless/internal/endpoint/runtime/files_test.go
  components/buildless-serverless/internal/endpoint/runtime/resources_test.go
Labels: enhancement
