Repository kyma-project/serverless, pull requests merged in 2025-02, with the labels that each got.

#1426 Set commonLabels for docker-registry resources
  config/serverless/charts/docker-registry/templates/configmap.yaml
  config/serverless/charts/docker-registry/templates/deployment.yaml
  config/serverless/charts/docker-registry/templates/ingress.yaml
  config/serverless/charts/docker-registry/templates/poddisruptionbudget.yaml
  config/serverless/charts/docker-registry/templates/pvc.yaml
  config/serverless/charts/docker-registry/templates/secret.yaml
  config/serverless/charts/docker-registry/templates/service.yaml
  config/serverless/templates/registry-config.yaml
Labels: area/serverless, size/S, kind/chore, cla: yes

#1425 Set commonLabels managed-by flag
  components/operator/internal/chart/flags.go
  components/operator/internal/chart/flags_test.go
  components/operator/internal/state/apply.go
  components/operator/internal/state/apply_test.go
  components/operator/internal/state/state_test.go
Labels: size/M, area/serverless, lgtm, kind/chore, cla: yes

#1428 enable linter for buildless serverless
  .github/workflows/lint.yaml
  components/buildless-serverless/internal/controller/state/adjust_status_test.go
  components/buildless-serverless/internal/controller/state/deployment_status.go
  components/buildless-serverless/internal/controller/state/deployment_status_test.go
  components/buildless-serverless/internal/controller/state/handle_deployment.go
  components/buildless-serverless/internal/controller/state/handle_service.go
  components/buildless-serverless/internal/controller/state/state.go
Labels: size/M, area/serverless, kind/missing-test, cla: yes

#1404 Adjust Buildless Serverless to work with tracing
  components/buildless-serverless/internal/config/function_config.go
  components/buildless-serverless/internal/controller/resources/deployment.go
  components/buildless-serverless/internal/controller/resources/deployment_test.go
  components/buildless-serverless/internal/controller/state/handle_deployment.go
  config/buildless-serverless/templates/deployment.yaml
  config/buildless-serverless/values.yaml
  tests/serverless/internal/resources/runtimes/python.go
  tests/serverless/internal/testsuite/api_gateway.go
Labels: kind/feature, area/serverless, lgtm, size/L, cla: yes

#1432 bump: base golang image
  external-images.yaml
Labels: lgtm, size/XS, cla: yes

#1433 Reuse helm lib
  components/operator/internal/chart/flags.go
  components/operator/internal/chart/flags_test.go
  components/operator/internal/state/apply.go
  components/operator/internal/state/apply_test.go
  components/operator/internal/state/optional_dependencies_test.go
  components/operator/internal/state/registry_test.go
Labels: area/serverless, lgtm, size/L, kind/cleanup, cla: yes

#1434 Add missing selector
  config/operator/base/deployment/deployment.yaml
Labels: area/serverless, size/XS, kind/cleanup, cla: yes

#1435 Remove unused env print
  .github/scripts/release.sh
Labels: area/serverless, size/XS, kind/cleanup, cla: yes

#1437 Set most labels values to const values
  config/serverless/values.yaml
Labels: area/serverless, size/XS, kind/cleanup, cla: yes

#1438 Add commonLabels to templates
  config/serverless/charts/docker-registry/templates/deployment.yaml
  config/serverless/values.yaml
Labels: area/serverless, lgtm, size/XS, kind/cleanup, cla: yes

#1436 change sequence of states in buildless-serverless
  components/buildless-serverless/api/v1alpha2/zz_generated.deepcopy.go
  components/buildless-serverless/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/buildless-serverless/internal/controller/state/handle_service.go
  components/buildless-serverless/internal/controller/state/handle_service_test.go
  components/buildless-serverless/internal/controller/state/state_test.go
  config/buildless-serverless/templates/crds.yaml
Labels: kind/feature, size/M, area/serverless, cla: yes

#1439 Add tmp volume for node and python
  components/buildless-serverless/internal/controller/resources/deployment.go
  components/buildless-serverless/internal/controller/resources/deployment_test.go
Labels: size/M, lgtm, cla: yes

#1323 Buildless serverless integration test
  .github/workflows/_integration-tests.yaml
  Makefile
  components/operator/Makefile
  tests/serverless/cmd/main.go
  tests/serverless/run-local.sh
Labels: kind/feature, size/M, lgtm, kind/missing-test, cla: yes

#1420 Change title in sidebar
  docs/user/_sidebar.md
Labels: lgtm, size/XS, cla: yes

#1449 Configure priorityClass for operator
  config/operator/base/deployment/deployment.yaml
  config/operator/base/kustomization.yaml
  config/operator/base/priority-class/kustomization.yaml
  config/operator/base/priority-class/priority_class.yaml
Labels: area/serverless, size/S, lgtm, cla: yes

#1451 Add deletion logic when deletionTimestap is set on function
  components/buildless-serverless/internal/controller/function_controller.go
Labels: area/serverless, lgtm, size/XS, cla: yes

#1450 Add configmap deletion after serverless version change
  components/operator/internal/chart/uninstall.go
  components/operator/internal/state/delete.go
  components/serverless/internal/controllers/kubernetes/configmap_controller.go
  components/serverless/internal/controllers/kubernetes/configmap_controller_test.go
  components/serverless/internal/controllers/kubernetes/configmap_service.go
Labels: lgtm, size/L, cla: yes

#1453 Cherry-Pick: Configure priorityClass for operator
  config/operator/base/deployment/deployment.yaml
  config/operator/base/kustomization.yaml
  config/operator/base/priority-class/kustomization.yaml
  config/operator/base/priority-class/priority_class.yaml
Labels: area/serverless, size/S, cla: yes

#1459 bump: base images
  external-images.yaml
Labels: size/S, cla: yes

#1473 bump: python version
  components/runtimes/python/python312/Dockerfile
Labels: size/XS, cla: yes

#1474 fix: speed up integration tests
  .github/workflows/_integration-tests.yaml
  config/samples/default-serverless-cr-fast-requeue.yaml
Labels: size/S, lgtm, cla: yes

#1477 Revert "fix: speed up integration tests (#1474)"
  .github/workflows/_integration-tests.yaml
  config/samples/default-serverless-cr-fast-requeue.yaml
Labels: size/S, lgtm, cla: yes

#1452 add support to git functions for buildless serverless
  components/buildless-serverless/api/v1alpha2/function_types.go
  components/buildless-serverless/api/v1alpha2/zz_generated.deepcopy.go
  components/buildless-serverless/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/buildless-serverless/internal/controller/resources/deployment.go
  components/buildless-serverless/internal/controller/resources/deployment_test.go
  components/buildless-serverless/internal/controller/state/handle_deployment.go
  components/buildless-serverless/internal/controller/state/handle_deployment_test.go
  config/buildless-serverless/templates/crds.yaml
Labels: size/XL, cla: yes

#1479 Add checking if git sources were changed in buildless
  components/buildless-serverless/api/v1alpha2/function_types.go
  components/buildless-serverless/go.mod
  components/buildless-serverless/go.sum
  components/buildless-serverless/internal/controller/fsm/fsm.go
  components/buildless-serverless/internal/controller/git/automock/last_commit_checker.go
  components/buildless-serverless/internal/controller/git/commit_checker.go
  components/buildless-serverless/internal/controller/resources/deployment.go
  components/buildless-serverless/internal/controller/resources/deployment_test.go
  components/buildless-serverless/internal/controller/state/adjust_status_test.go
  components/buildless-serverless/internal/controller/state/handle_deployment.go
  components/buildless-serverless/internal/controller/state/handle_deployment_test.go
  components/buildless-serverless/internal/controller/state/handle_git_sources.go
  components/buildless-serverless/internal/controller/state/handle_git_sources_test.go
  components/buildless-serverless/internal/controller/state/validate_function.go
  components/buildless-serverless/internal/controller/state/validate_function_test.go
Labels: area/serverless, lgtm, size/L, cla: yes

#1476 Update the Serverless tutorials
  docs/user/_sidebar.md
  docs/user/tutorials/01-10-create-inline-function.md
  docs/user/tutorials/01-11-create-git-function.md
  docs/user/tutorials/01-20-expose-function.md
  docs/user/tutorials/01-30-manage-functions-with-kyma-cli.md
  docs/user/tutorials/01-40-debug-function.md
Labels: lgtm, size/L, area/documentation, cla: yes

#1484 Add skipping git source check
  components/buildless-serverless/api/v1alpha2/function_types.go
  components/buildless-serverless/internal/controller/state/adjust_status.go
  components/buildless-serverless/internal/controller/state/handle_git_sources.go
  components/buildless-serverless/internal/controller/state/handle_git_sources_test.go
Labels: size/L, cla: yes

#1486 remove tip about debug option
  docs/user/08-10-best-practices.md
Labels: lgtm, size/XS, cla: yes
