Repository kyma-project/serverless, pull requests merged in 2025-04, with the labels that each got.

#1549 Cherry-pick: Migrate coreCommands to actionCommands (#1546)
  config/serverless/templates/cli-extension.yaml
Labels: area/serverless, area/cli

#1556 New cli extensions configmap
  config/serverless/files/kyma-commands.yaml
  config/serverless/templates/cli-extension-compat.yaml
  config/serverless/templates/cli-extension.yaml
Labels: area/serverless, area/cli

#1587 Bump k8s version in integration tests
  .github/actions/create-k3d-cluster/action.yaml
Labels: kind/chore

#1590 Allow buildldess to read secrets
  config/buildless-serverless/templates/cluster-role.yaml
Labels: kind/bug

#1582 Update APIRule UI to version v2
  docs/user/tutorials/01-20-expose-function.md
Labels: do-not-merge/work-in-progress

#1594 Stop using configPath in cli extension
  config/serverless/files/kyma-commands.yaml
Labels: area/serverless

#1596 Support envs and secretMounts fields
  config/serverless/files/kyma-commands.yaml
Labels: kind/feature, area/serverless

#1593 Update tutorial and example for cloud events
  docs/user/_sidebar.md
  docs/user/tutorials/01-90-set-asynchronous-connection.md
  examples/incluster_eventing/README.md
  examples/incluster_eventing/k8s-resources/emitter-fn.yaml
  examples/incluster_eventing/k8s-resources/namespace.yaml
  examples/incluster_eventing/k8s-resources/receiver-fn.yaml
  examples/incluster_eventing/src/emitter-fn/handler.js
Labels: documentation, area/documentation

#1617 Allow buildless to read secrets
  components/buildless-serverless/config/rbac/role.yaml
  components/buildless-serverless/internal/controller/function_controller.go
  config/buildless-serverless/templates/cluster-role.yaml
Labels: kind/bug
