Repository kyma-project/serverless, pull requests merged in 2025-03, with the labels that each got.

#1493 fix build job permissions
  .github/workflows/push.yaml
Labels: lgtm, size/XS

#1501 Add cmake to python runtime base
  components/runtimes/python/python312/Dockerfile
Labels: area/serverless, lgtm, size/XS

#1494 add authorization to git in buildless serverless
  components/buildless-serverless/Makefile
  components/buildless-serverless/cmd/main.go
  components/buildless-serverless/internal/config/function_config.go
  components/buildless-serverless/internal/controller/fsm/fsm.go
  components/buildless-serverless/internal/controller/git/automock/last_commit_checker.go
  components/buildless-serverless/internal/controller/git/commit_checker.go
  components/buildless-serverless/internal/controller/git/git_auth.go
  components/buildless-serverless/internal/controller/git/git_auth_test.go
  components/buildless-serverless/internal/controller/resources/deployment.go
  components/buildless-serverless/internal/controller/resources/deployment_test.go
  components/buildless-serverless/internal/controller/state/adjust_status_test.go
  components/buildless-serverless/internal/controller/state/configuration_ready.go
  components/buildless-serverless/internal/controller/state/configuration_ready_test.go
  components/buildless-serverless/internal/controller/state/handle_deployment.go
  components/buildless-serverless/internal/controller/state/handle_deployment_test.go
  components/buildless-serverless/internal/controller/state/handle_git_sources.go
  components/buildless-serverless/internal/controller/state/handle_git_sources_test.go
  components/buildless-serverless/internal/controller/state/validate_function.go
  components/buildless-serverless/internal/controller/state/validate_function_test.go
  config/buildless-serverless/templates/deployment.yaml
  config/buildless-serverless/values.yaml
Labels: do-not-merge/work-in-progress, size/XXL

#1511 Improve tutorials
  docs/user/_sidebar.md
  docs/user/tutorials/01-100-customize-function-traces.md
  docs/user/tutorials/01-80-log-into-private-packages-registry.md
Labels: area/serverless, area/documentation

#1521 Enable the `kyma alpha function init` command
  config/serverless/templates/cli-extension.yaml
Labels: area/serverless, area/cli

#1525 Improve extension
  config/serverless/templates/cli-extension.yaml
Labels: documentation, area/serverless, area/cli

#1528 Add `defaultRuntime` to the `init` cmd config
  config/serverless/templates/cli-extension.yaml
Labels: area/serverless, area/cli

#1529 Cherry-pick cli config
  config/serverless/templates/cli-extension.yaml
Labels: kind/feature, area/serverless, area/cli

#1524 Fix substitution logic in inject ENV tutorial
  docs/user/tutorials/01-120-inject-envs.md
Labels: kind/bug

#1523 Fix custom image overriding tutorial
  docs/user/tutorials/01-110-override-runtime-image.md
  examples/custom-serverless-runtime-image/Dockerfile
  examples/custom-serverless-runtime-image/README.md
  examples/custom-serverless-runtime-image/lib/requirements.txt
  examples/custom-serverless-runtime-image/lib/tracing.py
  examples/custom-serverless-runtime-image/requirements.txt
Labels: kind/bug, area/documentation

#1541 Add the `--runtime-image-override` flag
  config/serverless/templates/cli-extension.yaml
Labels: area/serverless, area/cli

#1542 Migrate docs to the new kyma cli
  docs/assets/svls-kyma-cli-functions.png
  docs/user/08-10-best-practices.md
  docs/user/technical-reference/07-60-function-configuration-file.md
  docs/user/tutorials/01-10-create-inline-function.md
  docs/user/tutorials/01-110-override-runtime-image.md
  docs/user/tutorials/01-120-inject-envs.md
  docs/user/tutorials/01-20-expose-function.md
  docs/user/tutorials/01-30-manage-functions-with-kyma-cli.md
  docs/user/tutorials/01-50-sync-function-with-gitops.md
  docs/user/tutorials/01-90-set-asynchronous-connection.md
Labels: documentation, area/serverless

#1543 Remove old kyma-cli v2 usage from tutorials
  examples/incluster_eventing/k8s-resources/emitter-fn.yaml
  examples/incluster_eventing/k8s-resources/receiver-fn.yaml
  examples/incluster_eventing/src/emitter-fn/config.yaml
  examples/incluster_eventing/src/receiver-fn/config.yaml
  examples/python-text2img/Makefile
  examples/python-text2img/config.yaml
  examples/python-text2img/resources/function.yaml
Labels: documentation, area/serverless, area/cli

#1546 Migrate coreCommands to actionCommands
  config/serverless/templates/cli-extension.yaml
Labels: area/serverless, area/cli
